import {pdfCrest} from './pdf-crest';
import {pdfLogo} from './pdf-logo';
import {model303Pages} from './pdf303';
import {pdfFonts} from './pdf-fonts';
import { type Declaration, type Receipt } from './tax';
export function pdfBytes(d:Declaration,r?:Receipt):Uint8Array{return pdfFromStreams(model303Pages(d,r));}
export function pdfFromStreams(streams:string[],size={width:595,height:842}):Uint8Array{
const objects:string[]=[];objects[1]='<< /Type /Catalog /Pages 2 0 R >>';pdfFonts.forEach((f,i)=>{const descriptor=5+i*2,file=descriptor+1,binary=atob(f.data);objects[3+i]=`<< /Type /Font /Subtype /TrueType /BaseFont /${f.name} /FirstChar 32 /LastChar 255 /Widths [${f.widths.join(' ')}] /FontDescriptor ${descriptor} 0 R /Encoding /WinAnsiEncoding >>`;objects[descriptor]=`<< /Type /FontDescriptor /FontName /${f.name} /Flags 32 /FontBBox [${f.bbox.join(' ')}] /ItalicAngle 0 /Ascent ${f.ascent} /Descent ${f.descent} /CapHeight 730 /StemV 80 /FontFile2 ${file} 0 R >>`;objects[file]=`<< /Length ${binary.length} /Length1 ${binary.length} >>\nstream\n${binary}\nendstream`;});const ids:number[]=[];
const logo=atob(pdfLogo.data);objects[9]=`<< /Type /XObject /Subtype /Image /Width ${pdfLogo.width} /Height ${pdfLogo.height} /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /FlateDecode /Length ${logo.length} >>\nstream\n${logo}\nendstream`;
const crest=atob(pdfCrest);objects[10]=`<< /Type /XObject /Subtype /Image /Width 171 /Height 176 /ColorSpace /DeviceRGB /BitsPerComponent 8 /Filter /DCTDecode /Length ${crest.length} >>\nstream\n${crest}\nendstream`;
streams.forEach((stream,i)=>{const id=11+i*2;ids.push(id);objects[id]=`<< /Type /Page /Parent 2 0 R /MediaBox [0 0 ${size.width} ${size.height}] /Resources << /Font << /F1 3 0 R /F2 4 0 R >> /XObject << /Logo 9 0 R /Crest 10 0 R >> >> /Contents ${id+1} 0 R >>`;objects[id+1]=`<< /Length ${stream.length} >>\nstream\n${stream}endstream`;});objects[2]=`<< /Type /Pages /Kids [${ids.map(i=>i+' 0 R').join(' ')}] /Count ${streams.length} >>`;let s='%PDF-1.4\n';const offsets=[0];for(let i=1;i<objects.length;i++){offsets[i]=s.length;s+=`${i} 0 obj\n${objects[i]}\nendobj\n`;}const x=s.length;s+=`xref\n0 ${objects.length}\n0000000000 65535 f \n`;for(let i=1;i<objects.length;i++)s+=`${String(offsets[i]).padStart(10,'0')} 00000 n \n`;s+=`trailer\n<< /Size ${objects.length} /Root 1 0 R >>\nstartxref\n${x}\n%%EOF`;return Uint8Array.from(s,c=>c.charCodeAt(0));}
export function downloadPDF(d:Declaration,r?:Receipt){const bytes=pdfBytes(d,r);const a=document.createElement('a');const url=URL.createObjectURL(new Blob([bytes as BlobPart],{type:'application/pdf'}));a.href=url;a.download=`${r?'Justificante':'Borrador'}_SIMULADO_${d.model}_${d.year}_${d.period}.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
