import {pdfFromStreams} from './receipt';
import {pdfFonts} from './pdf-fonts';
import {money} from './tax';
import {reportNames,reportFields,reportScope,reportTotals,rowAmount,type Report,type ReportReceipt} from './reports';
const escape=(s:string)=>s.replace(/[–—−]/g,'-').replace(/€/g,'EUR').replace(/[^\x20-\xFF]/g,'?').replace(/\\/g,'\\\\').replace(/\(/g,'\\(').replace(/\)/g,'\\)');
const width=(s:string,size:number,bold=false)=>Array.from(s).reduce((n,c)=>n+(pdfFonts[bold?1:0].widths[c.charCodeAt(0)-32]||600),0)*size/1000;
export function reportPDF(d:Report,r?:ReportReceipt){let out='';const pages:string[]=[];const txt=(s:string,x:number,y:number,size=10,bold=false)=>{out+=`BT /F${bold?2:1} ${size} Tf 0 0 0 rg 1 0 0 1 ${x} ${842-y} Tm (${escape(s)}) Tj ET\n`;};const rect=(x:number,y:number,w:number,h:number)=>{out+=`q 0 0 0 RG 0.55 w ${x} ${842-y-h} ${w} ${h} re S Q\n`;};const lines=(s:string,x:number,y:number,max=510,size=9,bold=false)=>{let row='';for(const word of s.split(/\s+/)){if(width(row+' '+word,size,bold)>max&&row){txt(row,x,y,size,bold);row=word;y+=size+4;}else row+=(row?' ':'')+word;}txt(row,x,y,size,bold);return y;};const finish=()=>{txt('SIMULACIÓN EDUCATIVA - SIN VALIDEZ TRIBUTARIA',34,808,8,true);txt('Página '+(pages.length+1),500,808,8);txt('No se ha presentado información ante la Agencia Tributaria.',34,823,7);pages.push(out);out='';};
rect(34,29,527,78);out+='q 60 0 0 62 43 744 cm /Crest Do Q\n';const center=(s:string,y:number)=>txt(s,335-width(s,14,true)/2,y,14,true);center('INFORMACIÓN DE LA PRESENTACIÓN DE LA',57);center('DECLARACIÓN',76);txt('MODELO '+d.model,450,94,13,true);txt('Registro',34,140,13,true);rect(34,155,527,69);txt(r?'Presentación realizada el '+new Date(r.date).toLocaleString('es-ES',{timeZone:'Europe/Madrid'}):'BORRADOR - PENDIENTE DE PRESENTACIÓN SIMULADA',43,177);txt('Expediente/Referencia (registro simulado): '+(r?.id||'Sin asignar'),43,194);txt('Código Seguro de Verificación (simulado): '+(r?.csv||'Sin asignar'),43,211);txt('Presentador',34,257,13,true);rect(34,272,527,80);txt('NIF Presentador: '+d.nif,43,293);const yName=lines('Apellidos y Nombre/Razón social: '+d.company,43,310,510,10);txt('En calidad de: Declarante',43,yName+18);rect(34,437,527,53);txt('Vía de entrada: Presentación por internet (simulada)',43,459);txt('Número de justificante: '+(r?.id||'Sin asignar'),43,478);finish();
const heading=()=>{rect(34,30,527,62);txt('Modelo '+d.model,44,53,16,true);txt('Ejercicio '+d.year+' · Periodo '+d.period,365,53,10);lines(reportNames[d.model],44,75,500,9);};heading();txt('Declarante y resumen de la declaración',34,130,13,true);let y=160;for(const [label,value] of [['NIF',d.nif],['Razón social',d.company],['Persona de contacto',d.contact],['Teléfono',d.phone],['Alumno / referencia',d.alias||'—'],['Tipo de declaración',d.kind==='original'?'Original':d.kind==='complementaria'?'Complementaria por inclusión de datos':'Sustitutiva'],['Justificante anterior',d.previous||'—']]){y=lines(label+': '+value,43,y,510,10)+28;}
const totals=reportTotals(d);txt('Resumen',34,y+15,13,true);y+=48;for(const [label,value] of [['Registros de '+(d.model==='190'?'percepciones':d.model==='347'?'declarados':'operaciones'),String(totals.count)],['Importe total',money(totals.total)+' EUR'],...(d.model==='190'?[['Retenciones e ingresos a cuenta',money(totals.withheld)+' EUR']]:[]),...(d.model==='349'?[['Registros de rectificaciones',String(totals.corrections)],['Bases imponibles rectificadas',money(totals.corrected)+' EUR']]:[])]){txt(label,43,y,10);txt(value,410,y,10,true);y+=28;}lines('Alcance de la práctica: '+reportScope[d.model],43,690,508,8);finish();
for(const [i,row] of d.rows.entries()){heading();txt('Registro '+(i+1)+' de '+d.rows.length,34,125,12,true);y=153;for(const field of reportFields(d.model,row.data)){const raw=row.data[field.key]||'';const value=field.kind==='select'?(field.options?.find(([key])=>key===raw)?.[1]||'—'):(raw||'—');if(y>748){finish();heading();txt('Registro '+(i+1)+' · continuación',34,125,12,true);y=153;}const end=lines(field.label,43,y,275,8);const endValue=lines(value,330,y,220,9,true);y=Math.max(end,endValue)+22;}if(y>745){finish();heading();y=130;}txt(d.model==='347'?'Importe anual (IVA incluido)':'Importe del registro',43,y+10,10);txt(money(rowAmount(d.model,row))+' EUR',400,y+10,10,true);finish();}return pdfFromStreams(pages);}
export function downloadReport(d:Report,r?:ReportReceipt){const bytes=reportPDF(d,r);const url=URL.createObjectURL(new Blob([bytes as BlobPart],{type:'application/pdf'}));const a=document.createElement('a');a.href=url;a.download=`${r?'Justificante':'Borrador'}_SIMULADO_${d.model}_${d.year}_${d.period}.pdf`;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
