import {getProfile} from '../local/profile';
import {amount,round,periodOptions} from './tax';
export const reportModels=['190','347','349'] as const;
export type ReportModel=typeof reportModels[number];
export const reportNames:Record<ReportModel,string>={'190':'Retenciones e ingresos a cuenta. Resumen anual.','347':'Declaración anual de operaciones con terceras personas.','349':'Declaración recapitulativa de operaciones intracomunitarias.'};
export const reportHelp:Record<ReportModel,string>={'190':'https://sede.agenciatributaria.gob.es/Sede/procedimientoini/GI10.shtml','347':'https://sede.agenciatributaria.gob.es/Sede/procedimientoini/GI27.shtml','349':'https://sede.agenciatributaria.gob.es/Sede/procedimientoini/GI28.shtml'};
export type ReportRow={id:string;data:Record<string,string>};
export type Report={model:ReportModel;year:string;period:string;nif:string;company:string;contact:string;phone:string;alias:string;rows:ReportRow[];previous:string;kind:string;importWarnings?:string[]};
export type ReportReceipt={id:string;csv:string;date:string;report:Report};
export type ReportField={key:string;label:string;kind?:'money'|'select'|'integer';options?:[string,string][];required?:boolean};
const f=(key:string,label:string,kind?:ReportField['kind'],options?:[string,string][],required=false):ReportField=>({key,label,kind,options,required});
export const countries:[string,string][]=[['AT','Austria'],['BE','Bélgica'],['BG','Bulgaria'],['CY','Chipre'],['CZ','Chequia'],['DE','Alemania'],['DK','Dinamarca'],['EE','Estonia'],['EL','Grecia'],['FI','Finlandia'],['FR','Francia'],['HR','Croacia'],['HU','Hungría'],['IE','Irlanda'],['IT','Italia'],['LT','Lituania'],['LU','Luxemburgo'],['LV','Letonia'],['MT','Malta'],['NL','Países Bajos'],['PL','Polonia'],['PT','Portugal'],['RO','Rumanía'],['SE','Suecia'],['SI','Eslovenia'],['SK','Eslovaquia'],['XI','Irlanda del Norte (bienes)']];
const yn:[string,string][]=[['NO','No'],['SI','Sí']];
export function reportFields(model:ReportModel,row:Record<string,string>={}):ReportField[]{
const identity=[f('nif',model==='349'?'NIF-IVA (sin prefijo del país)':'NIF de prácticas',undefined,undefined,true),f('name','Apellidos y nombre o razón social',undefined,undefined,true)];
if(model==='190')return [...identity,f('province','Código de provincia (01–52 o 99)',undefined,undefined,true),f('key','Clave de percepción','select',[['A','A · Rendimientos del trabajo'],['G','G · Actividades profesionales'],['L','L · Rentas exentas']],true),...(row.key==='G'?[f('subkey','Subclave','select',[['01','01 · Tipo general'],['02','02 · Supuestos específicos del art. 95.1 RIRPF'],['03','03 · Inicio de actividad profesional'],['04','04 · Actividades del art. 95.1.d RIRPF'],['05','05 · Propiedad intelectual, tipo general'],['06','06 · Propiedad intelectual, tipo reducido'],['07','07 · Anticipos de derechos de autor'],['08','08 · Cesión de derechos de imagen']],true)]:[]),...(row.key==='L'?[f('subkey','Subclave de renta exenta (dos cifras)',undefined,undefined,true)]:[]),f('gross','Percepciones dinerarias íntegras','money'),f('withheld','Retenciones practicadas','money'),f('inKind','Valoración de percepciones en especie','money'),f('onAccount','Ingresos a cuenta efectuados','money'),f('passedOn','Ingresos a cuenta repercutidos','money'),f('accrual','Ejercicio de devengo (solo si es distinto)'),...(row.key==='A'?[f('birth','Año de nacimiento','integer',undefined,true),f('family','Situación familiar','select',[['1','1 · Unidad familiar con hijos, sin cónyuge'],['2','2 · Casado/a, cónyuge con rentas ≤ 1.500 €'],['3','3 · Otras situaciones']],true),...(row.family==='2'?[f('spouse','NIF del cónyuge',undefined,undefined,true)]:[]),f('contract','Contrato o relación','select',[['1','1 · General'],['2','2 · Duración inferior al año'],['3','3 · Relación laboral especial dependiente'],['4','4 · Relación esporádica por jornadas']],true),f('disability','Discapacidad','select',[['0','Sin discapacidad'],['1','Grado ≥ 33 % e inferior al 65 %'],['2','Grado ≥ 33 % e inferior al 65 %, con ayuda o movilidad reducida'],['3','Grado ≥ 65 %']]),f('reduction','Reducciones aplicables','money'),f('expenses','Gastos deducibles','money'),f('children','Descendientes computados por entero','integer'),f('childrenHalf','Descendientes computados por mitad','integer'),f('under3','Descendientes menores de 3 años, entero','integer'),f('under3Half','Descendientes menores de 3 años, mitad','integer'),f('ancestors','Ascendientes menores de 75 años','integer'),f('ancestors75','Ascendientes de 75 o más años','integer'),f('pension','Pensiones compensatorias al cónyuge','money'),f('maintenance','Anualidades por alimentos','money')]:[])];
if(model==='347')return [...identity,f('province','Código de provincia (01–52 o 99)',undefined,undefined,true),...(row.province==='99'?[f('country','Código de país (dos letras)',undefined,undefined,true)]:[]),f('key','Clave de operación','select',[['A','A · Adquisiciones de bienes y servicios'],['B','B · Entregas de bienes y prestaciones de servicios']],true),...['1','2','3','4'].map(q=>f('q'+q,'Importe '+q+'.º trimestre (IVA incluido)','money')),f('cash','Importe percibido en metálico superior a 6.000 €','money'),f('cashYear','Ejercicio de las operaciones cobradas en metálico')];
return [f('country','País del operador','select',countries,true),...identity,f('key','Clave de operación','select',[['A','A · Adquisiciones intracomunitarias de bienes'],['E','E · Entregas intracomunitarias de bienes'],['S','S · Prestaciones intracomunitarias de servicios'],['I','I · Adquisiciones intracomunitarias de servicios'],['T','T · Operaciones triangulares'],['M','M · Entregas posteriores a importación exenta'],['H','H · Entregas posteriores a importación exenta, representante fiscal']],true),f('rectification','Rectificación de un periodo anterior','select',yn),...(row.rectification==='SI'?[f('priorYear','Ejercicio de la operación rectificada',undefined,undefined,true),f('priorPeriod','Periodo de la operación rectificada','select',periodOptions.map(p=>[p.value,p.label]),true),f('priorBase','Base imponible declarada anteriormente','money'),f('base','Base imponible rectificada (nuevo total)','money')]:[f('base','Base imponible total de las operaciones','money')])];
}
export const reportScope:Record<ReportModel,string>={'190':'Prácticas de nóminas ordinarias (clave A) y profesionales (clave G). Incluye retribuciones dinerarias y en especie y datos personales básicos. Admite rentas exentas (clave L), con subclave indicada por el docente. No incluye prestaciones por incapacidad laboral ni todos los supuestos familiares especiales.','347':'Prácticas de compras y ventas ordinarias (claves A y B), con desglose trimestral y cobros en metálico. No incluye el anexo de inmuebles ni operaciones de seguros, criterio de caja u otros supuestos especiales.','349':'Incluye las claves A, E, S, I, T, M y H y rectificaciones de periodos anteriores. No incluye ventas en consigna ni periodos trimestrales truncados. Elija la periodicidad que corresponda al supuesto de clase.'};
export const blankReport=(model:ReportModel):Report=>({model,year:model==='349'?'2026':'2025',period:model==='349'?'1T':'0A',nif:getProfile().nif,company:getProfile().name,contact:'',phone:'',alias:'',rows:[],previous:'',kind:'original'});
export const reportId=()=>Array.from(crypto.getRandomValues(new Uint8Array(16)),b=>b.toString(16).padStart(2,'0')).join('').toUpperCase();
export const newReportRow=(model:ReportModel):ReportRow=>({id:reportId(),data:{key:model==='349'?'E':'A',province:'47',country:model==='349'?'FR':'',subkey:'01',family:'3',contract:'1',disability:'0',rectification:'NO'}});
export function rowAmount(model:ReportModel,r:ReportRow){const n=(k:string)=>amount(r.data[k])||0;return round(model==='190'?n('gross')+n('inKind'):model==='347'?n('q1')+n('q2')+n('q3')+n('q4'):n('base'));}
export function reportTotals(d:Report){const ordinary=d.rows.filter(r=>d.model!=='349'||r.data.rectification!=='SI');const corrected=d.rows.filter(r=>d.model==='349'&&r.data.rectification==='SI');return{count:ordinary.length,total:round(ordinary.reduce((n,r)=>n+rowAmount(d.model,r),0)),withheld:round(d.rows.reduce((n,r)=>n+(amount(r.data.withheld)||0)+(amount(r.data.onAccount)||0),0)),corrections:corrected.length,corrected:round(corrected.reduce((n,r)=>n+rowAmount(d.model,r),0))};}
export function checkReport(d:Report){const errors:string[]=[],warnings:string[]=[];if(!/^[A-Z0-9-]{5,16}$/i.test(d.nif))errors.push('Indique un NIF de prácticas válido para el declarante.');if(!d.company.trim())errors.push('Indique la razón social del declarante.');if(!/^\d{4}$/.test(d.year)||Number(d.year)<2020||Number(d.year)>2099)errors.push('Indique un ejercicio entre 2020 y 2099.');if(d.model==='349'&&!periodOptions.some(p=>p.value===d.period))errors.push('Seleccione un mes o trimestre.');if(!d.contact.trim())errors.push('Indique la persona de contacto.');if(!/^\d{9}$/.test(d.phone))errors.push('Indique un teléfono de prácticas de nueve cifras (puede usar 000000000).');if(d.model!=='349'&&d.period!=='0A')errors.push('El periodo de esta declaración debe ser anual.');if(!d.rows.length)errors.push('Añada al menos un registro.');if(d.kind!=='original'&&!d.previous.trim())errors.push('Indique el justificante anterior.');const seen=new Set<string>();d.rows.forEach((r,i)=>{const v=r.data,prefix=`Registro ${i+1}: `;for(const field of reportFields(d.model,v)){const s=v[field.key]||'';if(field.required&&!s.trim())errors.push(prefix+'cumplimente '+field.label+'.');if(field.kind==='select'&&s&&!field.options?.some(([k])=>k===s))errors.push(prefix+field.label+' no válido.');if(field.kind==='money'||field.kind==='integer'){const a=amount(s);if(!Number.isFinite(a)||Math.abs(a)>999999999.99)errors.push(prefix+field.label+': importe no válido.');else if(field.kind==='integer'&&(!Number.isInteger(a)||a<0))errors.push(prefix+field.label+': utilice un número entero positivo o cero.');else if(a<0&&!(d.model==='347'&&field.key.startsWith('q'))&&!(d.model==='190'&&['gross','inKind'].includes(field.key)))errors.push(prefix+field.label+': no admite valores negativos.');}}
if(d.model!=='349'&&!/^(0[1-9]|[1-4]\d|5[0-2]|99)$/.test(v.province||''))errors.push(prefix+'indique un código de provincia válido.');if(!/^[A-Z0-9-]{5,16}$/i.test(v.nif||''))errors.push(prefix+'revise el NIF de prácticas.');if(d.model==='190'){if(v.key==='L'&&!/^\d{2}$/.test(v.subkey||''))errors.push(prefix+'indique la subclave de renta exenta con dos cifras.');if(v.key==='A'&&(!/^\d{4}$/.test(v.birth||'')||Number(v.birth)>Number(d.year)))errors.push(prefix+'revise el año de nacimiento.');if(v.accrual&&(!/^\d{4}$/.test(v.accrual)||Number(v.accrual)>Number(d.year)))errors.push(prefix+'revise el ejercicio de devengo.');if(((amount(v.gross)||0)<0||(amount(v.inKind)||0)<0)&&!v.accrual)errors.push(prefix+'las percepciones negativas requieren el ejercicio de devengo anterior.');if((amount(v.passedOn)||0)>(amount(v.onAccount)||0))errors.push(prefix+'los ingresos repercutidos no pueden superar los efectuados.');if((amount(v.withheld)||0)>Math.max(amount(v.gross)||0,0))errors.push(prefix+'la retención no puede superar la percepción dineraria.');if(v.key==='A'&&(amount(v.under3)>amount(v.children)||amount(v.under3Half)>amount(v.childrenHalf)))errors.push(prefix+'los menores de 3 años no pueden superar el número de descendientes.');}
if(d.model==='347'){if(v.province==='99'&&!/^[A-Z]{2}$/.test(v.country||''))errors.push(prefix+'indique un país con dos letras.');if(Math.abs(rowAmount(d.model,r))<=3005.06&&(amount(v.cash)||0)<=6000)warnings.push(prefix+'el total no supera 3.005,06 €. Revise si esta operación debe declararse.');if((amount(v.cash)||0)>0&&(amount(v.cash)||0)<=6000)warnings.push(prefix+'la información de cobros en metálico se exige por encima de 6.000 €.');if((amount(v.cash)||0)>0&&!/^\d{4}$/.test(v.cashYear||''))errors.push(prefix+'indique el ejercicio del cobro en metálico.');}
if(d.model==='349'){if((v.nif||'').toUpperCase().startsWith(v.country))errors.push(prefix+'introduzca el NIF-IVA sin repetir el prefijo del país.');if(v.country==='XI'&&['S','I'].includes(v.key))errors.push(prefix+'Irlanda del Norte solo se admite para operaciones de bienes.');if(v.rectification==='SI'&&(!/^\d{4}$/.test(v.priorYear||'')||Number(v.priorYear)>Number(d.year)))errors.push(prefix+'revise el ejercicio de la rectificación.');if(v.rectification!=='SI'&&rowAmount(d.model,r)<=0)errors.push(prefix+'la base imponible debe ser positiva.');}
const key=[v.nif,v.key,d.model==='190'&&['G','L'].includes(v.key)?v.subkey:'',d.model==='349'?v.country:'',v.rectification==='SI'?v.priorYear+'-'+v.priorPeriod:'',v.accrual||''].join('|');if(seen.has(key))errors.push(prefix+'existe otro registro con la misma identificación y clave; agrupe sus importes.');seen.add(key);});return{errors,warnings};}
