import {getProfile} from '../local/profile';
export type Model='303'|'111'|'115';
export type Declaration={model:Model;company:string;nif:string;alias:string;year:string;period:string;values:Record<string,string>;complementary:boolean;previous:string;inactive:boolean;rectifying?:boolean;rectificationReasons?:string[];firstName?:string;iban?:string;identification?:Record<string,string>};
export type Receipt={id:string;csv:string;date:string;declaration:Declaration;method:string;bank:string;nrc:string;result:number;certificate:string};
export const names:Record<Model,string>={'303':'IVA. Autoliquidación.','111':'Retenciones e ingresos a cuenta. Rendimientos del trabajo y de actividades económicas, premios y determinadas ganancias patrimoniales e imputaciones de Renta. Autoliquidación.','115':'Retenciones e ingresos a cuenta. Rentas o rendimientos procedentes del arrendamiento o subarrendamiento de inmuebles urbanos.'};
export const shortNames={'303':'IVA · Autoliquidación','111':'Retenciones del trabajo y actividades económicas','115':'Retenciones de arrendamientos urbanos'};
export const sources:Record<Model,string>={'303':'https://sede.agenciatributaria.gob.es/Sede/procedimientoini/G414.shtml','111':'https://sede.agenciatributaria.gob.es/Sede/procedimientoini/GH01.shtml','115':'https://sede.agenciatributaria.gob.es/Sede/procedimientoini/GH02.shtml'};
export const groups111=[
{title:'I. Rendimientos del trabajo',rows:[{label:'Rendimientos dinerarios',codes:['01','02','03']},{label:'Rendimientos en especie',codes:['04','05','06']}]},
{title:'II. Rendimientos de actividades económicas',rows:[{label:'Rendimientos dinerarios',codes:['07','08','09']},{label:'Rendimientos en especie',codes:['10','11','12']}]},
{title:'III. Premios por la participación en juegos, concursos, rifas o combinaciones aleatorias',rows:[{label:'Premios en metálico',codes:['13','14','15']},{label:'Premios en especie',codes:['16','17','18']}]},
{title:'IV. Ganancias patrimoniales derivadas de los aprovechamientos forestales de los vecinos en montes públicos',rows:[{label:'Percepciones dinerarias',codes:['19','20','21']},{label:'Percepciones en especie',codes:['22','23','24']}]},
{title:'V. Contraprestaciones por la cesión de derechos de imagen',rows:[{label:'Contraprestaciones satisfechas',codes:['25','26','27']}]}];
export const vatRows=[{label:'Régimen general · 0 %',base:'150',rate:'151',quota:'152',pct:0},{label:'Régimen general · 4 %',base:'01',rate:'02',quota:'03',pct:4},{label:'Régimen general · 10 %',base:'04',rate:'05',quota:'06',pct:10},{label:'Régimen general · 21 %',base:'07',rate:'08',quota:'09',pct:21},{label:'Recargo de equivalencia · 1,75 %',base:'156',rate:'157',quota:'158',pct:1.75},{label:'Recargo de equivalencia · 0,50 %',base:'168',rate:'169',quota:'170',pct:0.5},{label:'Recargo de equivalencia · 1,40 %',base:'19',rate:'20',quota:'21',pct:1.4},{label:'Recargo de equivalencia · 5,20 %',base:'22',rate:'23',quota:'24',pct:5.2}];
export const otherVat=[{label:'Adquisiciones intracomunitarias de bienes y servicios',base:'10',quota:'11'},{label:'Otras operaciones con inversión del sujeto pasivo (excepto adquisiciones intracomunitarias)',base:'12',quota:'13'},{label:'Modificación de bases y cuotas',base:'14',quota:'15'},{label:'Modificación de bases y cuotas del recargo de equivalencia',base:'25',quota:'26'}];
export const deductions=[{label:'Por cuotas soportadas en operaciones interiores corrientes',base:'28',quota:'29'},{label:'Por cuotas soportadas en operaciones interiores con bienes de inversión',base:'30',quota:'31'},{label:'Por cuotas soportadas en las importaciones de bienes corrientes',base:'32',quota:'33'},{label:'Por cuotas soportadas en las importaciones de bienes de inversión',base:'34',quota:'35'},{label:'En adquisiciones intracomunitarias de bienes y servicios corrientes',base:'36',quota:'37'},{label:'En adquisiciones intracomunitarias de bienes de inversión',base:'38',quota:'39'},{label:'Rectificación de deducciones',base:'40',quota:'41'}];
export const round=(n:number)=>Math.round((n+Number.EPSILON)*100)/100;
export const amount=(s:string|undefined):number=>{if(!s?.trim())return 0;let t=s.trim().replace(/\s/g,'');if(t.includes(',')){if(!/^-?(?:\d+|\d{1,3}(?:\.\d{3})+)(?:,\d{1,2})?$/.test(t))return NaN;t=t.replace(/\./g,'').replace(',','.');}else if(/^-?\d{1,3}(?:\.\d{3})+$/.test(t))t=t.replace(/\./g,'');else if(!/^-?\d+(?:\.\d{1,2})?$/.test(t))return NaN;return Number(t);};
export const money=(n:number)=>Number.isFinite(n)?n.toLocaleString('es-ES',{minimumFractionDigits:2,maximumFractionDigits:2}):'—';
export const blank=(model:Model,company=getProfile().name,nif=getProfile().nif):Declaration=>({model,company,nif,alias:'',year:'2026',period:'1T',values:{},complementary:false,previous:'',inactive:false});
export function calculate(d:Declaration){const v:Record<string,number>={};for(const[k,s]of Object.entries(d.values))v[k]=amount(s);const n=(k:string)=>v[k]||0;
if(d.model==='303'){vatRows.forEach(r=>{v[r.rate]=r.pct;v[r.quota]=round(n(r.base)*r.pct/100)});v['27']=round([...vatRows.map(r=>r.quota),...otherVat.map(r=>r.quota)].reduce((s,k)=>s+n(k),0));v['45']=round([...deductions.map(r=>r.quota),'42','43','44'].reduce((s,k)=>s+n(k),0));v['46']=round(n('27')-n('45'));v['64']=round(n('46')+n('76'));v['65']=100;v['66']=n('64');v['87']=round(n('110')-n('78'));if(!d.rectifying){v['70']=0;v['109']=0;v['108']=0;}else if(!d.rectificationReasons?.includes('criterio'))v['108']=0;v['69']=round(n('66')+n('77')-n('78')+n('108'));v['71']=round(n('69')-n('70')+n('109'));v['111']=d.rectifying?round(Math.min(n('70'),Math.max(-n('71'),0))):0;}
else if(d.model==='111'){v['28']=round(groups111.flatMap(g=>g.rows).reduce((s,r)=>s+n(r.codes[2]),0));if(!d.complementary)v['29']=0;v['30']=round(n('28')-n('29'));}else{if(!d.complementary)v['04']=0;v['05']=round(n('03')-n('04'));}return{values:v,result:v[d.model==='303'?'71':d.model==='111'?'30':'05']||0};}
export function validate(d:Declaration):string[]{const e:string[]=[];const c=calculate(d);const n=(k:string)=>c.values[k]||0;if(!d.company.trim())e.push('Indique los apellidos o la razón social del declarante.');if(!/^[A-Z0-9-]{5,16}$/i.test(d.nif))e.push('Indique un NIF de prácticas de entre 5 y 16 caracteres, sin espacios.');if(!/^\d{4}$/.test(d.year))e.push('El ejercicio debe contener cuatro cifras.');if(!periodOptions.some(p=>p.value===d.period))e.push('Seleccione un periodo mensual o trimestral.');if(d.model==='303'&&d.identification?.redeme==='SI'&&!isMonthly(d.period))e.push('La inscripción en devolución mensual requiere un periodo mensual.');if(d.model==='303'){for(const f of identificationQuestions){const v=d.identification?.[f.key]??f.initial;if(f.unsupported&&v!==f.initial)e.push(f.label+' Este supuesto todavía no está disponible en la liquidación del simulador.');}}const signed=d.model==='303'?['14','15','25','26','40','41','43','44','108']:[];Object.entries(d.values).forEach(([k,s])=>{const a=amount(s);if(!Number.isFinite(a))e.push(`Casilla ${k}: introduzca un importe válido (ejemplo: 1.250,50).`);else if(Math.abs(a)>999999999.99)e.push(`Casilla ${k}: importe fuera del límite de la simulación.`);else if(a<0&&!signed.includes(k))e.push(`Casilla ${k}: el importe no puede ser negativo.`);});
if(d.model==='303'){if(d.rectifying){if(!d.previous.trim())e.push('Indique el número de justificante de la autoliquidación que rectifica.');if(!d.rectificationReasons?.some(r=>['general','criterio'].includes(r)))e.push('Seleccione al menos un motivo de rectificación.');if(Number(d.year)<2024||(d.year==='2024'&&!['09','10','11','12','3T','4T'].includes(d.period)))e.push('La autoliquidación rectificativa está disponible desde septiembre / 3T de 2024.');}if(amount(d.values['108'])!==0&&(!d.rectifying||!d.rectificationReasons?.includes('criterio')))e.push('La casilla 108 requiere una rectificativa por discrepancia de criterio administrativo.');if(n('78')>n('110'))e.push('Casilla 78: no puede superar las cuotas pendientes de la casilla 110.');if(n('78')>Math.max(n('66')+n('77'),0))e.push('Casilla 78: no puede superar el resultado positivo de la suma de las casillas 66 y 77.');if(d.inactive&&Object.entries(d.values).some(([k,s])=>!['110','78','70','109','108'].includes(k)&&amount(s)!==0))e.push('Ha marcado Sin actividad, pero existen operaciones en la declaración.');[...otherVat,...deductions].forEach(r=>{if(n(r.quota)!==0&&n(r.base)===0)e.push(`Casilla ${r.base}: indique la base correspondiente a la cuota ${r.quota}.`);});}
else{const rows=d.model==='111'?groups111.flatMap(g=>g.rows).map(r=>r.codes):[['01','02','03']];rows.forEach(([p,b,q])=>{if(!Number.isInteger(n(p)))e.push(`Casilla ${p}: el número de perceptores debe ser entero.`);if((n(b)>0||n(q)>0)&&n(p)<1)e.push(`Casilla ${p}: indique al menos un perceptor.`);if(n(p)>0&&n(b)<=0)e.push(`Casilla ${b}: indique el importe de las percepciones o la base.`);if(n(q)>n(b))e.push(`Casilla ${q}: la retención no puede superar las percepciones o la base.`);});if(rows.every(([p,b])=>n(p)===0&&n(b)===0))e.push('Cumplimente los perceptores y las percepciones o bases del periodo.');if(c.result<0)e.push('El resultado de una declaración complementaria no puede ser negativo.');if(d.complementary&&!d.previous.trim())e.push('Indique el número de justificante de la declaración anterior.');}return e;}
export function fieldLabels(model:Model):Record<string,string>{if(model==='115')return{'01':'Número de perceptores','02':'Base de las retenciones e ingresos a cuenta','03':'Retenciones e ingresos a cuenta','04':'A deducir: resultados anteriores','05':'Resultado a ingresar'};if(model==='111'){const l:Record<string,string>={};groups111.forEach(g=>g.rows.forEach(r=>r.codes.forEach((k,i)=>l[k]=g.title+' · '+r.label+' · '+['N.º perceptores','Importe percepciones','Retenciones / ingresos a cuenta'][i])));return{...l,'28':'Total de retenciones e ingresos a cuenta','29':'A deducir: resultados anteriores','30':'Resultado a ingresar'};}const l:Record<string,string>={};vatRows.forEach(r=>{l[r.base]=r.label+' · Base';l[r.rate]=r.label+' · Tipo';l[r.quota]=r.label+' · Cuota'});[...otherVat,...deductions].forEach(r=>{l[r.base]=r.label+' · Base';l[r.quota]=r.label+' · Cuota'});return{...l,'27':'Total cuota devengada','42':'Compensaciones régimen agricultura, ganadería y pesca','43':'Regularización bienes de inversión','44':'Regularización por porcentaje definitivo de prorrata','45':'Total a deducir','46':'Resultado régimen general','59':'Entregas intracomunitarias de bienes y servicios','60':'Exportaciones y operaciones asimiladas','120':'Operaciones no sujetas por reglas de localización (excepto las incluidas en la casilla 123)','122':'Operaciones sujetas con inversión del sujeto pasivo','123':'Operaciones no sujetas por reglas de localización acogidas a los regímenes especiales de ventanilla única','124':'Operaciones sujetas y acogidas a los regímenes especiales de ventanilla única','76':'Regularización cuotas art. 80.Cinco.5ª LIVA','77':'IVA a la importación liquidado por la Aduana pendiente de ingreso','64':'Suma de resultados [46] + [58] + [76]','65':'Porcentaje atribuible al Estado','66':'Atribuible a la Administración del Estado','110':'Cuotas a compensar pendientes de periodos anteriores','78':'Cuotas a compensar de periodos anteriores aplicadas en este periodo','87':'Cuotas a compensar de periodos previos pendientes para periodos posteriores','69':'Resultado','71':'Resultado de la liquidación','70':'Resultado a ingresar de la anterior autoliquidación o liquidación administrativa','109':'Devoluciones acordadas correspondientes al mismo ejercicio y periodo','108':'Ajuste por discrepancia de criterio administrativo','111':'Importe a regularizar por la rectificación'};}

export const isMonthly=(period:string)=>/^(0[1-9]|1[0-2])$/.test(period);
export const periodOptions=[...['1T','2T','3T','4T'].map((value,i)=>({value,label:value+' · '+(i+1)+'.º trimestre'})),...['Enero','Febrero','Marzo','Abril','Mayo','Junio','Julio','Agosto','Septiembre','Octubre','Noviembre','Diciembre'].map((label,i)=>({value:String(i+1).padStart(2,'0'),label:String(i+1).padStart(2,'0')+' · '+label}))];
export const identificationQuestions=[
{key:'foral',label:'Sujeto pasivo que tributa exclusivamente a una Administración tributaria Foral con IVA a la importación liquidado por la Aduana pendiente de ingreso',initial:'NO',unsupported:true},
{key:'redeme',label:'¿Está inscrito en el Registro de devolución mensual (Art. 30 RIVA)?',initial:'NO'},
{key:'general',label:'¿Tributa exclusivamente en régimen general?',initial:'SI',unsupported:true},
{key:'simplificado',label:'¿Tributa exclusivamente en régimen simplificado?',initial:'NO',unsupported:true},
{key:'conjunta',label:'¿Es autoliquidación conjunta (Art. 71.6 RIVA)?',initial:'NO',unsupported:true},
{key:'concurso',label:'¿Ha sido declarado en concurso de acreedores en el presente periodo de liquidación?',initial:'NO',unsupported:true},
{key:'caja',label:'¿Ha optado por el régimen especial del criterio de Caja (art. 163 undecies LIVA)?',initial:'NO',unsupported:true},
{key:'destinatarioCaja',label:'¿Es destinatario de operaciones a las que se aplique el régimen especial del criterio de caja?',initial:'NO',unsupported:true},
{key:'prorrata',label:'Opción por la aplicación de la prorrata especial (artículo 103.Dos.1º LIVA)',initial:'NO',unsupported:true},
{key:'revocacion',label:'Revocación de la opción por la aplicación de la prorrata especial (artículo 103.Dos.1º LIVA)',initial:'NO',unsupported:true},
{key:'exonerado390',label:'¿Está exonerado de la Declaración-resumen anual del IVA, modelo 390?',initial:'NO'},
{key:'volumen',label:'¿Existe volumen anual de operaciones (art. 121 LIVA)?',initial:'NO'}];
export const canRefund=(d:Declaration)=>d.model==='303'&&(d.period==='4T'||d.period==='12'||(isMonthly(d.period)&&d.identification?.redeme==='SI'));
export const normalizeIBAN=(s:string)=>s.replace(/\s/g,'').toUpperCase();
// Format-only check: intentionally accepts fictitious account numbers for training.
export const validPracticeIBAN=(s:string)=>/^ES\d{22}$/.test(normalizeIBAN(s));

export function retentionColumns(code:string){const species=['04','10','16','22'].includes(code);return ['N.º de perceptores',code==='25'?'Contraprestaciones satisfechas':species?'Valor percepciones en especie':'Importe de las percepciones',species||code==='25'?'Importe de los ingresos a cuenta':'Importe de las retenciones'];}
export const officialHelp:Record<Model,string>={
'303':'https://sede.agenciatributaria.gob.es/Sede/todas-gestiones/impuestos-tasas/iva/modelo-303-iva-autoliquidacion_/instrucciones-2026.html',
'111':'https://sede.agenciatributaria.gob.es/Sede/ayuda/consultas-informaticas/presentacion-declaraciones-ayuda-tecnica/modelo-111/presentacion-electronica-modelo-111.html',
'115':'https://sede.agenciatributaria.gob.es/Sede/ayuda/consultas-informaticas/presentacion-declaraciones-ayuda-tecnica/modelo-115/presentacion-electronica-modelo-115.html'};

// The portion corresponding to the prior positive return belongs in 111,
// separately from the ordinary VAT credit (72 / 73).
export function settlement(d:Declaration,method:string){const c=calculate(d);const correction=d.model==='303'?(c.values['111']||0):0;const credit=round(Math.max(-c.result-correction,0));return{correction,credit,compensation:method==='compensar'?credit:0,refund:method==='devolver'?round(credit+(c.values['87']||0)):0};}
export function rectificationFrom(r:Receipt):Declaration{const c=calculate(r.declaration);return{...r.declaration,values:{...r.declaration.values,'70':String(Math.max(c.values['69']||0,0)),'109':'0','108':''},complementary:false,rectifying:true,previous:r.id,rectificationReasons:['general']};}
