'use client';
import {companyFetch,companyUrl,clientCompany} from '@/lib/company-client';

import {useCallback,useEffect,useRef,useState,type FormEvent,type MouseEvent} from 'react';
import {BookOpen,CheckCircle2,FileCheck2,FileText,FolderOpen,HelpCircle,Info,Loader2,Search} from 'lucide-react';
import {DeleteRecord} from '@/components/practice/delete-record';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Checkbox} from '@/components/ui/checkbox';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import SedeHeader from './sede-header';
import ContractModels from './contract-models';
import {newMailId} from '@/lib/mail-types';
import {sepeDate,type SepeHistory,type SepePreview,type SepeReceipt} from '@/lib/sepe-types';
import {ContractCard} from './contract-details';
import {sepeViewFromSearch,sepeViewSearch,sepeViewTitles,type SepeView} from '@/lib/sepe-navigation';
const today=()=>new Date().toLocaleDateString('sv-SE',{timeZone:'Europe/Madrid'});
const pdfUrl=(id:string)=>'/api/sepe?'+new URLSearchParams({batch:id,pdf:'1'});
const receiptUrl=(id:string)=>'/servicios/sepe/justificante?'+new URLSearchParams({id});
async function post<T>(payload:unknown):Promise<T>{const response=await companyFetch('/api/sepe',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(payload)});const data=await response.json() as T&{error?:string;batchId?:string};if(!response.ok)throw Object.assign(new Error(data.error||'No se ha podido completar la operación.'),{batchId:data.batchId});return data;}
export default function SepeWorkspace(){
 const [help,setHelp]=useState(false);
 const [tab,setTab]=useState<SepeView>('services'),[busy,setBusy]=useState(false),[dragging,setDragging]=useState(false),[preview,setPreview]=useState<SepePreview|null>(null),[file,setFile]=useState<{filename:string;file:string;size:number}|null>(null),[error,setError]=useState(''),[conflict,setConflict]=useState(''),[consent,setConsent]=useState(false),[warningsAccepted,setWarningsAccepted]=useState(false),[communicationDate,setCommunicationDate]=useState(''),[done,setDone]=useState<SepeReceipt|null>(null);
 const [history,setHistory]=useState<SepeHistory|null>(null),[historyBusy,setHistoryBusy]=useState(false),[historyError,setHistoryError]=useState(''),[query,setQuery]=useState(''),[from,setFrom]=useState(''),[to,setTo]=useState(''),[filter,setFilter]=useState({q:'',from:'',to:'',page:0});
 const input=useRef<HTMLInputElement>(null),requestId=useRef(''),loadId=useRef(0),reviewHeading=useRef<HTMLHeadingElement>(null),resultHeading=useRef<HTMLHeadingElement>(null),busyRef=useRef(false);
 const pageHeading=useRef<HTMLHeadingElement>(null);
 const viewHref=(view:SepeView)=>companyUrl('/servicios/sepe'+sepeViewSearch(view));
 function navigate(view:SepeView,e?:MouseEvent<HTMLAnchorElement>){
  if(e&&(e.button!==0||e.metaKey||e.ctrlKey||e.shiftKey||e.altKey))return;
  e?.preventDefault();
  if(view!==tab){window.history.pushState(window.history.state,'',companyUrl('/servicios/sepe'+sepeViewSearch(view,window.location.hash.split('?')[1]||'')));setTab(view);window.dispatchEvent(new HashChangeEvent('hashchange'));}
  requestAnimationFrame(()=>pageHeading.current?.focus());
 }
 const load=useCallback(async()=>{const generation=++loadId.current;setHistoryBusy(true);setHistoryError('');try{const r=await companyFetch('/api/sepe?'+new URLSearchParams({...filter,page:String(filter.page)}),{cache:'no-store'});const d=await r.json() as SepeHistory&{error?:string};if(!r.ok)throw Error(d.error);if(generation===loadId.current)setHistory(d);}catch(e){if(generation===loadId.current)setHistoryError(e instanceof Error?e.message:'No se puede consultar el historial.');}finally{if(generation===loadId.current)setHistoryBusy(false);}},[filter]);
 useEffect(()=>{setCommunicationDate(today());const sync=()=>setTab(sepeViewFromSearch(window.location.hash.split('?')[1]||''));sync();window.addEventListener('popstate',sync);window.addEventListener('hashchange',sync);return()=>{window.removeEventListener('popstate',sync);window.removeEventListener('hashchange',sync);};},[]);
 useEffect(()=>{document.title=sepeViewTitles[tab]+' · SEPE | Simulación educativa';},[tab]);
 useEffect(()=>{void load();return()=>{loadId.current++;};},[load]);
 useEffect(()=>{if(preview)reviewHeading.current?.focus();},[preview]);
 useEffect(()=>{if(done)resultHeading.current?.focus();},[done]);
 function reset(){setFile(null);setPreview(null);setDone(null);setError('');setConflict('');setConsent(false);setWarningsAccepted(false);requestId.current='';if(input.current)input.current.value='';}
 async function inspect(selected?:File){
  if(!selected||busyRef.current)return;reset();
  if(!/\.xml$/i.test(selected.name)||selected.size>1024*1024||!selected.size){setError('Selecciona un archivo XML de hasta 1 MB.');return;}
  busyRef.current=true;setBusy(true);
  try{const bytes=new Uint8Array(await selected.arrayBuffer());let binary='';for(let i=0;i<bytes.length;i+=8192)binary+=String.fromCharCode(...bytes.subarray(i,i+8192));const uploaded={filename:selected.name,file:btoa(binary),size:selected.size};const d=await post<SepePreview>({action:'preview',...uploaded});setFile(uploaded);setPreview(d);requestId.current=newMailId();}catch(e){setError(e instanceof Error?e.message:'No se puede leer el fichero.');}finally{busyRef.current=false;setBusy(false);}
 }
 async function register(){if(!file||!preview||busyRef.current)return;busyRef.current=true;setBusy(true);setError('');setConflict('');try{const d=await post<SepeReceipt>({action:'register',...file,id:requestId.current,fingerprint:preview.fingerprint,communicationDate,consent,warningsAccepted});setDone(d);setPreview(null);setFile(null);setConsent(false);void load();}catch(e){setError(e instanceof Error?e.message:'No se ha podido registrar.');if(e&&typeof e==='object'&&'batchId'in e)setConflict(String(e.batchId));}finally{busyRef.current=false;setBusy(false);}}
 function search(e:FormEvent){e.preventDefault();setFilter({q:query,from,to,page:0});}
 return <div className="sepe-app">
  <a className="sepe-skip" href="#contenido">Saltar al contenido</a>
  <SedeHeader onHome={e=>navigate('services',e)}/>
  <div className="sepe-shell">
   <nav className="sepe-breadcrumb" aria-label="Ruta de navegación"><a href={companyUrl('/')}>Central de simulación</a><span aria-hidden="true">/</span><span>SEPE · Empresas</span><span aria-hidden="true">/</span>{tab==='services'?<strong aria-current="page">Contratos</strong>:<><a href={viewHref('services')} onClick={e=>navigate('services',e)}>Contratos</a><span aria-hidden="true">/</span><strong aria-current="page">{sepeViewTitles[tab]}</strong></>}</nav>
   <div className="sepe-service-heading"><h1 ref={pageHeading} tabIndex={-1}>{sepeViewTitles[tab]}</h1><p>Servicios para empresas</p></div>
   <div className="sepe-session"><span><strong>Empresa:</strong> {clientCompany().name}</span><span>Comunicación y consulta de contratos</span></div>
   <div className="sepe-workspace-frame"><nav className="sepe-application-menu" aria-label="Servicios de contratación"><span className="sepe-menu-label">CONTRATOS · EMPRESAS</span><a href={viewHref('services')} aria-current={tab==='services'?'page':undefined} onClick={e=>navigate('services',e)}>Todos los servicios</a><a href={viewHref('import')} aria-current={tab==='import'?'page':undefined} onClick={e=>navigate('import',e)}>Comunicar contratos</a><a href={viewHref('history')} aria-current={tab==='history'?'page':undefined} onClick={e=>navigate('history',e)}>Consultar comunicaciones</a><a href={viewHref('models')} aria-current={tab==='models'?'page':undefined} onClick={e=>navigate('models',e)}>Modelos oficiales</a><button type="button" onClick={()=>setHelp(true)}><HelpCircle size={18}/>Ayuda e instrucciones</button></nav>
   <div className="sepe-layout">
    <main className="sepe-content" id="contenido">
     <section aria-label="Servicios de contratos" hidden={tab!=='services'}>
      <div className="sepe-section-heading"><h2>Gestiones de contratación</h2></div>
      <div className="sepe-service-list">
       <a href={viewHref('import')} onClick={e=>navigate('import',e)}><FileText size={25} aria-hidden="true"/><div><h3>Comunicar contratos</h3><p>Envíe el fichero XML, compruebe sus datos y obtenga el justificante de la comunicación.</p><span>Acceder a Contrat@</span></div></a>
       <a href={viewHref('history')} onClick={e=>navigate('history',e)}><FolderOpen size={25} aria-hidden="true"/><div><h3>Consultar comunicaciones</h3><p>Localice los envíos de la empresa y consulte o descargue sus justificantes.</p><span>Consultar el expediente</span></div></a>
       <a href={viewHref('models')} onClick={e=>navigate('models',e)}><BookOpen size={25} aria-hidden="true"/><div><h3>Modelos oficiales de contratos</h3><p>Acceda al catálogo del SEPE para descargar y cumplimentar los impresos.</p><span>Consultar modelos</span></div></a>
      </div>
     </section>
     <section aria-label="Envío de ficheros" hidden={tab!=='import'}>
      <div className="sepe-section-heading"><h2>Comunicación a través de ficheros</h2><button className="sepe-help-button" onClick={()=>setHelp(true)} aria-label="Ayuda sobre el envío de ficheros"><HelpCircle size={20}/></button></div>
      {done?<section className="sepe-result"><h3 tabIndex={-1} ref={resultHeading}><CheckCircle2 size={23}/>Comunicación registrada</h3><p>El fichero se ha procesado correctamente.</p><dl className="sepe-result-data"><div><dt>Referencia de comunicación</dt><dd>{done.batch.reference}</dd></div><div><dt>Fichero</dt><dd>{done.batch.filename}</dd></div><div><dt>Fecha de comunicación</dt><dd>{sepeDate(done.batch.communicationDate)}</dd></div><div><dt>Contratos comunicados</dt><dd>{done.batch.count}</dd></div></dl><p>Puede obtener el justificante o consultar esta comunicación desde el menú de consultas.</p><div className="sepe-actions"><Button asChild><a href={companyUrl(pdfUrl(done.batch.id))}>Descargar justificante PDF</a></Button><Button variant="outline" asChild><a href={companyUrl(receiptUrl(done.batch.id))}><FileCheck2 size={17}/>Ver comunicación</a></Button><Button variant="outline" onClick={reset}>Nuevo envío</Button></div></section>:<>
       <ol className="sepe-steps" aria-label="Pasos del envío"><li className={!preview?'current':'complete'} aria-current={!preview?'step':undefined}><span>1</span>Selección del fichero</li><li className={preview?'current':''} aria-current={preview?'step':undefined}><span>2</span>Comprobación de datos</li><li><span>3</span>Resultado del envío</li></ol>
       {error&&<div className="sepe-error" role="alert"><strong>No se ha completado el envío</strong><p>{error}</p>{conflict&&<a href={companyUrl(receiptUrl(conflict))}>Consultar la comunicación existente </a>}</div>}
       <input ref={input} type="file" accept=".xml,text/xml,application/xml" aria-label="Fichero XML de contratos" onChange={e=>void inspect(e.target.files?.[0])} disabled={busy} hidden/>
       {!preview?<section className="sepe-upload-section">
        <p>Seleccione el fichero XML con los datos de los contratos que desea comunicar.</p>
        <fieldset className={'sepe-file-box'+(dragging?' is-dragging':'')} disabled={busy} onDragOver={e=>{e.preventDefault();if(!busy)setDragging(true);}} onDragLeave={()=>setDragging(false)} onDrop={e=>{e.preventDefault();setDragging(false);if(e.dataTransfer.files.length!==1){setError('Seleccione un único fichero XML por envío.');return;}void inspect(e.dataTransfer.files[0]);}}>
         <legend>Datos del fichero</legend><div className="sepe-file-row"><span>Fichero XML <span className="sepe-required" aria-hidden="true">*</span></span><div className="sepe-file-selector"><span role="status">{busy?'Procesando fichero…':'Ningún fichero seleccionado'}</span><Button type="button" variant="outline" onClick={()=>input.current?.click()} disabled={busy}>{busy?<Loader2 className="sepe-spin" size={16}/>:<FileText size={16}/>}Seleccionar fichero</Button></div></div>
         <p className="sepe-file-limit">Formato XML · Tamaño máximo: 1 MB · Hasta 50 contratos por fichero.</p>
        </fieldset>
        <div className="sepe-information"><Info size={19}/><p>Tras seleccionar el fichero, compruebe los datos y confirme el envío. Al finalizar podrá obtener el justificante de la comunicación.</p></div>
        <p className="sepe-upload-help">¿Necesita ayuda para preparar el envío? <button onClick={()=>setHelp(true)}>Consultar instrucciones</button></p>
       </section>:<section className="sepe-review">
        <div className="sepe-review-heading"><div><h3 tabIndex={-1} ref={reviewHeading}>Comprobación de datos</h3><p><strong>Fichero:</strong> {file?.filename}</p><p><strong>Contratos incluidos:</strong> {preview.contracts.length}</p></div><Button variant="outline" disabled={busy} onClick={()=>input.current?.click()}>Seleccionar otro fichero</Button></div>
        <p className="sepe-review-instruction">Compruebe la información antes de confirmar el envío. Si detecta un error, corrija los datos en su programa de nóminas y genere un nuevo fichero.</p>
        {preview.duplicates.length>0&&<div className="sepe-error" role="alert"><strong>Contratos ya comunicados</strong><p>El fichero contiene contratos registrados anteriormente. Retírelos del fichero para poder continuar.</p><ul>{preview.duplicates.map((d,i)=><li key={d.batchId+i}>{d.name} · <a href={companyUrl(receiptUrl(d.batchId))}>{d.reference}</a></li>)}</ul></div>}
        {preview.contracts.map(c=><ContractCard key={c.line} contract={c}/>)}
        {preview.warnings.length>0&&<div className="sepe-warnings"><strong>Observaciones</strong><ul>{preview.warnings.map(w=><li key={w}>{w}</li>)}</ul><label className="sepe-check"><Checkbox checked={warningsAccepted} onCheckedChange={v=>setWarningsAccepted(v===true)} disabled={busy}/>He revisado las observaciones y confirmo los datos del fichero.</label></div>}
        <fieldset className="sepe-confirm" disabled={busy}><legend>Confirmación del envío</legend><label className="sepe-date-field"><span>Fecha de comunicación</span><Input type="date" min="1900-01-01" max="2199-12-31" value={communicationDate} onChange={e=>{setCommunicationDate(e.target.value);setConsent(false);}} disabled={busy}/></label><label className="sepe-check"><Checkbox checked={consent} onCheckedChange={v=>setConsent(v===true)} disabled={busy}/>He comprobado los datos de los contratos y confirmo esta comunicación.</label><div className="sepe-actions"><Button disabled={busy||!consent||!communicationDate||preview.duplicates.length>0||(preview.warnings.length>0&&!warningsAccepted)} onClick={()=>void register()}>{busy?<Loader2 className="sepe-spin" size={17}/>:null}{busy?'Enviando…':'Confirmar envío'}</Button><Button variant="outline" disabled={busy} onClick={reset}>Cancelar</Button></div></fieldset>
       </section>}
      </>}
     </section>
     <section aria-label="Consulta de comunicaciones" hidden={tab!=='history'}>
      <div className="sepe-section-heading"><h2>Seguimiento de las comunicaciones realizadas</h2><Button variant="outline" disabled={historyBusy} onClick={()=>void load()}>Actualizar</Button></div>
      <div className="practice-actions"><DeleteRecord scope="sepe" title="Todas las comunicaciones del SEPE" label="Borrar comunicaciones" onDeleted={()=>{reset();setFilter(f=>({...f,page:0}));void load();}}/><a href={companyUrl("/practicas")}>Gestión de prácticas</a></div><form className="sepe-filters" onSubmit={search}><fieldset><legend>Criterios de búsqueda</legend><label className="sepe-search-field"><span>Nombre, identificación, modalidad o referencia</span><div><Search size={17}/><Input aria-label="Buscar comunicaciones" value={query} onChange={e=>setQuery(e.target.value)} maxLength={120} placeholder="Introduzca un criterio de búsqueda"/></div></label><div className="sepe-filter-dates"><label><span>Fecha de comunicación desde</span><Input type="date" value={from} max={to||undefined} onChange={e=>setFrom(e.target.value)}/></label><label><span>Fecha de comunicación hasta</span><Input type="date" value={to} min={from||undefined} onChange={e=>setTo(e.target.value)}/></label><div className="sepe-filter-actions"><Button type="submit" disabled={historyBusy}>Buscar</Button><Button type="button" variant="outline" disabled={historyBusy} onClick={()=>{setQuery('');setFrom('');setTo('');setFilter({q:'',from:'',to:'',page:0});}}>Limpiar filtros</Button></div></div></fieldset></form>
      {historyError&&<p className="sepe-error" role="alert">{historyError}</p>}
      {historyBusy?<p className="sepe-loading" role="status">Consultando comunicaciones…</p>:history&&!historyError&&<><p className="sepe-result-count" role="status">Resultado de la consulta: <strong>{history.total} {history.total===1?'comunicación':'comunicaciones'}</strong> · {history.contractCount} {history.contractCount===1?'contrato':'contratos'}</p>{history.batches.length?<><div className="sepe-table-wrap" role="region" aria-label="Comunicaciones registradas" tabIndex={0}><table className="sepe-table"><caption className="sr-only">Comunicaciones de contratos de la empresa</caption><thead><tr><th scope="col">Referencia / estado</th><th scope="col">Trabajadores / fichero</th><th scope="col">Fecha de comunicación</th><th scope="col">Contratos</th><th scope="col">Documentos</th></tr></thead><tbody>{history.batches.map(b=><tr key={b.id}><td><strong>{b.reference}</strong><span className="sepe-status">Registrada</span></td><td><p className="sepe-names" title={b.names}>{b.names}</p><small>{b.filename}</small></td><td>{sepeDate(b.communicationDate)}</td><td>{b.count}</td><td><a className="sepe-receipt-link" href={companyUrl(receiptUrl(b.id))}>Ver justificante</a><a className="sepe-pdf-link" href={companyUrl(pdfUrl(b.id))}>Descargar PDF</a><DeleteRecord scope="sepe" id={b.id} title={b.reference} onDeleted={()=>{reset();setFilter(f=>({...f,page:0}));void load();}}/>{b.hasXml&&<a className="sepe-xml-link" href={companyUrl('/api/sepe?'+new URLSearchParams({batch:b.id,xml:'1'}))}>Fichero XML</a>}</td></tr>)}</tbody></table></div><div className="sepe-pagination"><span>Página {history.page+1} de {Math.ceil(history.total/history.pageSize)}</span><div><Button variant="outline" size="sm" disabled={history.page===0} onClick={()=>setFilter(f=>({...f,page:f.page-1}))}>Anterior</Button><Button variant="outline" size="sm" disabled={(history.page+1)*history.pageSize>=history.total} onClick={()=>setFilter(f=>({...f,page:f.page+1}))}>Siguiente</Button></div></div></>:<div className="sepe-empty"><p>{filter.q||filter.from||filter.to?'No se han encontrado comunicaciones con los criterios seleccionados.':'No constan comunicaciones registradas.'}</p>{!(filter.q||filter.from||filter.to)&&<Button variant="outline" onClick={()=>navigate('import')}>Envío de ficheros</Button>}</div>}</>}
     </section>
     <section aria-label="Modelos de contratos" hidden={tab!=='models'}><ContractModels/></section>
    </main>
   </div></div>
  </div>
  <footer className="sepe-footer"><span>SEPE · Contrat@</span><button onClick={()=>setHelp(true)}>Ayuda y alcance de la simulación</button><span>{clientCompany().name} · Aula de simulación</span></footer>
  <Dialog open={help} onOpenChange={setHelp}><DialogContent className="sepe-help-dialog"><DialogTitle>Ayuda de Contrat@</DialogTitle><DialogDescription>Envío y consulta de comunicaciones de contratos.</DialogDescription><div className="sepe-help-content"><h3>Envío de ficheros</h3><p>La práctica es de acceso libre. No necesita solicitar una autorización real de Contrat@ ni identificarse en el SEPE.</p><ol><li>Exporte el XML de comunicación inicial de contratos desde NominaSol.</li><li>Seleccione el fichero y revise los datos de empresa, trabajadores y contratos.</li><li>Confirme el envío y conserve el justificante. Si hay errores, corrija el fichero en el programa de origen.</li></ol><h3>Consulta de comunicaciones</h3><p>Permite buscar registros y descargar justificantes. Conserve el PDF que corresponda a su práctica. El expediente de {clientCompany().shortName} se guarda solo en esta práctica de este navegador.</p><h3>Modelos de contratos</h3><p>Acceda al catálogo oficial del SEPE, descargue los impresos y cumpliméntelos con los datos de la práctica. El enlace se abre en otra pestaña, previo aviso.</p><h3>Alcance de la simulación</h3><p>Utilice exclusivamente datos ficticios. No se realiza ninguna presentación ante el SEPE ni se acredita la validación administrativa de los contratos. Revise que el NIF y la cuenta de cotización del fichero coincidan con los datos de su empresa.</p><p>Están disponibles las comunicaciones iniciales de contratos. Las prórrogas y otras variaciones no se tramitan en este servicio.</p></div><Button variant="outline" onClick={()=>setHelp(false)}>Cerrar</Button></DialogContent></Dialog>
 </div>;
}
