import {cents} from '../lib/bank-xml.ts';
export function bankXml({id='REMESA-1',type='payment',amounts=['10.10','20.20'],version,owner='Empresa de prácticas, S.L.'}={}){
 const dd=type==='collection',ver=version||(dd?'pain.008.001.02':'pain.001.001.03'),body=dd?'CstmrDrctDbtInitn':'CstmrCdtTrfInitn';
 const total=(amounts.reduce((n,x)=>n+cents(x),0)/100).toFixed(2),date=dd?'<ReqdColltnDt>2026-09-19</ReqdColltnDt>':ver.endsWith('.09')?'<ReqdExctnDt><Dt>2026-09-19</Dt></ReqdExctnDt>':'<ReqdExctnDt>2026-09-19</ReqdExctnDt>';
 const source=dd?'Cdtr':'Dbtr',other=dd?'Dbtr':'Cdtr';
 const rows=amounts.map((a,i)=>`<${dd?'DrctDbtTxInf':'CdtTrfTxInf'}><PmtId><EndToEndId>${id}-${i+1}</EndToEndId></PmtId>${dd?`<InstdAmt Ccy="EUR">${a}</InstdAmt><DrctDbtTx><MndtRltdInf><MndtId>MANDATO-${i+1}</MndtId><DtOfSgntr>2026-01-01</DtOfSgntr></MndtRltdInf></DrctDbtTx>`:`<Amt><InstdAmt Ccy="EUR">${a}</InstdAmt></Amt>`}<${other}><Nm>Empresa ficticia ${i+1}</Nm></${other}><${other}Acct><Id><IBAN>ES0000000000000000000000</IBAN></Id></${other}Acct><RmtInf><Ustrd>Factura de prácticas ${i+1}</Ustrd></RmtInf></${dd?'DrctDbtTxInf':'CdtTrfTxInf'}>`).join('');
 return `<?xml version="1.0" encoding="UTF-8"?><Document xmlns="urn:iso:std:iso:20022:tech:xsd:${ver}"><${body}><GrpHdr><MsgId>${id}</MsgId><NbOfTxs>${amounts.length}</NbOfTxs><CtrlSum>${total}</CtrlSum><InitgPty><Nm>${owner}</Nm></InitgPty></GrpHdr><PmtInf><PmtInfId>BLOQUE-1</PmtInfId><PmtMtd>${dd?'DD':'TRF'}</PmtMtd><NbOfTxs>${amounts.length}</NbOfTxs><CtrlSum>${total}</CtrlSum><PmtTpInf><SvcLvl><Cd>SEPA</Cd></SvcLvl>${type==='payroll'?'<CtgyPurp><Cd>SALA</Cd></CtgyPurp>':''}</PmtTpInf>${date}<${source}><Nm>${owner}</Nm></${source}><${source}Acct><Id><IBAN>ES0000000000000000000000</IBAN></Id></${source}Acct>${rows}</PmtInf></${body}></Document>`;
}
function contract({person='D00000000T',name='MARTA',code='100',start='20260901',ccc='011128123456740',extra=''}={}){return `<CONTRATO_${code}><DATOS_EMPRESA><CIF_NIF_EMPRESA><CIF_NIF>B12345674</CIF_NIF></CIF_NIF_EMPRESA><CODIGO_CUENTA_COTIZACION>${ccc}</CODIGO_CUENTA_COTIZACION></DATOS_EMPRESA><DATOS_TRABAJADOR><IDENTIFICADORPFISICA>${person}</IDENTIFICADORPFISICA><NOMBRE_APELLIDOS><NOMBRE>${name}</NOMBRE><PRIMER_APELLIDO>MUÑOZ</PRIMER_APELLIDO><SEGUNDO_APELLIDO>PRUEBA</SEGUNDO_APELLIDO></NOMBRE_APELLIDOS><SEXO>2</SEXO><FECHA_NACIMIENTO>19950520</FECHA_NACIMIENTO><NACIONALIDAD>724</NACIONALIDAD></DATOS_TRABAJADOR><DATOS_GENERALES_CONTRATO><FECHA_INICIO>${start}</FECHA_INICIO><NIVEL_FORMATIVO>59</NIVEL_FORMATIVO><CODIGO_OCUPACION>0000</CODIGO_OCUPACION></DATOS_GENERALES_CONTRATO>${extra}</CONTRATO_${code}>`;}
export const contractXml=(rows=[{}],encoding='UTF-8')=>`<?xml version="1.0" encoding="${encoding}"?><CONTRATOS>${rows.map(contract).join('')}</CONTRATOS>`;
