import {practiceStorage} from '@/lib/local/storage';
'use client';
import {clientCompany,companyFetch,companyStorageKey,shouldRefresh,companyUrl} from '@/lib/company-client';

import {useCallback,useEffect,useRef,useState} from 'react';
import {DeleteRecord} from '@/components/practice/delete-record';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Textarea} from '@/components/ui/textarea';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogFooter,AlertDialogAction,AlertDialogCancel} from '@/components/ui/alert-dialog';
import {Sidebar,SidebarProvider,SidebarContent,SidebarMenu,SidebarMenuItem,SidebarMenuButton} from '@/components/ui/sidebar';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Inbox,Send,FilePenLine,Archive,Trash2,Search,PenLine,Mail,MailOpen,Globe,Plus,Users,Paperclip} from 'lucide-react';
import {newMailId,MAILBOX,FOLDERS,folderNames,scenarios,type Folder,type MailMessage,type MailSummary,type MailList,type MailEditor} from '@/lib/mail-types';
import {AttachmentPicker,MessageAttachments} from './attachments';
import {CorporateSignature} from './corporate-signature';
import {DownloadMessage} from './download-message';
import {messageForm,type MailAttachment,type PendingAttachment} from '@/lib/mail-files';
const signaturePreference='mail-signature-name';
const personalName=(name:string)=>name===`${clientCompany().name}`?'':name;
const icons={inbox:Inbox,sent:Send,drafts:FilePenLine,archive:Archive,trash:Trash2};
const empty:MailList={messages:[],total:0,counts:{inbox:0,sent:0,drafts:0,archive:0,trash:0},unread:0,page:0,pageSize:40};
async function api(data:Record<string,unknown>,files:PendingAttachment[]=[]){const response=await companyFetch('/api/correo',{method:'POST',...(files.length?{body:messageForm(data,files)}:{headers:{'Content-Type':'application/json'},body:JSON.stringify(data)})});const result=await response.json() as {message:MailMessage;error?:string};if(!response.ok)throw Error(result.error||'No se ha podido guardar el mensaje.');return result;}
const date=(s:string)=>new Date(s).toLocaleString('es-ES',{day:'2-digit',month:'short',hour:'2-digit',minute:'2-digit',timeZone:'Europe/Madrid'});
export default function MailWorkspace(){
 const practiceScenarios=scenarios;
 const [folder,setFolder]=useState<Folder>('inbox'),[data,setData]=useState<MailList>(empty),[page,setPage]=useState(0),[query,setQuery]=useState(''),[search,setSearch]=useState('');
 const [selected,setSelected]=useState<MailMessage|null>(null),[editor,setEditor]=useState<MailEditor|null>(null),[incoming,setIncoming]=useState(false),[dirty,setDirty]=useState(false),[discard,setDiscard]=useState(false);
 const [loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[error,setError]=useState(''),[editorError,setEditorError]=useState(''),[notice,setNotice]=useState('');
 const [files,setFiles]=useState<PendingAttachment[]>([]),[savedFiles,setSavedFiles]=useState<MailAttachment[]>([]);
 const [signatureName,setSignatureName]=useState('');
 useEffect(()=>{try{setSignatureName((practiceStorage.getItem(companyStorageKey(signaturePreference))||'').slice(0,100));}catch{/* The signature can still be edited without browser storage. */}},[]);
 const requestNumber=useRef(0),selectedId=useRef<string|null>(null);
 const refresh=useCallback(async()=>{const n=++requestNumber.current;setLoading(true);try{const r=await companyFetch('/api/correo?'+new URLSearchParams({folder,page:String(page),q:search}),{cache:'no-store'});const d=await r.json() as MailList&{error?:string};if(!r.ok)throw Error(d.error);if(n===requestNumber.current){setData(d);setError('');}}catch(e){if(n===requestNumber.current)setError(e instanceof Error?e.message:'No se ha podido abrir el correo.');}finally{if(n===requestNumber.current)setLoading(false);}},[folder,page,search]);
 useEffect(()=>{const t=setTimeout(()=>{setSearch(query);setPage(0);},250);return()=>clearTimeout(t);},[query]);
 useEffect(()=>{shouldRefresh();void refresh();const update=()=>{if(shouldRefresh())void refresh();};const t=setInterval(update,120000);window.addEventListener('focus',update);document.addEventListener('visibilitychange',update);return()=>{clearInterval(t);window.removeEventListener('focus',update);document.removeEventListener('visibilitychange',update);requestNumber.current++;};},[refresh]);
 useEffect(()=>{if(!editor||!dirty)return;const warn=(e:BeforeUnloadEvent)=>{e.preventDefault();e.returnValue='';};window.addEventListener('beforeunload',warn);return()=>window.removeEventListener('beforeunload',warn);},[editor,dirty]);
 function openFolder(f:Folder){if(f!==folder){setData(old=>({...old,messages:[],total:0}));setLoading(true);}setFolder(f);setPage(0);setSelected(null);selectedId.current=null;setNotice('');}
 function newEditor(inbound=false,m?:MailMessage){setFiles([]);setSavedFiles(m?.attachments||[]);setIncoming(inbound);setEditorError('');setDirty(false);setEditor(m?{id:m.id,revision:m.revision,senderName:personalName(m.senderName),senderAddress:m.senderAddress,recipient:m.recipient,subject:m.subject,body:m.body,replyTo:m.replyTo}:{id:newMailId(),senderName:inbound?practiceScenarios[0].senderName:signatureName,senderAddress:inbound?practiceScenarios[0].senderAddress:clientCompany().mailbox,recipient:inbound?clientCompany().mailbox:'',subject:inbound?practiceScenarios[0].subject:'',body:inbound?practiceScenarios[0].body:''});}
 function changeSignature(value:string){edit('senderName',value);setSignatureName(value);try{practiceStorage.setItem(companyStorageKey(signaturePreference),value);}catch{/* Keep the editable signature in this window. */}}
 function edit(key:keyof MailEditor,value:string){setEditor(old=>old?{...old,[key]:value}:old);setDirty(true);setEditorError('');}
 async function openMessage(summary:MailSummary){selectedId.current=summary.id;setSelected(null);setBusy(true);setError('');try{const response=await companyFetch('/api/correo?id='+summary.id),result=await response.json() as {message:MailMessage;error?:string};if(!response.ok)throw Error(result.error||'No se puede abrir el mensaje.');if(selectedId.current!==summary.id)return;const m=result.message;if(m.folder==='drafts'){newEditor(false,m);return;}setSelected(m);if(!m.isRead){const marked=await api({action:'read',id:m.id,isRead:true});if(selectedId.current===m.id)setSelected(marked.message);void refresh();}}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function move(dest:'archive'|'trash'|'restore'){if(!selected)return;setBusy(true);try{await api({action:'move',id:selected.id,revision:selected.revision,folder:dest});setSelected(null);selectedId.current=null;setNotice(dest==='trash'?'Mensaje movido a la papelera. Puedes restaurarlo.':dest==='archive'?'Mensaje archivado.':'Mensaje restaurado.');await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function markUnread(){if(!selected)return;setBusy(true);try{await api({action:'read',id:selected.id,isRead:false});setSelected(null);selectedId.current=null;setNotice('Mensaje marcado como no leído.');await refresh();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 function reply(){if(!selected)return;newEditor();setEditor({id:newMailId(),senderName:signatureName,senderAddress:clientCompany().mailbox,recipient:selected.senderAddress===clientCompany().mailbox?selected.recipient:selected.senderAddress,subject:/^Re:/i.test(selected.subject)?selected.subject:'Re: '+selected.subject,body:'\n\n--- Mensaje anterior ---\n'+selected.senderName+' · '+date(selected.createdAt)+'\n'+selected.body.slice(0,3000),replyTo:selected.id});}
 async function save(action:'draft'|'send'|'receive'){if(!editor)return;setBusy(true);setEditorError('');try{await api({...editor,action,attachmentIds:savedFiles.map(f=>f.id)},files);setEditor(null);setDirty(false);setNotice(action==='draft'?'Borrador guardado en el buzón de prácticas.':action==='send'?'Mensaje guardado en Enviados. Envío simulado, sin entrega a correo real.':'Mensaje recibido en la bandeja de entrada.');setFolder(action==='draft'?'drafts':action==='send'?'sent':'inbox');setPage(0);setSelected(null);selectedId.current=null;await refresh();}catch(e){setEditorError((e as Error).message);}finally{setBusy(false);}}
 const closeEditor=()=>{if(busy)return;if(dirty)setDiscard(true);else setEditor(null);};
 return <div className="mail-app">
  <a className="portal-skip" href={companyUrl("#bandeja")}>Saltar al correo</a>
  <header className="mail-header"><a href={companyUrl("/")} className="mail-home" aria-label="Volver a la central"><img src={clientCompany().logo} width="146" height="41" alt={`${clientCompany().name}`}/></a><span className="mail-divider"/><h1>Correo</h1><span className="mail-account"><Users size={16}/> Correo de prácticas</span><Button asChild variant="ghost"><a href={companyUrl("/")}>Central de servicios</a></Button></header>
  <div className="mail-notice"><span>Simulación educativa</span><p>Mensajes de prácticas en este navegador. Sin envío a cuentas reales.</p></div>
  <SidebarProvider className="mail-layout">
   <Sidebar collapsible="none" className="mail-sidebar"><SidebarContent><div className="mail-profile"><span className="mail-avatar">{clientCompany().shortName[0]}</span><div><strong>{clientCompany().name}</strong><small>{clientCompany().mailbox}</small></div></div><Button className="mail-compose" onClick={()=>newEditor()}><PenLine size={18}/>Redactar</Button><SidebarMenu>{FOLDERS.map(f=>{const Icon=icons[f];return <SidebarMenuItem key={f}><SidebarMenuButton isActive={folder===f} onClick={()=>openFolder(f)} className="mail-folder"><Icon/><span>{folderNames[f]}</span><span className="mail-count">{f==='inbox'?data.unread:data.counts[f]}</span></SidebarMenuButton></SidebarMenuItem>;})}</SidebarMenu><div className="mail-side-actions"><Button variant="outline" onClick={()=>newEditor(true)}><Plus size={17}/>Simular recepción</Button></div><p className="mail-side-note">Sin envío a cuentas reales.</p></SidebarContent></Sidebar>
   <main id="bandeja" className={'mail-main'+(selected?' has-selection':'')}>
    <div className="mail-toolbar"><div><h2>{folderNames[folder]}</h2><span>{data.total} {data.total===1?'mensaje':'mensajes'}</span></div><label className="mail-search"><Search size={18}/><Input value={query} onChange={e=>setQuery(e.target.value)} aria-label="Buscar en esta carpeta" placeholder="Buscar en esta carpeta"/></label><Button variant="ghost" onClick={()=>void refresh()} disabled={loading} aria-label="Actualizar bandeja">Actualizar</Button></div>
    {error&&<div className="mail-error" role="alert">{error} <Button variant="link" onClick={()=>void refresh()}>Reintentar</Button></div>}
    {notice&&<p className="mail-feedback" role="status">{notice}</p>}
    <div className="mail-panes"><section className="mail-list" aria-label="Lista de mensajes" aria-busy={loading}>
     {!data.messages.length?<div className="mail-empty-list"><Inbox size={34}/><h3>{loading?'Abriendo el correo…':search?'No hay coincidencias':'No hay mensajes'}</h3><p>{loading?'':search?'Prueba con otro asunto o remitente.':folder==='inbox'?'Puedes recibir una consulta desde el formulario web o simular un mensaje.':'Los mensajes de esta carpeta aparecerán aquí.'}</p>{!loading&&!search&&folder==='inbox'&&<Button variant="outline" onClick={()=>newEditor(true)}>Recibir un mensaje de prácticas</Button>}</div>:data.messages.map(m=><button key={m.id} className={'mail-row'+(!m.isRead?' unread':'')+(selected?.id===m.id?' selected':'')} onClick={()=>void openMessage(m)} aria-label={(m.isRead?'':'No leído. ')+(m.folder==='drafts'?'Borrador. ':'')+(m.subject||'Sin asunto')}><div className="mail-row-top"><strong>{m.homeFolder==='inbox'?m.senderName:'Para: '+(m.recipient||'Sin destinatario')}</strong><time dateTime={m.createdAt}>{date(m.createdAt)}</time></div><h3>{m.subject||'Sin asunto'}</h3>{m.homeFolder!=='inbox'&&<span className="mail-row-author">De: {m.senderName}</span>}<p>{m.preview||'Mensaje sin texto'}</p>{m.attachments.length>0&&<span className="mail-file-count"><Paperclip size={13}/>{m.attachments.length} {m.attachments.length===1?'adjunto':'adjuntos'}</span>}{m.source==='web'&&<span className="mail-web-label">Formulario web</span>}</button>)}
     {data.total>data.pageSize&&<nav className="mail-pagination" aria-label="Páginas de mensajes"><Button variant="ghost" disabled={page===0} onClick={()=>setPage(p=>p-1)} aria-label="Página anterior">Anterior</Button><span>Página {page+1} de {Math.ceil(data.total/data.pageSize)}</span><Button variant="ghost" disabled={(page+1)*data.pageSize>=data.total} onClick={()=>setPage(p=>p+1)} aria-label="Página siguiente">Siguiente</Button></nav>}
    </section><section className="mail-reading" aria-label="Lectura del mensaje">{selected?<><div className="mail-message-actions"><Button variant="ghost" onClick={()=>{setSelected(null);selectedId.current=null;}} className="mail-back">Volver</Button>{selected.folder!=='trash'&&<Button variant="outline" onClick={reply} disabled={busy}>Responder</Button>}<DownloadMessage id={selected.id} onError={setError}/><Button variant="outline" onClick={()=>void markUnread()} disabled={busy}><Mail size={17}/>Marcar como no leído</Button>{selected.folder!=='archive'&&selected.folder!=='trash'&&<Button variant="ghost" onClick={()=>void move('archive')} disabled={busy} aria-label="Archivar mensaje"><Archive size={18}/></Button>}{['archive','trash'].includes(selected.folder)&&<Button variant="outline" onClick={()=>void move('restore')} disabled={busy}>Restaurar</Button>}{selected.folder!=='trash'&&<Button variant="ghost" onClick={()=>void move('trash')} disabled={busy} aria-label="Mover a la papelera"><Trash2 size={18}/></Button>}{selected.folder==='trash'&&<DeleteRecord scope="mail" id={selected.id} title={selected.subject||'Mensaje sin asunto'} label="Eliminar definitivamente" onDeleted={async()=>{setSelected(null);selectedId.current=null;setNotice('Mensaje eliminado.');await refresh();}}/>}</div><article className="mail-message"><span className="mail-message-source">{selected.source==='web'?'CONTACTO WEB':selected.homeFolder==='sent'?'MENSAJE ENVIADO · SIMULADO':'MENSAJE RECIBIDO'}</span><h2>{selected.subject||'Sin asunto'}</h2><div className="mail-sender"><span className="mail-sender-avatar">{selected.senderName.charAt(0)}</span><div><strong>{selected.senderName}</strong><span>{selected.senderAddress}</span><small>Para: {selected.recipient}</small></div><time dateTime={selected.createdAt}>{date(selected.createdAt)}</time></div><div className="mail-body">{selected.body}</div>{selected.source==='mail'&&<CorporateSignature name={selected.senderName}/>}<MessageAttachments messageId={selected.id} files={selected.attachments}/>{selected.homeFolder==='sent'&&<p className="mail-delivery">Envío de prácticas registrado. No se ha enviado a una cuenta de correo real.</p>}</article></>:<div className="mail-reading-empty"><div className="mail-envelope"><MailOpen size={42} strokeWidth={1.3}/></div><h2>Tu espacio de comunicación.</h2><p>Selecciona un mensaje para leerlo<br/>o redacta una nueva comunicación.</p><span>{clientCompany().name}</span></div>}</section></div>
   </main>
  </SidebarProvider>
  <footer className="mail-footer"><span>{clientCompany().name} · Aula de simulación</span><span>Correo de prácticas · Guardado en este navegador.</span></footer>
  <Dialog open={!!editor} onOpenChange={open=>{if(!open)closeEditor();}}><DialogContent className="mail-editor" onInteractOutside={e=>e.preventDefault()}><DialogTitle>{incoming?'Recibir mensaje de prácticas':'Nuevo mensaje'}</DialogTitle><DialogDescription>{incoming?'Crea una consulta de cliente o una comunicación de proveedor.':'El mensaje se guardará en Enviados. No se enviará a ninguna cuenta real.'}</DialogDescription>{editor&&<form onSubmit={e=>{e.preventDefault();void save(incoming?'receive':'send');}}><fieldset disabled={busy}>
   {incoming&&<><label className="mail-field"><span>Situación</span><Select onValueChange={v=>{const s=practiceScenarios[Number(v)];setEditor(old=>old?{...old,senderName:s.senderName,senderAddress:s.senderAddress,subject:s.subject,body:s.body}:old);setDirty(true);}}><SelectTrigger aria-label="Situación de prácticas"><SelectValue placeholder="Solicitud de presupuesto"/></SelectTrigger><SelectContent>{practiceScenarios.map((s,i)=><SelectItem key={s.name} value={String(i)}>{s.name}</SelectItem>)}</SelectContent></Select></label><label className="mail-field"><span>Empresa remitente</span><Input value={editor.senderName} maxLength={100} required onChange={e=>edit('senderName',e.target.value)}/></label></>}
   <label className="mail-field"><span>{incoming?'Correo del remitente':'Para'}</span><Input type="email" value={incoming?editor.senderAddress:editor.recipient} required maxLength={120} placeholder="nombre@empresa.com" onChange={e=>edit(incoming?'senderAddress':'recipient',e.target.value)}/></label>
   <label className="mail-field"><span>Asunto</span><Input value={editor.subject} required maxLength={160} onChange={e=>edit('subject',e.target.value)}/></label>
   <label className="mail-field"><span>Mensaje</span><Textarea value={editor.body} required maxLength={12000} rows={11} onChange={e=>edit('body',e.target.value)}/></label>
   {!incoming&&<section className="mail-signature-editor" aria-label="Firma del mensaje"><label className="mail-field"><span>Nombre y apellidos para la firma</span><Input value={editor.senderName} maxLength={100} placeholder="Nombre Apellidos" onChange={e=>changeSignature(e.target.value)}/></label><CorporateSignature name={editor.senderName}/></section>}
   <AttachmentPicker saved={savedFiles} files={files} disabled={busy} onChange={next=>{setFiles(next);setDirty(true);}} onRemove={id=>{setSavedFiles(old=>old.filter(f=>f.id!==id));setDirty(true);}}/>
   <p className="mail-editor-note">Envío simulado · Correo de prácticas</p>
   {editorError&&<p className="mail-error" role="alert">{editorError}</p>}
   <div className="mail-editor-actions"><Button type="button" variant="ghost" onClick={closeEditor} disabled={busy}>Cerrar</Button>{!incoming&&<Button type="button" variant="outline" onClick={()=>void save('draft')} disabled={busy}><FilePenLine size={16}/>Guardar borrador</Button>}<Button type="submit" disabled={busy}>{busy?'Guardando…':incoming?'Recibir en la bandeja':'Enviar'}</Button></div>
  </fieldset></form>}</DialogContent></Dialog>
  <AlertDialog open={discard} onOpenChange={setDiscard}><AlertDialogContent><AlertDialogTitle>¿Cerrar sin guardar los cambios?</AlertDialogTitle><AlertDialogDescription>Se perderán los cambios de esta ventana. Si existía un borrador guardado, se conservará su versión anterior.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Seguir escribiendo</AlertDialogCancel><AlertDialogAction onClick={()=>{setEditor(null);setDirty(false);}}>Descartar cambios</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
 </div>;
}
