import {companyId,companyProfile} from './company-server';
import {bankDb as db,bankJson as json,bankUuid as uuid,bankText as text,bankSha as sha,bankAccount as account,bankBatch as batch,bankDetails as details,bankBoundary as boundary,bankPayload as payload,bankBatchInsert as batchInsert} from './bank-server';
import {BankError,cents,validDate,normalizeIban,validIban} from './bank-xml';
import {financePlan,type FinanceData,type FinanceProduct,type Mandate} from './bank-finance';
import {kindNames,type BankKind,type BankItem,type BankBatch} from './bank-types';
const mandateCols='id,name,iban,reference,signed_date AS signedDate,direction,status,revision';
async function mandate(id:string){return db().prepare(`SELECT ${mandateCols} FROM bank_mandates WHERE company_id=? AND id=?`).bind(companyId(),id).first<Mandate>();}
async function product(id:string):Promise<FinanceProduct|null>{const row=await db().prepare('SELECT id,kind,title,data,created_at AS createdAt FROM bank_products WHERE company_id=? AND id=?').bind(companyId(),id).first<any>();if(!row)return null;const payments=await db().prepare('SELECT installment,batch_id AS batchId FROM bank_product_payments WHERE product_id=? ORDER BY installment').bind(id).all<{installment:number;batchId:string}>();return {...row,data:JSON.parse(row.data),payments:payments.results};}
const inputIban=(v:unknown)=>{const s=normalizeIban(text(v,'el IBAN',40));if(!/^[A-Z]{2}\d{2}[A-Z0-9]{11,30}$/.test(s)||(s.startsWith('ES')&&s.length!==24))throw new BankError('El IBAN debe tener formato válido; para España, 24 caracteres.');return s;};
export function readBankOperations(req:Request){return boundary(async()=>{const u=new URL(req.url),id=u.searchParams.get('product');if(id){const r=await product(uuid(id));if(!r)throw new BankError('No se encuentra la financiación.',404);return json({product:r});}const ids=await db().prepare('SELECT id FROM bank_products WHERE company_id=? ORDER BY created_at DESC LIMIT 200').bind(companyId()).all<{id:string}>();const mandates=await db().prepare(`SELECT ${mandateCols} FROM bank_mandates WHERE company_id=? ORDER BY name LIMIT 500`).bind(companyId()).all<Mandate>();return json({products:await Promise.all(ids.results.map(r=>product(r.id))),mandates:mandates.results});});}
export function writeBankOperations(req:Request){return boundary(async()=>{
 const p=await payload(req),action=String(p.action),a=await account();if(!a)throw new BankError(`Abre primero la cuenta de ${companyProfile().shortName}.`,409);
 if(!['manual-preview','manual-execute','finance-preview','finance-execute','installment-preview','installment-execute','mandate-create','mandate-status'].includes(action))throw new BankError('Operación no válida.');
 const preview=action.endsWith('preview');if(!preview&&p.consent!==true)throw new BankError('Confirma la operación.');
 if(action.startsWith('mandate-')){
  const id=uuid(p.id);if(action==='mandate-status'){const m=await mandate(id);if(!m||!['active','inactive'].includes(String(p.status)))throw new BankError('Domiciliación no válida.');const updated=await db().prepare('UPDATE bank_mandates SET status=?,revision=revision+1 WHERE company_id=? AND id=? AND revision=?').bind(p.status,companyId(),id,p.revision).run();if(!updated.meta.changes)throw new BankError('La domiciliación ha cambiado. Actualiza la consulta.',409);return json({mandate:await mandate(id)});}
  const name=text(p.name,'el titular',120),iban=inputIban(p.iban),reference=text(p.reference,'la referencia del mandato',80),signedDate=validDate(p.signedDate),direction=p.direction;if(direction!=='in'&&direction!=='out')throw new BankError('Elige cobro o pago.');const m=await mandate(id);if(m){if(m.name===name&&m.iban===iban&&m.reference===reference&&m.signedDate===signedDate&&m.direction===direction)return json({mandate:m});throw new BankError('La referencia de solicitud ya existe.',409);}
  if(!validIban(iban)&&p.warningsAccepted!==true)throw new BankError('Revisa el IBAN: no supera el control de dígitos. Confirma su uso para la práctica.');
  try{const r=await db().prepare("INSERT INTO bank_mandates(id,company_id,name,iban,reference,signed_date,direction,status,revision,created_at) SELECT ?,?,?,?,?,?,?,'active',1,? WHERE (SELECT COUNT(*) FROM bank_mandates WHERE company_id=?)<500 AND EXISTS(SELECT 1 FROM bank_accounts WHERE id=?)").bind(id,companyId(),name,iban,reference,signedDate,direction,new Date().toISOString(),companyId(),companyId()).run();if(!r.meta.changes)throw new BankError('No se ha guardado: actualiza la cuenta o revisa el límite de 500 domiciliaciones.',409);}catch(e){if(String(e).includes('UNIQUE'))throw new BankError('Ya existe esta referencia de mandato.',409);throw e;}return json({mandate:await mandate(id)},201);
 }
 const id=uuid(p.id),input={...p};delete input.action;delete input.consent;delete input.fingerprint;delete input.revision;delete input.warningsAccepted;
 const fingerprint=await sha(JSON.stringify(input)),existing=await batch(id);if(existing){if(existing.fingerprint!==fingerprint)throw new BankError('Inicia una operación nueva: esta referencia ya se ha utilizado.',409);return json({...await details(id),product:await product(id)});}
 const date=validDate(p.bookingDate);let kind:BankKind,amount=0,delta=0,name='',iban='',concept='',reference=text(p.reference??'','la referencia',100,true),mandateId='',mandateDate='',finance:FinanceData|null=null,linkedProduct:FinanceProduct|null=null,installment=0;
 const warnings:string[]=[];let selectedMandate:Mandate|null=null;
 if(action.startsWith('finance-')){finance=financePlan(p);kind=finance.kind;amount=finance.principal;delta=kind==='loan'?amount:0;name='Nexo Banca';concept=(kind==='loan'?'Formalización de préstamo · ':'Formalización de leasing · ')+finance.title;reference='FIN-'+id.slice(0,8).toUpperCase();}
 else if(action.startsWith('installment-')){linkedProduct=await product(uuid(p.productId));if(!linkedProduct)throw new BankError('No se encuentra la financiación.',404);const next=linkedProduct.data.schedule.find(s=>!linkedProduct!.payments.some(x=>x.installment===s.number));if(!next)throw new BankError('Esta financiación ya está liquidada.');if(p.installment!==next.number)throw new BankError('La siguiente cuota ha cambiado. Actualiza el cuadro.',409);if(date<linkedProduct.data.bookingDate)throw new BankError('La fecha no puede ser anterior a la formalización.');installment=next.number;kind=linkedProduct.kind==='loan'?'loan_payment':'lease_payment';amount=next.total;delta=-amount;name='Nexo Banca';concept=(next.option?'Opción de compra':'Cuota '+next.number)+' · '+linkedProduct.title;reference=linkedProduct.id+'/'+next.number;}
 else{const allowed:BankKind[]=['transfer','receipt','payroll','collection','direct_debit','cash','fee','tax','social'];if(!allowed.includes(p.kind as BankKind))throw new BankError('Selecciona una operación manual.');kind=p.kind as BankKind;amount=cents(p.amount);delta=amount*(['receipt','collection'].includes(kind)?1:-1);concept=text(p.concept,'el concepto',160);
  if(kind==='collection'||kind==='direct_debit'){selectedMandate=await mandate(uuid(p.mandateId));if(!selectedMandate||selectedMandate.status!=='active'||selectedMandate.direction!==(kind==='collection'?'in':'out'))throw new BankError('Selecciona una domiciliación activa del tipo adecuado.');if(selectedMandate.signedDate>date)throw new BankError('La fecha no puede ser anterior a la firma del mandato.');name=selectedMandate.name;iban=selectedMandate.iban;mandateId=selectedMandate.reference;mandateDate=selectedMandate.signedDate;}
  else{name=['cash','fee','tax','social'].includes(kind)?({cash:`${companyProfile().name}`,fee:'Nexo Banca',tax:'Agencia Tributaria',social:'Tesorería General de la Seguridad Social'} as Record<string,string>)[kind]:text(p.name,'el beneficiario o cliente',120);if(['transfer','receipt','payroll'].includes(kind))iban=inputIban(p.iban);}
  if(iban&&!validIban(iban))warnings.push('El IBAN no supera el control de dígitos. Comprueba su uso en este supuesto.');if(iban&&iban===a.iban)throw new BankError(`La cuenta de destino u origen debe ser distinta de la cuenta de ${companyProfile().shortName}.`);
 }
 const now=new Date().toISOString(),b:BankBatch={id,kind,filename:'',messageId:reference||id,format:'Manual',count:1,total:amount,delta,before:a.balance,after:a.balance+delta,bookingDate:date,createdAt:now,warnings,hasXml:false};
 if(preview)return json({batch:b,account:a,fingerprint,finance,installment:linkedProduct?.data.schedule.find(s=>s.number===installment)||null,warnings});
 if(p.fingerprint!==fingerprint)throw new BankError('La operación ha cambiado. Revísala de nuevo.',409);if(p.revision!==a.revision)throw new BankError('El saldo ha cambiado. Revisa la operación de nuevo.',409);if(warnings.length&&!p.warningsAccepted)throw new BankError('Confirma la revisión del IBAN.');if(b.after<0)throw new BankError('Saldo insuficiente.',409);if(b.after>1e12)throw new BankError('Se supera el saldo máximo de la simulación.',409);
 const count=await db().prepare('SELECT COUNT(*) AS n FROM bank_movements WHERE company_id=?').bind(companyId()).first<{n:number}>();if((count?.n||0)>=10000)throw new BankError('Se ha alcanzado el límite de movimientos.',409);
 if(finance){const n=await db().prepare('SELECT COUNT(*) AS n FROM bank_products WHERE company_id=?').bind(companyId()).first<{n:number}>();if((n?.n||0)>=200)throw new BankError('Se ha alcanzado el límite de 200 contratos de financiación.',409);}
 const committed='EXISTS(SELECT 1 FROM bank_batches WHERE id=? AND fingerprint=? AND created_at=?)',args=[id,fingerprint,now];const extra:D1PreparedStatement[]=[];
 if(finance)extra.push(db().prepare(`INSERT INTO bank_products(id,company_id,kind,title,data,created_at) SELECT ?,?,?,?,?,? WHERE ${committed}`).bind(id,companyId(),kind,finance.title,JSON.stringify(finance),now,...args));
 if(linkedProduct)extra.push(db().prepare(`INSERT INTO bank_product_payments(product_id,installment,batch_id) SELECT ?,?,? WHERE ${committed}`).bind(linkedProduct.id,installment,id,...args));
 // Guards share the same transaction as the ledger, including mandate cancellation or product deletion races.
 const guard=crypto.randomUUID(),checks:D1PreparedStatement[]=[];
 if(selectedMandate)checks.push(db().prepare('INSERT INTO practice_guards(id,valid) SELECT ?,CASE WHEN EXISTS(SELECT 1 FROM bank_mandates WHERE id=? AND revision=? AND status=?) THEN 1 ELSE 0 END').bind(guard,selectedMandate.id,selectedMandate.revision,'active'));
 if(linkedProduct)checks.push(db().prepare('INSERT INTO practice_guards(id,valid) SELECT ?,CASE WHEN EXISTS(SELECT 1 FROM bank_products WHERE id=?) AND NOT EXISTS(SELECT 1 FROM bank_product_payments WHERE product_id=? AND installment=?) THEN 1 ELSE 0 END').bind(guard,linkedProduct.id,linkedProduct.id,installment));
 try{const results=await db().batch([...checks,batchInsert(b,fingerprint,'manual:'+id,'',a.revision),db().prepare(`UPDATE bank_accounts SET balance=balance+?,revision=revision+1 WHERE id=? AND revision=? AND ${committed}`).bind(delta,companyId(),a.revision,...args),db().prepare(`INSERT INTO bank_movements(company_id,batch_id,line,name,iban,amount,delta,balance,concept,reference,kind,requested_date,booking_date,created_at,mandate_id,mandate_date,source_name,source_iban) SELECT ?,?,1,?,?,?,?,?,?,?,?,?,?,?,?,?,?,? WHERE ${committed}`).bind(companyId(),id,name,iban,amount,delta,b.after,concept,reference||id,kind,date,date,now,mandateId,mandateDate,`${companyProfile().name}`,a.iban,...args),...extra,db().prepare('DELETE FROM practice_guards WHERE id=?').bind(guard)]);if(!results[checks.length].meta.changes)throw new BankError('El saldo ha cambiado. Revisa de nuevo.',409);
 }catch(e){const raced=await batch(id);if(raced?.fingerprint===fingerprint)return json({...await details(id),product:await product(id)});if(String(e).includes('UNIQUE')||String(e).includes('practice_guard_valid')||String(e).includes('FOREIGN KEY'))throw new BankError('La operación ha cambiado o ya está contabilizada. Actualiza y revisa de nuevo.',409);throw e;}
 return json({...await details(id),product:finance?await product(id):null},201);
});}
