import type {BankReceiptDetails} from './bank-receipt-details';
export type BankKind='payment'|'payroll'|'collection'|'opening'|'funds'|'transfer'|'receipt'|'direct_debit'|'cash'|'fee'|'interest'|'tax'|'social'|'loan'|'leasing'|'loan_payment'|'lease_payment'|'spreadsheet';
export const kindNames:Record<BankKind,string>={payment:'Pago a proveedores',payroll:'Nóminas',collection:'Cobro de recibos',opening:'Saldo inicial',funds:'Ingreso de fondos',transfer:'Transferencia',receipt:'Abono de cliente',direct_debit:'Recibo domiciliado',cash:'Retirada de efectivo',fee:'Comisión bancaria',interest:'Abono de intereses',tax:'Pago de impuestos',social:'Pago de cotizaciones',loan:'Préstamo',leasing:'Contrato de leasing',loan_payment:'Cuota de préstamo',lease_payment:'Cuota de leasing',spreadsheet:'Importación de Excel'};
export type BankItem={name:string;iban:string;amount:number;concept:string;reference:string;requestedDate:string;kind:BankKind;mandateId:string;mandateDate:string;sourceName:string;sourceIban:string};
export type BankParsed={format:string;messageId:string;initiator:string;kind:BankKind;items:BankItem[];total:number;count:number;warnings:string[]};
export type BankAccount={id:string;name:string;iban:string;balance:number;revision:number;createdAt:string};
export type BankBatch={id:string;kind:BankKind;filename:string;messageId:string;format:string;count:number;total:number;delta:number;before:number;after:number;bookingDate:string;createdAt:string;warnings:string[];hasXml:boolean;receiptDetails?:BankReceiptDetails|null};
export type BankMovement=BankItem&{id:number;batchId:string;line:number;delta:number;balance:number;bookingDate:string;createdAt:string};
export type BankSummary={preferredIban?:string;account:BankAccount|null;movements:BankMovement[];batches:BankBatch[];total:number;page:number;pageSize:number;credits:number;debits:number};
export type BankPreview={parsed:BankParsed;account:BankAccount;duplicateId:string|null;delta:number;after:number};
export const money=(cents:number)=>(cents/100).toLocaleString('es-ES',{style:'currency',currency:'EUR'});
export const dateLabel=(value:string)=>/^\d{4}-\d{2}-\d{2}$/.test(value)?value.slice(8,10)+'/'+value.slice(5,7)+'/'+value.slice(0,4):value;
export const today=()=>new Date().toLocaleDateString('en-CA',{timeZone:'Europe/Madrid'});
