import {socialDate,socialPeriod,socialMoney,type SocialReceipt} from './social-types';
import {registryNames,registryModels,type RegistryRecord} from './social-registry-types';
export type ReceiptSection={title:string;fields:[string,string][]};
export type ReceiptSummary={title:string;subtitle:string;reference:string;date:string;createdAt:string;sections:ReceiptSection[];note:string};
export function registrySummary(r:RegistryRecord):ReceiptSummary{
 const d=r.data,sections:ReceiptSection[]=[];
 if(r.kind==='company')sections.push({title:'Datos de la empresa',fields:[['Razón social',d.name],['NIF',d.nif],['CCC',d.ccc],['Régimen',d.regime],['Domicilio',d.address],['Municipio',d.postcode+' · '+d.city],['Provincia',d.province],['Representante',d.representative||'—']]},{title:'Actividad y cobertura',fields:[['Actividad económica',d.activity],['CNAE',d.cnae],['Entidad de cobertura',d.entity],['Inicio de actividad',socialDate(r.effectiveDate)]]});
 if(r.kind==='person')sections.push({title:'Datos de la persona',fields:[['Nombre y apellidos',r.title],[d.documentType,d.personId],['Nacimiento',socialDate(d.birthDate)],['Nacionalidad',d.nationality],['Domicilio',d.address],['Municipio',d.postcode+' · '+d.city],['Provincia',d.province],['Número de Seguridad Social',d.nss]]},{title:'Solicitud',fields:[['Fecha de solicitud',socialDate(r.effectiveDate)],['Número de Seguridad Social',d.numberAssigned==='yes'?'Asignado en la simulación':'Aportado en la solicitud']]});
 if(r.kind==='employment')sections.push({title:'Empresa y trabajador',fields:[['Razón social',d.company],['NIF de la empresa',d.nif],['CCC',d.ccc],['Régimen',d.regime],['Trabajador',d.worker],[d.documentType,d.workerId],['Número de Seguridad Social',d.nss]]},{title:'Datos del alta',fields:[['Fecha de efectos',socialDate(r.effectiveDate)],['Código de contrato',d.contract],['Grupo de cotización',d.group],['Jornada',d.percent+' %'],['Puesto de trabajo',d.occupation]]});
 return {title:'Justificante de registro',subtitle:registryNames[r.kind]+' · '+registryModels[r.kind],reference:r.reference,date:r.effectiveDate,createdAt:r.createdAt,sections,note:r.kind==='company'?'Inscripción registrada en el Régimen General dentro de la simulación.':r.kind==='person'?'Afiliación registrada. El alta laboral en una empresa se tramita por separado.':'Alta registrada con la fecha de efectos indicada en la solicitud.'};
}
export function contributionSummary(r:SocialReceipt):ReceiptSummary{
 const b=r.batch,h=r.documents[0]?.header,p=r.payment,sections:ReceiptSection[]=[{title:'Empresa y liquidación',fields:[['Razón social',b.company],['Código de empresario',h?.employerId||'—'],['CCC',b.ccc],['Periodo de liquidación',socialPeriod(b.periodFrom)+' – '+socialPeriod(b.periodTo)],['Trabajadores',String(b.workers)],['Número de liquidación',h?.liquidationNumber||'—'],['Calificador',h?.qualification||'—'],['Importe de la liquidación',p?.amount!==undefined?socialMoney(p.amount):b.total===null?'No consta RLC':socialMoney(b.total)]]},{title:'Documentación registrada',fields:r.documents.map(d=>[d.kind,d.filename])}];
 if(p){const fields:[string,string][]=[['Estado del ingreso',p.label]];if(p.liquidationId&&p.liquidationId!==b.id)fields.push(['RLC vinculado',p.liquidationReference||'—']);if(p.status==='paid')fields.push(['Fecha del pago',socialDate(p.date||'')],['Referencia del pago simulado',p.reference||'—'],['Cuenta de cargo · Nexo',p.iban||'—']);sections.push({title:'Pago de cotizaciones',fields});}
 const note=p?.status==='paid'?'Pago registrado en Nexo dentro de la simulación. No acredita un ingreso real.':p?.status==='pending'?'Documentación registrada. El pago de cuotas sigue pendiente.':!p?'Documentación registrada. No acredita el pago de cuotas.':p.liquidationId?'Documentación registrada sin importe a ingresar.':'La RNT no genera un cargo bancario. Presente el RLC para liquidar las cuotas.';
 return {title:'Justificante de presentación',subtitle:'Documentos de cotización · '+b.kinds,reference:b.reference,date:b.submissionDate,createdAt:b.createdAt,sections,note:note+(b.warnings.length?' Las observaciones aceptadas pueden consultarse en el expediente.':'')};
}
export function registerDate(value:string){return new Date(value).toLocaleString('es-ES',{timeZone:'Europe/Madrid',hour12:false});}
