'use client';
import {companyFetch,companyUrl,clientCompany} from '@/lib/company-client';

import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {FinanceSchedule} from './manual-operations';
import type {FinanceProduct} from '@/lib/bank-finance';
import {money,dateLabel} from '@/lib/bank-types';
export default function FinanceReceipt(){const [data,setData]=useState<FinanceProduct|null>(null),[error,setError]=useState('');useEffect(()=>{const id=new URLSearchParams(location.hash.split('?')[1]||location.search).get('id');if(!id){setError('Falta la referencia.');return;}companyFetch('/api/banco/operaciones?product='+encodeURIComponent(id)).then(async r=>{const d=await r.json() as {product:FinanceProduct;error?:string};if(!r.ok)throw Error(d.error);setData(d.product);}).catch(e=>setError(e.message));},[]);return <main className="bank-finance-sheet"><nav className="bank-finance-controls"><a href={companyUrl("/servicios/banco")}>Volver al banco</a><Button onClick={()=>window.print()} disabled={!data}>Imprimir / guardar PDF</Button></nav><strong className="bank-wordmark">nexo.</strong><p>SIMULACIÓN EDUCATIVA · SIN VALIDEZ CONTRACTUAL</p>{error?<p role="alert">{error}</p>:data?<><h1>{data.kind==='loan'?'Préstamo de empresa':'Contrato de leasing'}</h1><p><strong>{clientCompany().name}</strong> · {data.title}</p><p>Referencia: {data.id}<br/>Formalización: {dateLabel(data.data.bookingDate)}<br/>Capital: {money(data.data.principal)} · Plazo: {data.data.months} meses · TIN: {data.data.tin} %</p>{data.kind==='leasing'&&<p>IVA del supuesto: {data.data.vat} % · Opción de compra sin IVA: {money(data.data.residual)}. El capital financia el bien, sin abono en la cuenta.</p>}<p>Cuotas mensuales. Sin comisiones ni carencia. El último pago ajusta los redondeos. Cada cuota se contabiliza al confirmar su pago.</p><FinanceSchedule data={data.data} payments={data.payments}/><p>Documento de simulación. No constituye un contrato con una entidad financiera.</p></>:<p role="status">Consultando financiación…</p>}</main>;}
