'use client';
import {companyFetch,companyUrl} from '@/lib/company-client';

import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Checkbox} from '@/components/ui/checkbox';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {FileText,Plus,CheckCircle2} from 'lucide-react';
import {DeleteRecord} from '@/components/practice/delete-record';
import {newMailId as newId} from '@/lib/mail-types';
import {money,today,dateLabel,kindNames,type BankBatch,type BankAccount} from '@/lib/bank-types';
import type {FinanceData,FinanceProduct,Mandate,Installment} from '@/lib/bank-finance';
type Mode='manual'|'mandates'|'finance';
type Preview={batch:BankBatch;account:BankAccount;fingerprint:string;finance:FinanceData|null;installment:Installment|null;warnings:string[]};
export async function operationPost(data:Record<string,unknown>){const r=await companyFetch('/api/banco/operaciones',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const d=await r.json() as Preview&{error?:string};if(!r.ok)throw Error(d.error||'No se ha podido registrar la operación.');return d;}
function Field({label,value,onChange,type='text',required=true,min,max,step}:{label:string;value:string;onChange:(v:string)=>void;type?:string;required?:boolean;min?:string;max?:string;step?:string}){return <label className="bank-field"><span>{label}</span><Input type={type} value={value} onChange={e=>onChange(e.target.value)} required={required} min={min} max={max} step={step} maxLength={160}/></label>;}
function csvPlan(p:FinanceData){const table=[['Cuota','Vencimiento','Capital EUR','Intereses EUR','IVA EUR','Total EUR','Pendiente EUR'],...p.schedule.map(s=>[s.option?'Opción de compra':s.number,s.date,...[s.principal,s.interest,s.tax,s.total,s.balance].map(v=>(v/100).toFixed(2).replace('.',','))])];const data='\uFEFF'+table.map(row=>row.map(v=>'"'+String(v).replaceAll('"','""')+'"').join(';')).join('\r\n'),url=URL.createObjectURL(new Blob([data],{type:'text/csv;charset=utf-8'})),link=document.createElement('a');link.href=url;link.download='cuadro-'+p.kind+'.csv';link.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}
export function FinanceSchedule({data,payments=[]}:{data:FinanceData;payments?:FinanceProduct['payments']}){return <div className="bank-table-wrap"><table className="bank-table"><thead><tr><th>Cuota</th><th>Vencimiento</th><th className="bank-number">Capital</th><th className="bank-number">Intereses</th>{data.kind==='leasing'&&<th className="bank-number">IVA</th>}<th className="bank-number">Total</th><th className="bank-number">Pendiente</th><th>Estado</th></tr></thead><tbody>{data.schedule.map(s=>{const paid=payments.find(p=>p.installment===s.number);return <tr key={s.number}><td>{s.option?'Opción de compra':s.number}</td><td>{dateLabel(s.date)}</td><td className="bank-number">{money(s.principal)}</td><td className="bank-number">{money(s.interest)}</td>{data.kind==='leasing'&&<td className="bank-number">{money(s.tax)}</td>}<td className="bank-number">{money(s.total)}</td><td className="bank-number">{money(s.balance)}</td><td>{paid?<a href={companyUrl('/servicios/banco/justificante?id='+paid.batchId)}>Pagada · justificante</a>:s.option?'Opcional':'Pendiente'}</td></tr>;})}</tbody></table></div>;}
export default function ManualOperations({mode,account,onChanged}:{mode:Mode;account:BankAccount;onChanged:(batch?:BankBatch)=>void|Promise<void>}){
 const [products,setProducts]=useState<FinanceProduct[]>([]),[mandates,setMandates]=useState<Mandate[]>([]),[error,setError]=useState(''),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[message,setMessage]=useState('');
 const [editor,setEditor]=useState<'finance'|'mandate'|null>(null),[selected,setSelected]=useState<string|null>(null),[payment,setPayment]=useState<{productId:string;installment:number;title:string}|null>(null);
 const fresh=()=>({id:newId(),kind:'transfer',name:'',iban:'',amount:'',concept:'',reference:'',bookingDate:today(),mandateId:'',title:'',months:'12',tin:'',vat:'21',residual:'0',firstDate:'',signedDate:today(),direction:'out'});
 const [form,setForm]=useState(fresh),[review,setReview]=useState<Preview|null>(null),[accepted,setAccepted]=useState(false);
 async function load(){setLoading(true);try{const r=await companyFetch('/api/banco/operaciones',{cache:'no-store'}),d=await r.json() as {products:FinanceProduct[];mandates:Mandate[];error?:string};if(!r.ok)throw Error(d.error||"No se puede consultar la banca.");setProducts(d.products);setMandates(d.mandates);}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
 useEffect(()=>{void load();},[mode,account.revision]);
 function change(key:string,value:string){setForm(f=>({...f,[key]:value}));setReview(null);setError('');setAccepted(false);}
 function start(type:'finance'|'mandate',kind='loan'){setEditor(type);setPayment(null);setForm({...fresh(),kind});setReview(null);setError('');setMessage('');setAccepted(false);}
 function pay(p:FinanceProduct){const s=p.data.schedule.find(s=>!p.payments.some(paid=>paid.installment===s.number));if(!s)return;setForm({...fresh(),bookingDate:s.date});setPayment({productId:p.id,installment:s.number,title:(s.option?'Opción de compra':'Cuota '+s.number)+' · '+p.title});setReview(null);setError('');setAccepted(false);}
 const family=payment?'installment':editor==='finance'?'finance':'manual';
 const request=()=>({...form,...(payment?{productId:payment.productId,installment:payment.installment}:{})});
 async function inspect(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');setMessage('');try{setReview(await operationPost({...request(),action:family+'-preview'}));}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function execute(){if(!review)return;setBusy(true);setError('');try{const d=await operationPost({...request(),action:family+'-execute',consent:true,warningsAccepted:accepted,fingerprint:review.fingerprint,revision:review.account.revision});setReview(null);if(!editor&&!payment)setForm(fresh());setEditor(null);setPayment(null);setMessage('Operación registrada.');await load();await onChanged(d.batch);}catch(e){setError((e as Error).message);setReview(null);}finally{setBusy(false);}}
 async function saveMandate(e:React.FormEvent){e.preventDefault();setBusy(true);setError('');try{await operationPost({...form,action:'mandate-create',consent:true,warningsAccepted:accepted});setEditor(null);setMessage('Domiciliación registrada.');await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 async function status(m:Mandate){setBusy(true);setError('');try{await operationPost({action:'mandate-status',id:m.id,status:m.status==='active'?'inactive':'active',revision:m.revision,consent:true});await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
 const reviewPanel=review&&<section className="bank-manual-review"><h3>Revisa la operación</h3><dl><div><dt>Operación</dt><dd>{kindNames[review.batch.kind]}</dd></div><div><dt>Importe</dt><dd>{money(review.batch.total)}</dd></div><div><dt>Movimiento en cuenta</dt><dd>{review.batch.delta>0?'+':''}{money(review.batch.delta)}</dd></div><div><dt>Fecha</dt><dd>{dateLabel(review.batch.bookingDate)}</dd></div><div><dt>Saldo resultante</dt><dd>{money(review.batch.after)}</dd></div></dl>{review.finance&&<><p>{review.finance.months} cuotas mensuales · TIN {review.finance.tin} % · {review.finance.kind==='leasing'?'IVA del supuesto '+review.finance.vat+' % · Opción de compra '+money(review.finance.residual):'Cuotas constantes, con ajuste de redondeo en la última.'}</p><p>Intereses totales: <strong>{money(review.finance.schedule.reduce((n,s)=>n+s.interest,0))}</strong>. Sin comisiones ni carencia.</p>{review.finance.kind==='leasing'&&<p>El bien queda financiado; el capital no se ingresa en la cuenta. Las cuotas se cargan al contabilizarlas.</p>}<details><summary>Ver cuadro de cuotas</summary><FinanceSchedule data={review.finance}/></details></>}{review.installment&&<p>Capital {money(review.installment.principal)} · Intereses {money(review.installment.interest)} · IVA {money(review.installment.tax)}</p>}{review.warnings.length>0&&<label className="bank-check"><Checkbox checked={accepted} onCheckedChange={v=>setAccepted(v===true)}/><span>{review.warnings.join(' ')} Confirmo los datos de la práctica.</span></label>}{review.batch.after<0&&<p className="bank-error">Saldo insuficiente.</p>}<div className="bank-manual-actions"><Button variant="outline" type="button" disabled={busy} onClick={()=>setReview(null)}>Modificar datos</Button><Button type="button" onClick={()=>void execute()} disabled={busy||review.batch.after<0||(review.warnings.length>0&&!accepted)}><CheckCircle2 size={17}/>{busy?'Registrando…':editor==='finance'?'Confirmar y formalizar':'Confirmar operación'}</Button></div></section>;
 return <section className="bank-section bank-manual-section">
  <div className="bank-section-title"><div><h2>{mode==='manual'?'Operaciones manuales':mode==='mandates'?'Domiciliaciones':'Préstamos y leasing'}</h2><p>{mode==='manual'?'Introduce los datos, revisa el resultado y confirma.':mode==='mandates'?'Mandatos para cobrar a clientes y pagar recibos de proveedores.':'Consulta las condiciones, formaliza y contabiliza las cuotas de la práctica.'}</p></div>{mode==='mandates'&&<Button onClick={()=>start('mandate')}><Plus size={17}/>Nueva domiciliación</Button>}{mode==='finance'&&<div className="bank-manual-actions"><Button onClick={()=>start('finance','loan')}>Solicitar préstamo</Button><Button variant="outline" onClick={()=>start('finance','leasing')}>Solicitar leasing</Button></div>}</div>
  {error&&!editor&&!payment&&<p className="bank-error" role="alert">{error}</p>}{message&&<p className="bank-operation-message" role="status">{message}</p>}
  {mode==='manual'&&<form onSubmit={inspect}><fieldset disabled={busy}><div className="bank-manual-grid"><label className="bank-field"><span>Tipo de operación</span><select value={form.kind} onChange={e=>change('kind',e.target.value)}>{['transfer','receipt','payroll','collection','direct_debit','cash','fee','tax','social'].map(k=><option key={k} value={k}>{kindNames[k as keyof typeof kindNames]}</option>)}</select></label><Field label="Fecha de contabilización" type="date" value={form.bookingDate} onChange={v=>change('bookingDate',v)}/>{['collection','direct_debit'].includes(form.kind)?<label className="bank-field bank-span-two"><span>Domiciliación</span><select required value={form.mandateId} onChange={e=>change('mandateId',e.target.value)}><option value="">Selecciona un mandato activo</option>{mandates.filter(m=>m.status==='active'&&m.direction===(form.kind==='collection'?'in':'out')).map(m=><option value={m.id} key={m.id}>{m.name} · {m.reference}</option>)}</select><small>Los mandatos se dan de alta en Domiciliaciones.</small></label>:!['cash','fee','tax','social'].includes(form.kind)&&<><Field label={form.kind==='receipt'?'Cliente / ordenante':'Beneficiario'} value={form.name} onChange={v=>change('name',v)}/><Field label={form.kind==='receipt'?'IBAN de origen':'IBAN de destino'} value={form.iban} onChange={v=>change('iban',v)}/></>}<Field label="Importe (€)" type="number" min="0.01" step="0.01" value={form.amount} onChange={v=>change('amount',v)}/><Field label="Referencia (opcional)" value={form.reference} onChange={v=>change('reference',v)} required={false}/><div className="bank-span-two"><Field label="Concepto" value={form.concept} onChange={v=>change('concept',v)}/></div></div><p className="bank-manual-note">La operación se contabiliza al confirmar con la fecha indicada.{form.kind==='tax'&&' Para pagar una declaración presentada en Hacienda, utilice la pestaña Impuestos. Este apunte manual no liquida ningún expediente.'}{form.kind==='social'&&' Para pagar un RLC presentado, utilice la pestaña Cotizaciones. Este apunte manual no liquida ningún expediente.'}</p>{!review&&<Button type="submit">Revisar operación</Button>}</fieldset>{reviewPanel}</form>}
  {mode==='mandates'&&(loading?<p role="status">Consultando domiciliaciones…</p>:mandates.length?<div className="bank-table-wrap"><table className="bank-table"><thead><tr><th>Titular / IBAN</th><th>Mandato</th><th>Operativa</th><th>Estado</th><th>Gestiones</th></tr></thead><tbody>{mandates.map(m=><tr key={m.id}><td><strong>{m.name}</strong><small>{m.iban}</small></td><td>{m.reference}<small>Firma: {dateLabel(m.signedDate)}</small></td><td>{m.direction==='in'?'Cobros':'Pagos'}</td><td>{m.status==='active'?'Activa':'Suspendida'}</td><td><div className="bank-manual-actions"><Button variant="outline" size="sm" disabled={busy} onClick={()=>void status(m)}>{m.status==='active'?'Suspender':'Reactivar'}</Button><DeleteRecord scope="mandate" id={m.id} title={m.name+' · '+m.reference} onDeleted={load}/></div></td></tr>)}</tbody></table></div>:<p className="bank-empty">No hay domiciliaciones registradas.</p>)}
  {mode==='finance'&&(loading?<p role="status">Consultando financiación…</p>:products.length?<div className="bank-product-grid">{products.map(p=>{const next=p.data.schedule.find(s=>!p.payments.some(paid=>paid.installment===s.number)),paidCapital=p.data.schedule.filter(s=>p.payments.some(paid=>paid.installment===s.number)).reduce((n,s)=>n+s.principal,0);return <article className="bank-product-card" key={p.id}><span className="bank-tag">{p.kind==='loan'?'Préstamo':'Leasing'}</span><h3>{p.title}</h3><strong className="bank-product-amount">{money(p.data.principal-paidCapital)}</strong><p>Capital pendiente · {p.data.tin} % TIN</p><p>{next?(next.option?'Opción de compra: ':'Próxima cuota: ')+money(next.total)+' · '+dateLabel(next.date):'Liquidado'}</p><div className="bank-manual-actions"><Button variant="outline" onClick={()=>setSelected(selected===p.id?null:p.id)}><FileText size={16}/>Cuadro de cuotas</Button>{next&&<Button onClick={()=>pay(p)}>{next.option?'Ejercer opción de compra':'Contabilizar cuota'}</Button>}<DeleteRecord scope="bank" id={p.id} title={p.title} onDeleted={async()=>{await load();await onChanged();}}/></div>{selected===p.id&&<><div className="bank-manual-actions"><Button variant="outline" onClick={()=>csvPlan(p.data)}>Descargar cuadro CSV</Button><a href={companyUrl('/servicios/banco/financiacion?id='+p.id)}>Contrato y cuadro imprimible</a></div><FinanceSchedule data={p.data} payments={p.payments}/></>}</article>;})}</div>:<p className="bank-empty">No hay préstamos ni contratos de leasing.</p>)}
  <Dialog open={!!editor||!!payment} onOpenChange={v=>{if(!v&&!busy){setEditor(null);setPayment(null);setReview(null);setError('');}}}><DialogContent className="bank-operation-dialog"><DialogTitle>{payment?payment.title:editor==='mandate'?'Nueva domiciliación':form.kind==='loan'?'Solicitar préstamo':'Solicitar leasing'}</DialogTitle><DialogDescription>{editor==='mandate'?'Registra la autorización de cobro o pago.':'Indica las condiciones del supuesto y revisa el resultado antes de confirmar.'}</DialogDescription>{error&&<p className="bank-error" role="alert">{error}</p>}<form onSubmit={editor==='mandate'?saveMandate:inspect}><fieldset disabled={busy}><div className="bank-manual-grid">{editor==='mandate'?<><label className="bank-field"><span>Operativa</span><select value={form.direction} onChange={e=>change('direction',e.target.value)}><option value="out">Pagar recibos a proveedores</option><option value="in">Cobrar recibos a clientes</option></select></label><Field label="Titular" value={form.name} onChange={v=>change('name',v)}/><Field label="IBAN" value={form.iban} onChange={v=>change('iban',v)}/><Field label="Referencia de mandato" value={form.reference} onChange={v=>change('reference',v)}/><Field label="Fecha de firma" type="date" value={form.signedDate} onChange={v=>change('signedDate',v)}/><label className="bank-check"><Checkbox checked={accepted} onCheckedChange={v=>setAccepted(v===true)}/>He revisado el IBAN del supuesto.</label></>:payment?<Field label="Fecha de contabilización" type="date" value={form.bookingDate} onChange={v=>change('bookingDate',v)}/>:<><div className="bank-span-two"><Field label={form.kind==='loan'?'Finalidad':'Bien y proveedor'} value={form.title} onChange={v=>change('title',v)}/></div><Field label={form.kind==='loan'?'Capital solicitado (€)':'Valor del bien sin IVA (€)'} type="number" min="0.01" step="0.01" value={form.amount} onChange={v=>change('amount',v)}/><Field label="Plazo (meses)" type="number" min="1" max="240" step="1" value={form.months} onChange={v=>change('months',v)}/><Field label="TIN anual (%)" type="number" min="0" max="50" step="0.01" value={form.tin} onChange={v=>change('tin',v)}/><Field label="Fecha de formalización" type="date" value={form.bookingDate} onChange={v=>change('bookingDate',v)}/><Field label="Primer vencimiento" type="date" value={form.firstDate} onChange={v=>change('firstDate',v)}/>{form.kind==='leasing'&&<><Field label="Opción de compra sin IVA (€)" type="number" min="0" step="0.01" value={form.residual} onChange={v=>change('residual',v)}/><Field label="IVA del supuesto (%)" type="number" min="0" max="30" step="0.01" value={form.vat} onChange={v=>change('vat',v)}/></>}</>}</div>{!review&&<Button type="submit" disabled={busy}>{busy?'Preparando…':editor==='mandate'?'Guardar domiciliación':'Calcular y revisar'}</Button>}</fieldset>{reviewPanel}</form></DialogContent></Dialog>
 </section>;
}
