'use client';
import {clientCompany,companyUrl,companyFetch} from '@/lib/company-client';

import {useEffect,useState} from 'react';
import {DeleteRecord} from '@/components/practice/delete-record';
import {Button} from '@/components/ui/button';
import {Printer,Download} from 'lucide-react';
import {kindNames,money,dateLabel,type BankBatch,type BankMovement} from '@/lib/bank-types';
export type ReceiptData={batch:BankBatch;items:BankMovement[];taxFiling?:{id:string;reference:string;model:string}|null;socialFiling?:{id:string;reference:string;ccc:string;periodFrom:string;periodTo:string}|null};
export function Receipt({data}:{data:ReceiptData}){
 const {batch:b,items}=data;
 return <article className="bank-receipt"><div className="bank-receipt-heading"><strong className="bank-wordmark">nexo<span>.</span></strong><span>BANCA DE EMPRESAS</span></div><p className="bank-eyebrow">JUSTIFICANTE DE OPERACIÓN · SIMULACIÓN</p><h1>{kindNames[b.kind]}</h1><dl className="bank-receipt-meta"><div><dt>Titular de la cuenta</dt><dd>{clientCompany().name}</dd></div><div><dt>Fecha de contabilización</dt><dd>{dateLabel(b.bookingDate)}</dd></div><div><dt>Referencia del justificante</dt><dd>{b.id}</dd></div><div><dt>{data.taxFiling?'NRC simulado':'Referencia de la operación'}</dt><dd>{b.filename||data.taxFiling||data.socialFiling?b.messageId:'Operación manual'}</dd></div>{data.taxFiling&&<div><dt>Declaración vinculada</dt><dd><a href={companyUrl('/servicios/agencia-tributaria?declaracion='+data.taxFiling.id)}>{data.taxFiling.reference} · Modelo {data.taxFiling.model}</a></dd></div>}{data.socialFiling&&<><div><dt>Liquidación vinculada</dt><dd><a href={companyUrl('/servicios/seguridad-social/justificante?id='+data.socialFiling.id)}>{data.socialFiling.reference}</a></dd></div><div><dt>CCC / Periodo</dt><dd>{data.socialFiling.ccc} · {data.socialFiling.periodFrom}{data.socialFiling.periodFrom!==data.socialFiling.periodTo?' – '+data.socialFiling.periodTo:''}</dd></div></>}</dl><div className="bank-receipt-amount"><span>{b.kind==='leasing'?'Capital financiado':b.delta<0?'Importe cargado':'Importe abonado'}</span><strong>{money(b.total)}</strong><span>{b.kind==='leasing'?'Contrato formalizado · Sin ingreso en cuenta':`${b.count} ${b.count===1?'operación':'operaciones'} · Contabilizada`}</span></div><div className="bank-table-wrap"><table className="bank-table bank-receipt-table"><thead><tr><th>Beneficiario / cliente</th><th>Concepto y referencia</th><th>{b.hasXml?'Fecha del XML':'Fecha'}</th><th className="bank-number">Importe</th></tr></thead><tbody>{items.map(i=><tr key={i.id}><td><strong>{i.name}</strong><small>{data.taxFiling||data.socialFiling?'Cargo en '+i.sourceIban:i.iban||'Cuenta de prácticas'}</small></td><td>{i.concept||'Sin concepto'}<small>{i.reference}</small>{i.mandateId&&<small>Mandato: {i.mandateId} · {dateLabel(i.mandateDate)}</small>}</td><td>{dateLabel(i.requestedDate)}</td><td className="bank-number">{money(i.amount)}</td></tr>)}</tbody></table></div><div className="bank-receipt-balances"><p>Saldo anterior <strong>{money(b.before)}</strong></p><p>Saldo tras la operación <strong>{money(b.after)}</strong></p></div>{b.warnings.length>0&&<div className="bank-receipt-warnings"><strong>Advertencias revisadas al confirmar</strong><ul>{b.warnings.map(w=><li key={w}>{w}</li>)}</ul></div>}<footer>Documento de simulación educativa. No acredita pagos ni cobros reales.<br/>Nexo Banca · {clientCompany().name} · Aula de simulación</footer></article>;
}
export default function ReceiptPage(){
 const [data,setData]=useState<ReceiptData|null>(null),[error,setError]=useState('');
 useEffect(()=>{const id=new URLSearchParams((window.location.hash.split('?')[1]||'')).get('id');if(!id){setError('Falta la referencia del justificante.');return;}void companyFetch('/api/banco?'+new URLSearchParams({batch:id}),{cache:'no-store'}).then(async r=>{const d=await r.json() as ReceiptData&{error?:string};if(!r.ok)throw Error(d.error);setData(d);}).catch(e=>setError(e.message));},[]);
 return <main className="bank-print-page"><nav className="bank-print-controls"><a href={companyUrl("/servicios/banco")}>Volver al banco</a>{data&&<><Button variant="outline" onClick={()=>window.print()}><Printer size={17}/>Imprimir / guardar PDF</Button>{data.batch.kind!=='opening'&&<DeleteRecord scope="bank" id={data.batch.id} title={kindNames[data.batch.kind]} onDeleted={()=>{window.location.href=companyUrl("/servicios/banco");}}/>}{data.batch.hasXml&&<Button asChild variant="outline"><a href={companyUrl('/api/banco?'+new URLSearchParams({batch:data.batch.id,xml:'1'}))}><Download size={17}/>XML presentado</a></Button>}</>}</nav>{error?<p className="bank-error" role="alert">{error}</p>:data?<Receipt data={data}/>:<p role="status">Abriendo justificante…</p>}</main>;
}
