'use client';
import {newMailId} from '@/lib/mail-types';
import {useRef,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Checkbox} from '@/components/ui/checkbox';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {companyFetch,companyUrl} from '@/lib/company-client';
import {parseImportMatrix,type ImportRow,type ImportPreview} from '@/lib/bank-import';
import {money,dateLabel} from '@/lib/bank-types';
import type {Workbook} from 'exceljs';
import {readBankWorkbook} from '@/lib/bank-spreadsheet';
async function post(data:unknown){const r=await companyFetch('/api/banco/importar',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(data)});const d=await r.json() as any;if(!r.ok)throw Error(d.error||'No se ha podido importar el archivo.');return d;}
export default function SpreadsheetImport({onChanged}:{onChanged:()=>void|Promise<void>}){
 const [validSource,setValidSource]=useState(false);
 const [file,setFile]=useState(''),[sheets,setSheets]=useState<string[]>([]),[sheet,setSheet]=useState(''),[rows,setRows]=useState<ImportRow[]>([]),[errors,setErrors]=useState<string[]>([]),[preview,setPreview]=useState<ImportPreview|null>(null),[busy,setBusy]=useState(false),[allow,setAllow]=useState(false),[consent,setConsent]=useState(false),[result,setResult]=useState<{id:string;count:number}|null>(null);
 const workbook=useRef<Workbook|null>(null),operation=useRef('');
 function readSheet(name:string,book=workbook.current){if(!book)return;setValidSource(false);setSheet(name);operation.current=newMailId();setPreview(null);setConsent(false);setResult(null);const ws=book.getWorksheet(name)!;const matrix:unknown[][]=[];if(ws.rowCount>10000||ws.columnCount>100){setErrors(['La hoja es demasiado grande. Usa una hoja con un máximo de 500 movimientos y sin filas sobrantes.']);setRows([]);return;}for(let i=1;i<=ws.rowCount;i++){const row=ws.getRow(i);const values:unknown[]=[];for(let j=1;j<=Math.min(ws.columnCount,40);j++){const v=row.getCell(j).value;if(v&&typeof v==='object'&&!(v instanceof Date)){if('formula' in v||'sharedFormula' in v){values.push(v);}else if('richText' in v)values.push(v.richText.map(x=>x.text).join(''));else if('text' in v)values.push(v.text);else values.push('');}else values.push(v);}matrix.push(values);}try{const parsed=parseImportMatrix(matrix);setRows(parsed.rows);setValidSource(!parsed.errors.length);setErrors(parsed.errors);}catch(e){setRows([]);setErrors([(e as Error).message]);}}
 async function choose(selected?:File){if(!selected)return;setBusy(true);setValidSource(false);setPreview(null);setResult(null);setErrors([]);setRows([]);setSheets([]);setSheet('');setConsent(false);setAllow(false);operation.current=newMailId();setFile(selected.name);try{if(!/\.xlsx$/i.test(selected.name)||selected.size>5*1024*1024)throw Error('Selecciona un archivo Excel .xlsx de hasta 5 MB. En Excel puedes usar Guardar como para convertir un .xls.');let book:Workbook;try{book=await readBankWorkbook(await selected.arrayBuffer());}catch{throw Error('No se ha podido leer este Excel. Ábrelo en Excel, guárdalo de nuevo como .xlsx y vuelve a seleccionarlo.');}workbook.current=book;const names=book.worksheets.filter(s=>s.state==='visible').map(s=>s.name);if(!names.length)throw Error('El libro no contiene hojas visibles.');setSheets(names);readSheet(names.find(n=>n.toLowerCase()==='movimientos')||names[0],book);}catch(e){setErrors([(e as Error).message||'No se puede leer el archivo.']);}finally{setBusy(false);}}
 async function review(){setBusy(true);setErrors([]);setConsent(false);try{setPreview(await post({action:'preview',rows,filename:file,allowDuplicates:allow}));}catch(e){setErrors([(e as Error).message]);}finally{setBusy(false);}}
 async function execute(){if(!preview)return;setBusy(true);setErrors([]);try{const d=await post({action:'execute',id:operation.current,rows,filename:file,allowDuplicates:allow,consent,revision:preview.revision,fingerprint:preview.fingerprint});setResult(d);setPreview(null);setRows([]);await onChanged();}catch(e){setErrors([(e as Error).message]);}finally{setBusy(false);}}
 return <section className="bank-section excel-import"><div className="bank-section-title"><div><h2>Movimientos desde Excel</h2><p>Prepara la práctica en una hoja e incorpora hasta 500 movimientos a la cuenta.</p></div><Button asChild variant="outline"><a href={import.meta.env.BASE_URL + "plantillas/Plantilla_movimientos_bancarios.xlsx"} download>Descargar plantilla Excel</a></Button></div><p>Usa <strong>Fecha, Concepto e Importe</strong>: positivo para ingresos y negativo para gastos. También admite columnas separadas Entrada y Salida. Empresa, Referencia e IBAN son opcionales.</p><label className="excel-field">Seleccionar archivo .xlsx<Input type="file" accept=".xlsx,application/vnd.openxmlformats-officedocument.spreadsheetml.sheet" disabled={busy} onChange={e=>{void choose(e.target.files?.[0]);e.target.value='';}}/></label>{sheets.length>1&&<label className="excel-field">Hoja del libro<Select value={sheet} onValueChange={readSheet} disabled={busy}><SelectTrigger><SelectValue/></SelectTrigger><SelectContent>{sheets.map(n=><SelectItem key={n} value={n}>{n}</SelectItem>)}</SelectContent></Select></label>}
 {errors.length>0&&<div className="bank-error" role="alert">{errors.slice(0,20).map((e,i)=><p key={i}>{e}</p>)}{errors.length>20&&<p>Corrige también las otras {errors.length-20} incidencias del archivo.</p>}</div>}
 {rows.length>0&&!result&&<><p>{file} · {rows.length} movimientos leídos. Se añaden a la cuenta; el saldo inicial se configura en Nexo.</p><label className="excel-check"><Checkbox checked={allow} disabled={busy} onCheckedChange={v=>{setAllow(v===true);setPreview(null);setConsent(false);}}/>Incluir también coincidencias (solo si son operaciones distintas)</label><Button disabled={busy||!validSource} onClick={()=>void review()}>{busy?'Revisando…':'Revisar importación'}</Button></>}
 {preview&&<><div className="excel-summary"><div><span>Se incorporarán</span><strong>{preview.count} movimientos</strong></div><div><span>Ingresos / gastos</span><strong>{money(preview.credits)} / {money(preview.debits)}</strong></div><div><span>Saldo resultante</span><strong>{money(preview.after)}</strong></div></div>{preview.warnings.map(w=><p className="bank-notice" key={w}>{w}</p>)}{preview.errors.map(e=><p className="bank-error" key={e}>{e}</p>)}<Table><TableHeader><TableRow><TableHead>Fila</TableHead><TableHead>Fecha</TableHead><TableHead>Concepto / empresa</TableHead><TableHead>Importe</TableHead><TableHead>Revisión</TableHead></TableRow></TableHeader><TableBody>{preview.rows.map(r=><TableRow key={r.row}><TableCell>{r.row}</TableCell><TableCell>{dateLabel(r.date)}</TableCell><TableCell>{r.concept}<small className="excel-secondary">{r.name}{r.reference?' · '+r.reference:''}</small></TableCell><TableCell>{money(r.delta)}</TableCell><TableCell>{r.included?'Se importará':'Se omitirá'}{r.duplicate&&<small className="excel-secondary">{r.duplicateReason}</small>}</TableCell></TableRow>)}</TableBody></Table><label className="excel-check"><Checkbox checked={consent} disabled={busy} onCheckedChange={v=>setConsent(v===true)}/>He revisado los datos ficticios, los importes y las coincidencias.</label><Button onClick={()=>void execute()} disabled={busy||!consent||!!preview.errors.length}>{busy?'Importando…':'Confirmar importación'}</Button></>}
 {result&&<div className="bank-success" role="status"><div><strong>{result.count} movimientos incorporados.</strong><p>Ya aparecen en el extracto y en el historial de la cuenta.</p><a href={companyUrl('/servicios/banco/justificante?id='+result.id)} target="_blank" rel="noreferrer">Abrir justificante del lote</a></div></div>}
 </section>;
}
