import {Table,TableHeader,TableRow,TableHead,TableBody,TableCell,TableFooter} from '@/components/ui/table';
import {socialDate,socialMoney,socialPeriod,socialTitle,type SocialDocument} from '@/lib/social-types';
export function DocumentDetails({document:d}:{document:SocialDocument}){
 const h=d.header,people=[...new Set(d.lines.map(r=>r.naf))];
 return <article className="ss-document"><div className="ss-document-title"><div><span>{d.kind}</span><h3>{socialTitle(d.kind)}</h3></div><p>{d.filename} · {d.pages} {d.pages===1?'página':'páginas'}</p></div>
  <dl className="ss-data"><div className="ss-wide"><dt>Razón social</dt><dd>{h.company}</dd></div><div><dt>Código cuenta de cotización</dt><dd>{h.ccc}</dd></div><div><dt>Periodo de liquidación</dt><dd>{socialPeriod(h.periodFrom)} – {socialPeriod(h.periodTo)}</dd></div><div><dt>Número de trabajadores</dt><dd>{h.workers}</dd></div><div><dt>Calificador de liquidación</dt><dd>{h.qualification}</dd></div><div><dt>Código de empresario</dt><dd>{h.employerId||'No figura en el PDF'}</dd></div><div><dt>Número de liquidación</dt><dd>{h.liquidationNumber||'No figura en el PDF'}</dd></div><div><dt>Fecha de control</dt><dd>{socialDate(h.controlDate)}</dd></div><div><dt>Liquidación</dt><dd>{h.scope}</dd></div><div><dt>Entidad AT/EP</dt><dd>{h.entity||'—'}</dd></div></dl>
  {d.kind==='RNT'?<><h4>Trabajadores y tramos</h4>{people.map((naf,index)=>{const rows=d.lines.filter(r=>r.naf===naf),person=rows[0];return <section className="ss-worker" key={naf}><div className="ss-worker-id"><strong>Trabajador {index+1}</strong><span><b>NAF:</b> {naf}</span><span><b>IPF:</b> {person.ipf}</span><span><b>CAF:</b> {person.caf||'—'}</span></div><Table><TableHeader><TableRow><TableHead>Desde</TableHead><TableHead>Hasta</TableHead><TableHead>Días</TableHead><TableHead>Horas</TableHead><TableHead>H. compl.</TableHead><TableHead>Base o compensación</TableHead><TableHead className="ss-number">Importe</TableHead></TableRow></TableHeader><TableBody>{rows.map((r,i)=><TableRow key={i}><TableCell className="ss-nowrap">{socialDate(r.from)}</TableCell><TableCell className="ss-nowrap">{socialDate(r.to)}</TableCell><TableCell>{r.days}</TableCell><TableCell>{r.hours||'—'}</TableCell><TableCell>{r.extraHours||'—'}</TableCell><TableCell>{r.description}</TableCell><TableCell className="ss-number">{socialMoney(r.amount)}</TableCell></TableRow>)}</TableBody></Table></section>;})}<h4>Totales de bases y compensaciones</h4><Table><TableHeader><TableRow><TableHead>Concepto</TableHead><TableHead className="ss-number">Importe</TableHead></TableRow></TableHeader><TableBody>{d.amounts.map((r,i)=><TableRow key={i}><TableCell>{r.description}</TableCell><TableCell className="ss-number">{socialMoney(r.amount)}</TableCell></TableRow>)}</TableBody></Table></>:<><h4>Detalle de cotizaciones</h4><Table><TableHeader><TableRow><TableHead>Descripción</TableHead><TableHead className="ss-number">Base</TableHead><TableHead className="ss-number">Importe</TableHead></TableRow></TableHeader><TableBody>{d.amounts.slice(0,-1).map((r,i)=><TableRow key={i} className={r.description.startsWith('Líquido')?'ss-subtotal':''}><TableCell>{r.description}</TableCell><TableCell className="ss-number">{r.base===null?'—':socialMoney(r.base)}</TableCell><TableCell className="ss-number">{socialMoney(r.amount)}</TableCell></TableRow>)}</TableBody><TableFooter><TableRow><TableCell colSpan={2}>Líquido de totales</TableCell><TableCell className="ss-number">{socialMoney(d.total!)}</TableCell></TableRow></TableFooter></Table></>}
 </article>;
}
