'use client';
import {companyFetch,companyUrl,clientCompany} from '@/lib/company-client';

import {useEffect,useRef,useState,type FormEvent} from 'react';
import {CheckCircle2,FileCheck2,Loader2} from 'lucide-react';
import {Button} from '@/components/ui/button';
import {Checkbox} from '@/components/ui/checkbox';
import {Input} from '@/components/ui/input';
import SocialHeader,{SocialFooter} from './sede-header';
import {registryModels,registryNames,registryReceiptUrl,socialRoot,type RegistryKind,type RegistryData,type RegistryPreview,type RegistryRecord} from '@/lib/social-registry-types';
import {registrySummary} from '@/lib/social-receipt-data';
import {ReceiptSections} from './receipt-sections';
import {newMailId} from '@/lib/mail-types';
type Option={id:string;kind:RegistryKind;title:string;number:string};
export default function RegistryForm({kind}:{kind:RegistryKind}){
 const [data,setData]=useState<RegistryData>({effectiveDate:'',documentType:'DNI',nationality:'Española',percent:'100',group:'7',...(kind==='company'?{name:clientCompany().name,nif:clientCompany().nif,ccc:clientCompany().ccc,activity:clientCompany().activity}:{})}),[options,setOptions]=useState<Option[]>([]),[optionsReady,setOptionsReady]=useState(false),[preview,setPreview]=useState<RegistryPreview|null>(null),[done,setDone]=useState<RegistryRecord|null>(null),[busy,setBusy]=useState(false),[error,setError]=useState(''),[conflict,setConflict]=useState(''),[consent,setConsent]=useState(false);
 const [ready,setReady]=useState(false);
 const id=useRef(''),lock=useRef(false),heading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{setData(d=>({...d,effectiveDate:new Date().toLocaleDateString('sv-SE',{timeZone:'Europe/Madrid'})}));setReady(true);},[]);
 useEffect(()=>{if(kind!=='employment')return;let active=true;companyFetch('/api/seguridad-social/registro?options=1',{cache:'no-store'}).then(async r=>{const d=await r.json() as {options:Option[];error?:string};if(!r.ok)throw Error(d.error);if(active){setOptions(d.options);setOptionsReady(true);}}).catch(e=>{if(active)setError(e.message||'No se pueden cargar las empresas y personas.');});return()=>{active=false;};},[kind]);
 useEffect(()=>{if(preview||done||error)heading.current?.focus();},[preview,done,error]);
 function change(key:string,value:string){setData(d=>({...d,[key]:value}));setError('');setConflict('');}
 const field=(key:string,label:string,opts:{type?:string;max?:number;optional?:boolean;hint?:string}={})=><label className="ss-form-field" key={key} htmlFor={'ss-'+key}><span>{label}{opts.optional&&<small> (opcional)</small>}</span><Input id={'ss-'+key} name={key} type={opts.type||'text'} required={!opts.optional} maxLength={opts.max||100} value={data[key]||''} onChange={e=>change(key,e.target.value)} onInput={opts.type==='date'?e=>change(key,e.currentTarget.value):undefined} {...(opts.type==='date'?{min:'1900-01-01',max:'2199-12-31'}:{})}/>{opts.hint&&<small>{opts.hint}</small>}</label>;
 async function submit(action:'preview'|'register'){if(lock.current)return;lock.current=true;setBusy(true);setError('');setConflict('');if(!id.current)id.current=newMailId();try{const r=await companyFetch('/api/seguridad-social/registro',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({action,kind,id:id.current,data,consent,fingerprint:preview?.fingerprint})}),d=await r.json() as RegistryPreview&{error?:string;recordId?:string};if(!r.ok){setConflict(d.recordId||'');throw Error(d.error||'No se ha podido completar el trámite.');}if(action==='preview'){setPreview(d);setConsent(false);}else{setDone(d.record);setPreview(null);}}catch(e){setError(e instanceof Error?e.message:'No se ha podido conectar. Vuelva a intentarlo.');}finally{lock.current=false;setBusy(false);}}
 function review(e:FormEvent){e.preventDefault();void submit('preview');}
 const companies=options.filter(o=>o.kind==='company'),people=options.filter(o=>o.kind==='person');
 return <div className="social-app"><SocialHeader active={kind}/><main className="ss-shell"><nav className="ss-breadcrumb" aria-label="Ruta de navegación"><a href={companyUrl(socialRoot)}>Inicio</a><span>/</span><span>Afiliación e inscripción</span><span>/</span><strong>{registryModels[kind]}</strong></nav><div className="ss-heading"><div><h1 ref={heading} tabIndex={-1}>{done?'Solicitud registrada':registryNames[kind]}</h1><p>{kind==='company'?'Identificación de la empresa y CCC inicial':kind==='person'?'Datos de la persona y número de Seguridad Social':'Comunicación del inicio de la actividad laboral'}</p></div><span className="ss-model-badge">{registryModels[kind]}</span></div>
 <div className="ss-form-container">{!done&&<ol className="ss-steps" aria-label="Pasos del trámite"><li className={!preview?'ss-active':''} aria-current={!preview?'step':undefined}><span>1</span>Datos de la solicitud</li><li className={preview?'ss-active':''} aria-current={preview?'step':undefined}><span>2</span>Revisión y confirmación</li><li><span>3</span>Justificante</li></ol>}
 {error&&<div className="ss-error" role="alert">{error}{conflict&&<p><a href={companyUrl(registryReceiptUrl(conflict))}>Consultar el registro existente</a></p>}</div>}
 {done?<section className="ss-result"><CheckCircle2 size={34}/><h2>El trámite se ha completado</h2><p>{done.title}</p><dl className="ss-data"><div className="ss-wide"><dt>Referencia</dt><dd>{done.reference}</dd></div><div><dt>{kind==='company'?'CCC':'Número de Seguridad Social'}</dt><dd>{done.number}</dd></div></dl><div className="ss-actions"><Button asChild><a href={companyUrl(registryReceiptUrl(done.id))}><FileCheck2 size={18}/>Obtener justificante</a></Button><Button variant="outline" asChild><a href={companyUrl(kind==='company'?socialRoot+'/afiliacion':kind==='person'?socialRoot+'/altas':socialRoot+'/registros')}>{kind==='company'?'Afiliar a una persona':kind==='person'?'Dar de alta en una empresa':'Consultar expedientes'}</a></Button><Button variant="outline" onClick={()=>{setDone(null);id.current='';setConsent(false);setData(d=>({effectiveDate:d.effectiveDate,documentType:'DNI',nationality:'Española',percent:'100',group:'7'}));}}>Nueva solicitud</Button></div></section>:preview?<section><h2>Compruebe los datos de la solicitud</h2><ReceiptSections sections={registrySummary(preview.record).sections}/>{preview.record.data.numberAssigned==='yes'&&<p className="ss-info-line">Se asignará el {kind==='company'?'CCC':'número de Seguridad Social'} mostrado al confirmar la solicitud.</p>}<label className="ss-check ss-registry-confirm"><Checkbox checked={consent} disabled={busy} onCheckedChange={v=>setConsent(v===true)}/><span>Conforme: he revisado los datos y confirmo la solicitud.</span></label><div className="ss-actions"><Button disabled={busy||!consent} onClick={()=>void submit('register')}>{busy?<Loader2 size={18} className="ss-spin"/>:<FileCheck2 size={18}/>}Confirmar y registrar</Button><Button variant="outline" disabled={busy} onClick={()=>{setPreview(null);setConsent(false);setError('');}}>Corregir datos</Button></div></section>:<form onSubmit={review}><fieldset disabled={busy||!ready} className="ss-form-body">
 {kind==='company'&&<><section><h2>1. Identificación de la empresa</h2><div className="ss-form-grid">{field('name','Nombre o razón social')}{field('nif','NIF',{max:9})}{field('representative','Representante',{optional:true})}{field('effectiveDate','Fecha de inicio de actividad',{type:'date'})}</div></section><section><h2>2. Domicilio de la actividad</h2><div className="ss-form-grid">{field('address','Domicilio',{max:120})}{field('postcode','Código postal',{max:5})}{field('city','Municipio',{max:60})}{field('province','Provincia',{max:40})}</div></section><section><h2>3. Actividad y cotización</h2><div className="ss-form-grid">{field('activity','Actividad económica')}{field('cnae','Código CNAE',{max:4,hint:'Código de 4 dígitos del supuesto.'})}<div className="ss-form-field"><span>Régimen</span><p className="ss-readonly">0111 · Régimen General</p></div>{field('entity','Mutua o entidad de cobertura',{max:80})}{field('ccc','Código cuenta de cotización',{optional:true,max:15,hint:'11 dígitos. Si se deja vacío, se asignará uno de prácticas.'})}</div></section></>}
 {kind==='person'&&<><section><h2>1. Datos personales</h2><div className="ss-form-grid">{field('firstName','Nombre',{max:50})}{field('lastName','Primer apellido',{max:50})}{field('secondName','Segundo apellido',{max:50,optional:true})}{field('birthDate','Fecha de nacimiento',{type:'date'})}<label className="ss-form-field"><span>Tipo de documento</span><select value={data.documentType} onChange={e=>change('documentType',e.target.value)}><option>DNI</option><option>NIE</option><option>Pasaporte</option></select></label>{field('personId','Número de documento',{max:20})}{field('nationality','Nacionalidad',{max:40})}</div></section><section><h2>2. Domicilio</h2><div className="ss-form-grid">{field('address','Domicilio',{max:120})}{field('postcode','Código postal',{max:5})}{field('city','Municipio',{max:60})}{field('province','Provincia',{max:40})}</div></section><section><h2>3. Solicitud de afiliación</h2><div className="ss-form-grid">{field('effectiveDate','Fecha de solicitud',{type:'date'})}{field('nss','Número de Seguridad Social',{max:16,optional:true,hint:'12 dígitos. Déjelo vacío para solicitar un número de prácticas.'})}</div></section></>}
 {kind==='employment'&&<><section><h2>1. Empresa y trabajador</h2>{!optionsReady?<p role="status">Cargando empresas y personas…</p>:(!companies.length||!people.length)&&<p className="ss-info-line">Para tramitar un alta, primero debe <a href={companyUrl(socialRoot+'/empresas')}>inscribir una empresa</a> y <a href={companyUrl(socialRoot+'/afiliacion')}>afiliar a la persona</a>.</p>}<div className="ss-form-grid"><label className="ss-form-field"><span>Empresa / CCC</span><select required value={data.companyId||''} onChange={e=>change('companyId',e.target.value)}><option value="">Seleccione una empresa</option>{companies.map(o=><option key={o.id} value={o.id}>{o.title} · {o.number}</option>)}</select></label><label className="ss-form-field"><span>Trabajador / NSS</span><select required value={data.personId||''} onChange={e=>change('personId',e.target.value)}><option value="">Seleccione una persona</option>{people.map(o=><option key={o.id} value={o.id}>{o.title} · {o.number}</option>)}</select></label></div></section><section><h2>2. Datos del alta</h2><div className="ss-form-grid">{field('effectiveDate','Fecha de alta',{type:'date'})}{field('contract','Código de contrato',{max:3,hint:'Código de 3 dígitos indicado en el contrato.'})}{field('occupation','Puesto de trabajo',{max:80})}<label className="ss-form-field"><span>Grupo de cotización</span><select value={data.group} onChange={e=>change('group',e.target.value)}>{Array.from({length:11},(_,i)=><option key={i} value={i+1}>Grupo {i+1}</option>)}</select></label>{field('percent','Jornada (%)',{max:6,hint:'100 para jornada completa; use punto para decimales.'})}</div></section></>}
 <div className="ss-actions"><Button type="submit" disabled={busy||(kind==='employment'&&(!companies.length||!people.length))}>{busy?<Loader2 size={18} className="ss-spin"/>:<FileCheck2 size={18}/>}Continuar y revisar</Button><Button variant="outline" asChild><a href={companyUrl(socialRoot)}>Volver a servicios</a></Button></div></fieldset></form>}
 </div><SocialFooter/></main></div>;
}
