'use client';
import {companyUrl,clientCompany} from '@/lib/company-client';
import {House,ShieldCheck,FolderOpen,Building2,UsersRound,BriefcaseBusiness,Monitor,Files} from 'lucide-react';
import {socialRoot} from '@/lib/social-registry-types';
export function SocialNotice(){return <div className="ss-training"><ShieldCheck size={15} aria-hidden="true"/><strong>SIMULACIÓN EDUCATIVA</strong><span>Sin validez administrativa</span></div>;}
export function SocialBrand(){return <div className="ss-brand"><img className="ss-ministry" src="./ss-ministerio.svg" width="260" height="60" alt="Gobierno de España · Ministerio de Inclusión, Seguridad Social y Migraciones"/><img className="ss-sede-logo" src="./seguridad-social.svg" width="262" height="44" alt="Seguridad Social · Sede electrónica"/></div>;}
const navigation=[{path:'',key:'inicio',label:'Inicio',Icon:House},{path:'/empresas',key:'company',label:'Empresas',Icon:Building2},{path:'/afiliacion',key:'person',label:'Afiliación',Icon:UsersRound},{path:'/altas',key:'employment',label:'Altas de trabajadores',Icon:BriefcaseBusiness},{path:'/sistema-red',key:'red',label:'Sistema RED',Icon:Monitor},{path:'/cotizacion',key:'cotizacion',label:'Cotización',Icon:Files}];
export default function SocialHeader({active='cotizacion'}:{active?:string}){return <><a className="ss-skip" href="#contenido-social">Saltar al contenido</a><div className="ss-return"><a href={companyUrl('/')}>Servicios de la práctica</a><span>{clientCompany().name}</span></div><SocialNotice/><header className="ss-header"><a href={companyUrl(socialRoot)} aria-label="Inicio de la sede de Seguridad Social"><SocialBrand/></a><div className="ss-header-tools"><span>Castellano · Área de empresa</span><a href={companyUrl(socialRoot+'/registros')}><FolderOpen size={17} aria-hidden="true"/>Consulta de expedientes</a></div></header><nav className="ss-main-nav" aria-label="Servicios de la sede"><div>{navigation.map(({path,key,label,Icon})=><a key={key} href={companyUrl(socialRoot+path)} aria-current={active===key?'page':undefined}><Icon size={34} strokeWidth={1.35} aria-hidden="true"/><span>{label}</span></a>)}</div></nav></>;}
export function SocialFooter(){return <footer className="ss-footer">Tesorería General de la Seguridad Social · Simulación educativa de {clientCompany().shortName}</footer>;}
