'use client';
import {companyFetch,shouldRefresh,companyUrl,clientCompany} from '@/lib/company-client';

import {useCallback,useEffect,useRef,useState,type FormEvent} from 'react';
import {CheckCircle2,HelpCircle,Loader2,Search,FileCheck2} from 'lucide-react';
import {DeleteRecord,clearTaxPractice} from '@/components/practice/delete-record';
import {Button} from '@/components/ui/button';
import {Input} from '@/components/ui/input';
import {Checkbox} from '@/components/ui/checkbox';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {Alert,AlertTitle,AlertDescription} from '@/components/ui/alert';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Table,TableBody,TableCell,TableHead,TableHeader,TableRow} from '@/components/ui/table';
import {socialDate,socialMoney,socialPeriod,type SocialBatch,type SocialPreview,type SocialReceipt} from '@/lib/social-types';
import SocialHeader from './sede-header';
import {DocumentDetails} from './document-details';
import {newMailId} from '@/lib/mail-types';
type Upload={filename:string;file:string};
type History={batches:SocialBatch[];total:number;page:number;pageSize:number};
export const socialReceiptUrl=(id:string)=>'/servicios/seguridad-social/justificante?'+new URLSearchParams({id});
async function post<T>(p:unknown):Promise<T>{const r=await companyFetch('/api/seguridad-social',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(p)});const d=await r.json() as T&{error?:string;batchId?:string};if(!r.ok)throw Object.assign(Error(d.error||'No se ha podido completar el trámite.'),{batchId:d.batchId});return d;}
export default function SocialWorkspace(){
 const [tab,setTab]=useState('submit'),[help,setHelp]=useState(false),[preview,setPreview]=useState<SocialPreview|null>(null),[files,setFiles]=useState<Upload[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(''),[conflict,setConflict]=useState(''),[consent,setConsent]=useState(false),[warningsAccepted,setWarningsAccepted]=useState(false),[date,setDate]=useState(''),[done,setDone]=useState<SocialReceipt|null>(null);
 const [history,setHistory]=useState<History|null>(null),[historyBusy,setHistoryBusy]=useState(false),[historyError,setHistoryError]=useState(''),[query,setQuery]=useState(''),[period,setPeriod]=useState(''),[filter,setFilter]=useState({q:'',period:'',page:0});
 const input=useRef<HTMLInputElement>(null),busyRef=useRef(false),id=useRef(''),generation=useRef(0),heading=useRef<HTMLHeadingElement>(null);
 useEffect(()=>{setDate(new Date().toLocaleDateString('sv-SE',{timeZone:'Europe/Madrid'}));},[]);
 useEffect(()=>{if(preview||done)heading.current?.focus();},[preview,done]);
 const load=useCallback(async()=>{const n=++generation.current;setHistoryBusy(true);setHistoryError('');try{const r=await companyFetch('/api/seguridad-social?'+new URLSearchParams({...filter,page:String(filter.page)}),{cache:'no-store'}),d=await r.json() as History&{error?:string};if(!r.ok)throw Error(d.error);if(n===generation.current)setHistory(d);}catch(e){if(n===generation.current)setHistoryError(e instanceof Error?e.message:'No se pueden consultar los documentos.');}finally{if(n===generation.current)setHistoryBusy(false);}},[filter]);
 useEffect(()=>{if(tab!=='history')return;void load();const refresh=()=>{if(shouldRefresh())void load();};const timer=setInterval(refresh,120000);window.addEventListener('focus',refresh);window.addEventListener('social-payment-changed',refresh);return()=>{clearInterval(timer);window.removeEventListener('focus',refresh);window.removeEventListener('social-payment-changed',refresh);generation.current++;};},[tab,load]);
 function reset(){setPreview(null);setFiles([]);setDone(null);setError('');setConflict('');setConsent(false);setWarningsAccepted(false);id.current='';if(input.current)input.current.value='';}
 async function inspect(selected:File[]){if(!selected.length||busyRef.current)return;reset();if(selected.length>2||selected.some(f=>! /\.pdf$/i.test(f.name)||!f.size||f.size>5*1024*1024)){setError('Seleccione uno o dos PDF, de hasta 5 MB cada uno.');return;}busyRef.current=true;setBusy(true);try{const uploaded:Upload[]=[];for(const f of selected){const bytes=new Uint8Array(await f.arrayBuffer());let text='';for(let i=0;i<bytes.length;i+=8192)text+=String.fromCharCode(...bytes.subarray(i,i+8192));uploaded.push({filename:f.name,file:btoa(text)});}const d=await post<SocialPreview>({action:'preview',files:uploaded});setFiles(uploaded);setPreview(d);id.current=newMailId();}catch(e){setError(e instanceof Error?e.message:'No se han podido leer los PDF.');}finally{setBusy(false);busyRef.current=false;}}
 async function register(){if(!preview||busyRef.current)return;busyRef.current=true;setBusy(true);setError('');setConflict('');try{const r=await post<SocialReceipt>({action:'register',files,id:id.current,fingerprint:preview.fingerprint,submissionDate:date,consent,warningsAccepted});setDone(r);setPreview(null);setFiles([]);setConsent(false);}catch(e){setError(e instanceof Error?e.message:'No se ha podido presentar.');if(e&&typeof e==='object'&&'batchId'in e)setConflict(String(e.batchId));}finally{setBusy(false);busyRef.current=false;}}
 function search(e:FormEvent){e.preventDefault();setFilter({q:query,period,page:0});}
 return <div className="social-app"><SocialHeader/><div className="ss-shell"><nav className="ss-breadcrumb" aria-label="Ruta de navegación"><a href={companyUrl("/servicios/seguridad-social")}>Inicio</a><span>/</span><span>Empresas</span><span>/</span><span>Sistema RED</span><span>/</span><strong>Cotización</strong></nav><div className="ss-heading"><div><h1>Cotización y recaudación</h1><p>Documentos de liquidación</p></div><Button variant="ghost" onClick={()=>setHelp(true)}><HelpCircle size={18}/>Ayuda</Button></div><div className="ss-company"><strong>{clientCompany().name}</strong><span>Área de empresa</span></div>
 <Tabs value={tab} onValueChange={setTab} className="ss-tabs"><TabsList><TabsTrigger value="submit">Presentación de documentos</TabsTrigger><TabsTrigger value="history">Consulta de presentaciones</TabsTrigger></TabsList>
 <TabsContent value="submit"><main className="ss-main">
 {done?<section className="ss-result"><CheckCircle2 size={32}/><h2 ref={heading} tabIndex={-1}>Presentación registrada</h2><p>Los documentos se han incorporado al expediente.</p><dl className="ss-data"><div className="ss-wide"><dt>Referencia</dt><dd>{done.batch.reference}</dd></div><div><dt>Documentos</dt><dd>{done.batch.kinds}</dd></div><div><dt>Fecha de presentación</dt><dd>{socialDate(done.batch.submissionDate)}</dd></div><div><dt>CCC</dt><dd>{done.batch.ccc}</dd></div><div><dt>Periodo</dt><dd>{socialPeriod(done.batch.periodFrom)} – {socialPeriod(done.batch.periodTo)}</dd></div></dl><div className="ss-actions"><Button asChild><a href={companyUrl(socialReceiptUrl(done.batch.id))}><FileCheck2 size={18}/>Obtener justificante</a></Button><Button variant="outline" onClick={reset}>Nueva presentación</Button></div></section>:<>
 <ol className="ss-steps" aria-label="Pasos de la presentación"><li className={!preview?'ss-active':''} aria-current={!preview?'step':undefined}><span>1</span>Seleccionar documentos</li><li className={preview?'ss-active':''} aria-current={preview?'step':undefined}><span>2</span>Revisar datos</li><li><span>3</span>Confirmar presentación</li></ol>
 {error&&<Alert variant="destructive" className="ss-error"><AlertTitle>No se ha completado la presentación</AlertTitle><AlertDescription>{error}{conflict&&<a href={companyUrl(socialReceiptUrl(conflict))}>Consultar la presentación existente</a>}</AlertDescription></Alert>}
 <input hidden ref={input} type="file" accept=".pdf,application/pdf" multiple disabled={busy} aria-label="PDF de cotización" onChange={e=>void inspect(Array.from(e.target.files||[]))}/>
 {!preview?<section className="ss-upload"><h2>Incorporar documentos de cotización</h2><p>Seleccione los PDF de la relación nominal de trabajadores y de la liquidación de cotizaciones.</p><fieldset disabled={busy} onDragOver={e=>e.preventDefault()} onDrop={e=>{e.preventDefault();void inspect(Array.from(e.dataTransfer.files));}}><legend>Documentos</legend><div className="ss-file-row"><div><strong>{busy?'Leyendo documentos…':'RNT / Liquidación de cotizaciones'}</strong><span>Puede seleccionar ambos archivos o presentarlos por separado.</span></div><Button variant="outline" disabled={busy} onClick={()=>input.current?.click()}>{busy?<Loader2 className="ss-spin" size={18}/>:null}Seleccionar PDF</Button></div><p>PDF original con texto seleccionable · Hasta 5 MB por archivo · Máximo 30 páginas.</p></fieldset><p className="ss-upload-note">Después de la lectura, compruebe los datos extraídos y confirme la presentación.</p><button className="ss-text-button" onClick={()=>setHelp(true)}>Formatos admitidos e instrucciones</button></section>:<section className="ss-review"><div className="ss-review-heading"><div><h2 tabIndex={-1} ref={heading}>Comprobación de datos</h2><p>{preview.documents.length} {preview.documents.length===1?'documento leído':'documentos leídos'} · {preview.documents[0].header.workers} trabajadores</p></div><Button variant="outline" disabled={busy} onClick={()=>input.current?.click()}>Cambiar documentos</Button></div><p>Revise la información. Si detecta un error, corrija el documento en el programa de nóminas y vuelva a importarlo.</p>
 {preview.duplicates.length>0&&<Alert variant="destructive" className="ss-error"><AlertTitle>Documento ya presentado</AlertTitle><AlertDescription><p>No se puede duplicar una presentación de la misma liquidación.</p>{preview.duplicates.map((d,i)=><a key={i} href={companyUrl(socialReceiptUrl(d.batchId))}>{d.kind} · {d.reference}</a>)}</AlertDescription></Alert>}
 {preview.warnings.length>0&&<Alert className="ss-warning"><AlertTitle>Observaciones del documento</AlertTitle><AlertDescription><ul>{preview.warnings.map(w=><li key={w}>{w}</li>)}</ul></AlertDescription></Alert>}
 {preview.documents.map(d=><DocumentDetails key={d.kind} document={d}/>)}
 <fieldset className="ss-confirm" disabled={busy||preview.duplicates.length>0}><legend>Confirmación de la presentación</legend><label className="ss-date-label" htmlFor="ss-date">Fecha de presentación<Input id="ss-date" type="date" min="1900-01-01" max="2199-12-31" value={date} onChange={e=>setDate(e.target.value)}/></label><label className="ss-check"><Checkbox checked={consent} onCheckedChange={v=>setConsent(v===true)}/><span>He comprobado los datos de los documentos y confirmo su presentación.</span></label>{preview.warnings.length>0&&<label className="ss-check"><Checkbox checked={warningsAccepted} onCheckedChange={v=>setWarningsAccepted(v===true)}/><span>He revisado las observaciones y los datos corresponden al supuesto de trabajo.</span></label>}<div className="ss-actions"><Button disabled={busy||!consent||!date||preview.duplicates.length>0||(preview.warnings.length>0&&!warningsAccepted)} onClick={()=>void register()}>{busy?<Loader2 className="ss-spin" size={18}/>:<FileCheck2 size={18}/>}Confirmar presentación</Button><Button variant="outline" onClick={reset} disabled={busy}>Cancelar</Button></div></fieldset>
 </section>}
 </>}
 </main></TabsContent>
 <TabsContent value="history"><main className="ss-main"><div className="ss-review-heading"><h2>Consulta de presentaciones</h2><Button variant="outline" onClick={()=>void load()} disabled={historyBusy}>Actualizar</Button></div><div className="practice-actions"><DeleteRecord scope="social" title="Todas las presentaciones de cotización" label="Borrar presentaciones" onDeleted={()=>{reset();setTab("history");setFilter(f=>({...f,page:0}));void load();}}/><a href={companyUrl("/practicas")}>Gestión de prácticas</a></div><form className="ss-search" onSubmit={search}><label>Referencia, razón social, CCC o documento<Input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Buscar presentaciones"/></label><label>Periodo de cotización<Input type="month" value={period} onChange={e=>setPeriod(e.target.value)}/></label><Button type="submit"><Search size={16}/>Buscar</Button></form>{historyError&&<Alert variant="destructive"><AlertDescription>{historyError}</AlertDescription></Alert>}<div aria-live="polite">{historyBusy?<p className="ss-loading">Consultando documentos…</p>:history&&!history.total?<div className="ss-empty"><h3>No hay presentaciones{filter.q||filter.period?' con estos filtros':''}</h3><p>Los documentos confirmados aparecerán en esta consulta.</p></div>:history&&<><p className="ss-count">{history.total} {history.total===1?'presentación':'presentaciones'}</p><Table><TableHeader><TableRow><TableHead>Referencia / Documentos</TableHead><TableHead>Empresa / CCC</TableHead><TableHead>Periodo</TableHead><TableHead>Presentación</TableHead><TableHead className="ss-number">Liquidación</TableHead><TableHead>Justificante</TableHead></TableRow></TableHeader><TableBody>{history.batches.map(b=><TableRow key={b.id}><TableCell><strong className="ss-ref">{b.reference}</strong><span className="ss-cell-sub">{b.kinds}</span></TableCell><TableCell>{b.company}<span className="ss-cell-sub">{b.ccc}</span></TableCell><TableCell className="ss-nowrap">{socialPeriod(b.periodFrom)}{b.periodFrom!==b.periodTo&&' – '+socialPeriod(b.periodTo)}</TableCell><TableCell className="ss-nowrap">{socialDate(b.submissionDate)}</TableCell><TableCell className="ss-number">{b.total===null?'—':socialMoney(b.total)}</TableCell><TableCell><a href={companyUrl(socialReceiptUrl(b.id))}>Consultar</a><DeleteRecord scope="social" id={b.id} title={b.reference} onDeleted={()=>{reset();setTab("history");setFilter(f=>({...f,page:0}));void load();}}/></TableCell></TableRow>)}</TableBody></Table><div className="ss-pagination"><Button variant="outline" disabled={!filter.page||historyBusy} onClick={()=>setFilter({...filter,page:filter.page-1})}>Anterior</Button><span>Página {history.page+1} de {Math.ceil(history.total/history.pageSize)}</span><Button variant="outline" disabled={(filter.page+1)*history.pageSize>=history.total||historyBusy} onClick={()=>setFilter({...filter,page:filter.page+1})}>Siguiente</Button></div></>}</div></main></TabsContent>
 </Tabs><footer className="ss-footer">Tesorería General de la Seguridad Social · Entorno de simulación educativa</footer></div>
 <Dialog open={help} onOpenChange={setHelp}><DialogContent className="ss-help"><DialogTitle>Cotización · Instrucciones</DialogTitle><DialogDescription>Importación y consulta de documentos</DialogDescription><h3>Preparar los archivos</h3><p>Exporte desde NominaSOL la relación nominal de trabajadores (RNT) y la liquidación de cotizaciones. Se admite la distribución de los PDF educativos aportados: RNT horizontal y liquidación vertical de una página. Otras versiones pueden variar.</p><h3>Revisar y presentar</h3><p>Seleccione uno o ambos PDF. Se leen la cabecera, los trabajadores, los tramos y los conceptos. Se comprueban fechas, número de trabajadores y sumas. Cuando hay RNT y liquidación de un mismo expediente, también se contrastan sus datos.</p><p>La presentación conserva los documentos originales y un justificante. La consulta es compartida por todas las personas que acceden a {clientCompany().shortName}. Utilice únicamente datos ficticios.</p><h3>Alcance de esta sede</h3><p>La importación de PDF es una adaptación para la simulación; no reproduce el intercambio técnico real con el Sistema de Liquidación Directa. No recalcula cuotas legales ni comprueba todos los formatos oficiales.</p><p>Compruebe la razón social y el CCC del supuesto antes de presentar y pagar. No se consulta ningún registro oficial de empresas.</p><p>Las inscripciones de empresas, afiliaciones y altas de trabajadores se realizan desde sus apartados de la sede. Los pagos de cuotas se realizan desde el expediente o desde Nexo, apartado Cotizaciones, después de presentar el RLC. Las bajas y variaciones todavía no están disponibles.</p></DialogContent></Dialog>
 </div>;
}
