import {clientCompany,companyUrl} from '@/lib/company-client';
import {DeleteRecord} from '@/components/practice/delete-record';
import {practiceStorage as localStorage} from '@/lib/local/storage';
"use client";
import {useEffect,useState} from 'react';
import {Button} from '@/components/ui/button';
import {Select,SelectContent,SelectItem,SelectTrigger,SelectValue} from '@/components/ui/select';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Checkbox} from '@/components/ui/checkbox';
import {Switch} from '@/components/ui/switch';
import {Tabs,TabsList,TabsTrigger,TabsContent} from '@/components/ui/tabs';
import {DropdownMenu,DropdownMenuTrigger,DropdownMenuContent,DropdownMenuItem} from '@/components/ui/dropdown-menu';
import {Table,TableHeader,TableHead,TableBody,TableRow,TableCell} from '@/components/ui/table';
import {AlertDialog,AlertDialogContent,AlertDialogTitle,AlertDialogDescription,AlertDialogAction,AlertDialogCancel,AlertDialogFooter} from '@/components/ui/alert-dialog';
import {Toaster,toast} from 'sonner';
import {UserRound,Search,Info,SquarePen,FileText,Save,FolderOpen,CheckCheck,KeyRound,ShieldCheck,HelpCircle,LogOut,CheckCircle2,Trash2} from 'lucide-react';
import {settlement,rectificationFrom,officialHelp,retentionColumns,periodOptions,identificationQuestions,canRefund,validPracticeIBAN,normalizeIBAN,names,shortNames,groups111,vatRows,otherVat,deductions,blank,calculate,validate,money,fieldLabels,type Model,type Declaration,type Receipt} from '@/lib/tributaria/tax';
import ReportWorkspace from '@/components/tributaria/report-workspace';
import {reportModels,reportNames,type ReportModel} from '@/lib/tributaria/reports';
import {downloadPDF} from '@/lib/tributaria/receipt';
const simulationId=()=>Array.from(crypto.getRandomValues(new Uint8Array(16)),b=>b.toString(16).padStart(2,'0')).join('');
const models:Model[]=['303','111','115'];
function Choice({label,value,onChange,options}:{label:string;value:string;onChange:(v:string)=>void;options:{value:string;label:string}[]}){return <div className="field"><span className="field-label">{label}</span><Select value={value} onValueChange={onChange}><SelectTrigger aria-label={label}><SelectValue/></SelectTrigger><SelectContent>{options.map(o=><SelectItem key={o.value} value={o.value}>{o.label}</SelectItem>)}</SelectContent></Select></div>}
function Section({title,children}:{title:string;children:React.ReactNode}){return <section className="tax-section"><h2><span>{title}</span></h2><div className="section-body">{children}</div></section>}
function TextInput({label,value,onChange,...rest}:{label:string;value:string;onChange:(v:string)=>void;maxLength?:number;placeholder?:string;readOnly?:boolean}){return <label className="field"><span className="field-label">{label}</span><input value={value} onChange={e=>onChange(e.target.value)} {...rest}/></label>}
function methodLabel(v:string){return ({domiciliacion:'Domiciliación del importe a ingresar',ingresar:'A ingresar con NRC',deuda:'Reconocimiento de deuda',rectificar:'Rectificación de la autoliquidación anterior',compensar:'A compensar',devolver:'Solicitud de devolución',negativa:'Resultado cero / negativa'} as Record<string,string>)[v]||v;}
export default function Home(){
const certs=[{company:clientCompany().name,nif:clientCompany().nif},{company:'OTRA EMPRESA SIMULADA',nif:'SIM000003'}];
const [view,setView]=useState<'portal'|'procedure'|'access'|'form'|'receipt'|'history'|'report'>('portal');
const [reportModel,setReportModel]=useState<ReportModel>('190'),[reportHistory,setReportHistory]=useState(false);
const openReport=(m:ReportModel,h=false)=>{setReportModel(m);setReportHistory(h);setView('report');window.scrollTo(0,0);};
const [model,setModel]=useState<Model>('303'),[d,setD]=useState<Declaration>(blank('303'));
const [certificate,setCertificate]=useState(0),[certOpen,setCertOpen]=useState(false),[help,setHelp]=useState(false);
const [initial115,setInitial115]=useState(false),[presenter111,setPresenter111]=useState(false);
const [payment,setPayment]=useState(false),[sign,setSign]=useState(false),[conform,setConform]=useState(false);
const [method,setMethod]=useState('domiciliacion'),[nrc,setNrc]=useState(''),[payErrors,setPayErrors]=useState<string[]>([]);
const [receipt,setReceipt]=useState<Receipt|null>(null),[history,setHistory]=useState<Receipt[]>([]);
const [errors,setErrors]=useState<string[]|null>(null),[part,setPart]=useState('identificacion'),[clear,setClear]=useState(false);
const [search,setSearch]=useState(''),[clock,setClock]=useState('');
const calc=calculate(d),labels=fieldLabels(d.model),allocation=settlement(d,method);
const needsBank=['domiciliacion','devolver'].includes(method)||allocation.correction>0;
const rectify=(r:Receipt)=>{setD(rectificationFrom(r));setModel('303');setErrors(null);setPart('resultado');go('form');toast.info('Revise las casillas del periodo completo y los importes anteriores antes de presentar.');};
useEffect(()=>{setClock(new Date().toLocaleString('es-ES',{timeZone:'Europe/Madrid'}));try{const a=JSON.parse(localStorage.getItem('aula-presentaciones-v1')||'[]');if(Array.isArray(a))setHistory(a.filter(x=>x?.declaration&&models.includes(x.declaration.model)&&typeof x.id==='string'));}catch{}},[]);
const update=(key:keyof Declaration,value:unknown)=>{setD(old=>({...old,[key]:value}));setErrors(null);};
const value=(key:string,v:string)=>{setD(old=>({...old,values:{...old.values,[key]:v}}));setErrors(null);};
const go=(v:typeof view)=>{setView(v);window.scrollTo(0,0);};
const choose=(m:Model)=>{setModel(m);go('procedure');};
const start=()=>{setD(blank(model,certs[certificate].company,certs[certificate].nif));setErrors(null);setPart('identificacion');setCertOpen(false);if(model==='115'){setInitial115(true);}else if(model==='111'){setPresenter111(true);}else go('form');};
const save=()=>{try{localStorage.setItem('aula-borrador-'+d.model,JSON.stringify(d));toast.success('Borrador guardado en este navegador.');}catch{toast.error('No se ha podido guardar. Descargue el borrador en PDF.');}};
const loadDraft=()=>{try{const a=JSON.parse(localStorage.getItem('aula-borrador-'+model)||'null');if(!a||a.model!==model||!a.values||typeof a.company!=='string'){toast.info('No hay un borrador guardado de este modelo en este navegador.');return;}setInitial115(false);setD({...blank(model),...a});setErrors(null);setPart('identificacion');go('form');toast.success('Borrador recuperado.');}catch{toast.error('No se ha podido recuperar el borrador.');}};
const check=()=>{const e=validate(d);setErrors(e);return e.length===0;};
const formalize=()=>{if(!check())return;setMethod(calc.result>0?'domiciliacion':calc.result<0?(settlement(d,'compensar').credit>0?'compensar':'rectificar'):'negativa');setNrc('');setPayErrors([]);setPayment(true);};
const prepareSign=()=>{if(method==='compensar'&&allocation.credit>0&&(calc.values['78']||0)>0){setPayErrors(['No se puede consignar un importe a compensar en la casilla 72 si se han aplicado cuotas en la casilla 78. Revise el resultado.']);return;}if(needsBank&&!validPracticeIBAN(d.iban||'')){setPayErrors(['Indique un IBAN de prácticas con formato español: ES y 22 cifras.']);return;}if(method==='ingresar'&&!nrc){setPayErrors(['Obtenga primero el NRC mediante Realizar pago.']);return;}setPayment(false);setConform(false);setSign(true);};
const send=()=>{if(!conform||validate(d).length)return;const r:Receipt={id:'SIM-'+d.model+'-'+simulationId().slice(0,8).toUpperCase(),csv:'SIM-'+simulationId().slice(0,18).toUpperCase(),date:new Date().toISOString(),declaration:JSON.parse(JSON.stringify(d)),method:methodLabel(method),bank:needsBank?normalizeIBAN(d.iban||''):'',nrc,result:calc.result,certificate:certs[certificate].company+' · Certificado de prácticas'};const next=[r,...history];setReceipt(r);setHistory(next);try{localStorage.setItem('aula-presentaciones-v1',JSON.stringify(next));}catch{toast.info('Descargue el justificante: este navegador no permite guardar el historial.');}setSign(false);go('receipt');};
const cell=(code:string,ro=false,integer=false)=><div className={'number-field '+(ro?'calculated':'')}><span className="mobile-field-label" aria-hidden="true">{labels[code]||'Importe'}</span><span className="box-code">[{code}]</span><input aria-label={`Casilla ${code}: ${labels[code]||'Importe'}`} inputMode={integer?'numeric':'decimal'} autoComplete="off" placeholder={integer?'0':'0,00'} maxLength={18} readOnly={ro} value={ro?money(calc.values[code]||0):(d.values[code]??'')} onChange={e=>value(code,e.target.value)}/></div>;
const line=(label:string,code:string,ro=false,int=false)=><div className="tax-line" key={code}><span>{label}</span>{cell(code,ro,int)}</div>;
const identification303=<Section title="Datos identificativos"><div className="identification-panel"><div className="devengo-fields"><TextInput label="Año *" value={d.year} onChange={v=>update('year',v)} maxLength={4}/><Choice label="Periodo *" value={d.period} onChange={v=>update('period',v)} options={periodOptions}/></div><div className="identity-fields"><TextInput label="NIF *" value={d.nif} onChange={v=>update('nif',v.toUpperCase())} maxLength={16}/><TextInput label="Apellidos o Razón Social *" value={d.company} onChange={v=>update('company',v)} maxLength={100}/><TextInput label="Nombre" value={d.firstName||''} onChange={v=>update('firstName',v)} maxLength={60}/></div>{d.model==='303'&&<div className="identity-questions">{identificationQuestions.map(q=><div key={q.key}><label className="identity-question"><span>{q.label} (SI/NO)</span><i/><select aria-label={q.label} value={d.identification?.[q.key]??q.initial} onChange={e=>update('identification',{...d.identification,[q.key]:e.target.value})}><option value="SI">SI</option><option value="NO">NO</option></select></label>{q.key==='concurso'&&<><label className="identity-question"><span>Fecha en que se dictó el auto de declaración de concurso</span><i/><input type="date" aria-label="Fecha del auto de concurso" disabled={d.identification?.concurso!=='SI'} value={d.identification?.concursoFecha||''} onChange={e=>update('identification',{...d.identification,concursoFecha:e.target.value})}/></label><div className="identity-question"><span>Si se ha dictado auto de declaración de concurso en este periodo indique el tipo de autoliquidación</span><i/>{['Preconcursal','Postconcursal'].map(v=><label className="radio-label" key={v}><input type="radio" name="concursoTipo" disabled={d.identification?.concurso!=='SI'} checked={d.identification?.concursoTipo===v} onChange={()=>update('identification',{...d.identification,concursoTipo:v})}/>{v}</label>)}</div></>}</div>)}</div>}<TextInput label="Alumno / referencia de la práctica" value={d.alias} onChange={v=>update('alias',v)} maxLength={80} placeholder="Opcional"/><p className="micro">Utilice los datos de la empresa simulada. El NIF no se comprueba contra ningún registro real.</p>{d.model==='303'&&<><p className="micro">Liquidación disponible: régimen general y territorio común. Puede cumplimentar las preguntas de identificación; si selecciona un supuesto especial todavía no desarrollado, la validación se lo indicará antes de presentar.</p><Button className="identity-continue" onClick={()=>setPart('general')}>Aceptar y continuar</Button></>}</div></Section>;
const identityCore=<div className="retention-identity"><TextInput label="NIF *" value={d.nif} onChange={v=>update('nif',v.toUpperCase())} maxLength={16}/><TextInput label="Apellidos o Razón Social *" value={d.company} onChange={v=>update('company',v)} maxLength={100}/><TextInput label="Nombre" value={d.firstName||''} onChange={v=>update('firstName',v)} maxLength={60}/></div>;
const devengo=<div className="devengo-fields"><TextInput label="Ejercicio *" value={d.year} onChange={v=>update('year',v)} maxLength={4}/><Choice label="Periodo *" value={d.period} onChange={v=>update('period',v)} options={periodOptions}/></div>;
const identification=d.model==='303'?identification303:<><Section title="Datos identificativos">{identityCore}</Section><Section title="Devengo">{devengo}</Section></>;
const complementary=d.model!=='303'&&<Section title="Declaración complementaria"><div className="complement"><p>Si esta autoliquidación es complementaria de otra anterior correspondiente al mismo concepto, ejercicio y periodo, indíquelo marcando esta casilla.</p><label><Switch checked={d.complementary} onCheckedChange={v=>update('complementary',v)}/> Declaración complementaria</label></div>{<TextInput readOnly={!d.complementary} label="N.º de justificante de la declaración anterior" value={d.previous} onChange={v=>update('previous',v)} maxLength={40}/>}</Section>;
function vatTable(rows:typeof deductions){return <div className="vat-table">{rows.map(r=><div className="vat-row" key={r.base}><span>{r.label}</span>{cell(r.base)}{cell(r.quota)}</div>)}</div>}
const vatGeneral=<Section title="Liquidación (3)"><h3>Régimen general</h3><h4>IVA devengado</h4><div className="vat-table"><div className="vat-row rate header-row"><span/><span>Base imponible</span><span>Tipo %</span><span>Cuota</span></div>{vatRows.slice(0,4).map(r=><div className="vat-row rate" key={r.base}><span>{r.label}</span>{cell(r.base)}{cell(r.rate,true)}{cell(r.quota,true)}</div>)}</div>{vatTable(otherVat.slice(0,3))}<h4>Recargo de equivalencia</h4><div className="vat-table">{vatRows.slice(4).map(r=><div className="vat-row rate" key={r.base}><span>{r.label}</span>{cell(r.base)}{cell(r.rate,true)}{cell(r.quota,true)}</div>)}</div>{vatTable(otherVat.slice(3))}{line('Total cuota devengada','27',true)}<h4>IVA deducible</h4><div className="vat-row header-row"><span/><span>Base</span><span>Cuota</span></div>{vatTable(deductions)}{['42','43','44'].map(k=>line(labels[k],k))}{line('Total a deducir','45',true)}{line('Resultado régimen general [27] − [45]','46',true)}</Section>;
const rectifying=<Section title="Autoliquidación rectificativa"><label className="check-line"><Checkbox checked={!!d.rectifying} onCheckedChange={v=>{setD(old=>({...old,rectifying:v===true,previous:'',rectificationReasons:[],values:{...old.values,'70':'','109':'','108':''}}));setErrors(null);}}/>Autoliquidación rectificativa</label>{d.rectifying&&<><p className="micro">Cumplimente de nuevo todas las operaciones del periodo con los datos correctos, no solo la diferencia respecto a la anterior declaración.</p><TextInput label="Número de justificante de la autoliquidación anterior *" value={d.previous} onChange={v=>update('previous',v)} maxLength={40}/><h4>Motivos de rectificación *</h4>{[{key:'general',label:'Rectificaciones (excepto incluidas en el motivo siguiente)'},{key:'criterio',label:'Discrepancia criterio administrativo'}].map(r=><label className="check-line" key={r.key}><Checkbox checked={!!d.rectificationReasons?.includes(r.key)} onCheckedChange={v=>{setD(old=>({...old,rectificationReasons:v?[...(old.rectificationReasons||[]),r.key]:(old.rectificationReasons||[]).filter(k=>k!==r.key),values:r.key==='criterio'&&!v?{...old.values,'108':''}:old.values}));setErrors(null);}}/>{r.label}</label>)}{line(labels['70'],'70')}{line(labels['109'],'109')}<p className="micro">En la primera rectificativa, la casilla 70 recoge el resultado positivo de la casilla 69 anterior, esté pagado o no. En la 109 indique las devoluciones ya acordadas del periodo; no las que solo se han solicitado. Si rectifica otra rectificativa, revise ambos importes conforme al historial del ejercicio.</p>{d.rectificationReasons?.includes('criterio')&&<>{line(labels['108'],'108')}<p className="micro">Use la casilla 108 únicamente cuando la discrepancia no pueda corregirse en las demás casillas. Admite signo positivo o negativo.</p></>}</>}</Section>;
const vatResult=<>{rectifying}<Section title="Resultado"><p className="micro">Tributación exclusiva en territorio común. Porcentaje atribuible al Estado: 100 %.</p>{line(labels['76'],'76')}{['64','65','66'].map(k=>line(labels[k],k,true))}{line(labels['77'],'77')}{line(labels['110'],'110')}{line(labels['78'],'78')}{line(labels['87'],'87',true)}{line('Resultado [66] + [77] − [78] + [108]','69',true)}{d.rectifying&&<>{line(labels['70'],'70',true)}{line(labels['109'],'109',true)}</>}{line('Resultado de la liquidación [69] − [70] + [109]','71',true)}{d.rectifying&&line(labels['111'],'111',true)}<label className="check-line"><Checkbox checked={d.inactive} onCheckedChange={v=>update('inactive',v===true)}/>Sin actividad</label></Section></>;
return <><div className="tax-return"><a href={companyUrl("/")}>Aula de simulación</a><a href={companyUrl("/practicas")}>Mi práctica</a></div><Toaster position="top-right" richColors/><div className="training-strip"><ShieldCheck size={16}/><strong>SIMULACIÓN EDUCATIVA</strong><span>Sin validez tributaria · No conectada con la AEAT</span></div><header className="site-header"><button className="brand" onClick={()=>go('portal')} aria-label="Inicio de la sede de prácticas"><span className="government" role="img" aria-label="Gobierno de España, referencia visual"/><img src="./aeat.svg" width="230" height="42" alt="Agencia Tributaria · Sede electrónica (simulación)"/></button><div className="header-right"><span className="date">{clock}</span><Button className="personal" onClick={()=>go('history')}><UserRound size={19}/> ÁREA PERSONAL</Button><span>ES </span></div></header>
<nav className="main-nav" aria-label="Menú principal"><DropdownMenu><DropdownMenuTrigger asChild><button>Sobre la Agencia Tributaria </button></DropdownMenuTrigger><DropdownMenuContent><DropdownMenuItem onClick={()=>setHelp(true)}>Acerca de esta simulación educativa</DropdownMenuItem></DropdownMenuContent></DropdownMenu><DropdownMenu><DropdownMenuTrigger asChild><button>Información y gestiones </button></DropdownMenuTrigger><DropdownMenuContent>{models.map(m=><DropdownMenuItem key={m} onClick={()=>choose(m)}>Modelo {m} · {shortNames[m]}</DropdownMenuItem>)}{reportModels.map(m=><DropdownMenuItem key={m} onClick={()=>openReport(m)}>Modelo {m} · {reportNames[m]}</DropdownMenuItem>)}</DropdownMenuContent></DropdownMenu><button onClick={()=>go('portal')}>Todas las gestiones</button><form className="search" onSubmit={e=>{e.preventDefault();go('portal');}}><input aria-label="Buscar modelos" value={search} onChange={e=>setSearch(e.target.value)} placeholder="Buscar por impuestos, gestiones, modelos..."/><button aria-label="Buscar"><Search size={18}/></button></form></nav>
<div className="breadcrumbs"><button onClick={()=>go('portal')}>Inicio</button><span>/</span><button onClick={()=>go('portal')}>Todas las gestiones</button><span>/</span><span>{view==='history'?'Área personal':view==='portal'?'Impuestos, tasas y prestaciones patrimoniales':`Modelo ${view==='report'?reportModel:model}`}</span></div>
{['portal','procedure'].includes(view)&&<div className="portal-layout"><aside className="model-nav" aria-label="Modelos disponibles">{models.map(m=><button className={view==='procedure'&&model===m?'selected':''} onClick={()=>choose(m)} key={m}><span>Modelo {m}. {names[m]}</span></button>)}{reportModels.map(m=><button onClick={()=>openReport(m)} key={m}><span>Modelo {m}. {reportNames[m]}</span></button>)}</aside><main className="procedure"><h1>{view==='portal'?'Impuestos, tasas y prestaciones patrimoniales':`Modelo ${model}. ${names[model]}`}</h1><section className="highlight"><h2><SquarePen/>Gestiones destacadas</h2><a className="vf-portal-link" href={companyUrl("/servicios/agencia-tributaria/verifactu")}><strong>Facturación VERI*FACTU</strong><span>Emite facturas con la imagen de tu empresa, importa PDF de Aplifisa y consulta sus registros.</span></a>{view==='portal'?<div className="model-links">{models.filter(m=>(m+' '+names[m]).toLowerCase().includes(search.toLowerCase())).map(m=><button key={m} onClick={()=>choose(m)}>Modelo {m}. {names[m]}</button>)}{reportModels.filter(m=>(m+' '+reportNames[m]).toLowerCase().includes(search.toLowerCase())).map(m=><button key={m} onClick={()=>openReport(m)}>Modelo {m}. {reportNames[m]}</button>)}{[...models,...reportModels].every(m=>!(m+' '+(names[m as Model]||reportNames[m as ReportModel])).toLowerCase().includes(search.toLowerCase()))&&<p>No se han encontrado modelos. Pruebe con 303, 111, 115, 190, 347 o 349.</p>}</div>:<><div className="presentation-link"><button onClick={()=>go('access')}>Modelo {model}. {model==='303'?'Ejercicio 2026':'Ejercicio 2020 y siguientes'}. Presentación</button><button className="help-link" onClick={()=>setHelp(true)}><HelpCircle size={17}/>Ayuda</button></div><button className="all-link" onClick={()=>go('history')}>Consulta de declaraciones presentadas</button></>}</section><section className="info-section"><h2><Info/>Información</h2><button onClick={()=>setHelp(true)}>Instrucciones para la presentación</button><p className="practice-note">Sede de prácticas · Modelos 303, 111, 115, 190, 347 y 349<br/>Acceso con certificado electrónico ficticio.</p></section><details className="normative"><summary>Información del simulador </summary><p>Reproducción didáctica de la sede electrónica para cumplimentar y presentar declaraciones ficticias. Los borradores y justificantes se guardan solo en este navegador.</p><p>El modelo 303 incluye el régimen general, con autoliquidaciones ordinarias y rectificativas, sin regímenes especiales. Estructura de referencia: 2026.</p></details><button className="procedure-file" onClick={()=>setHelp(true)}><FileText size={18}/>Ficha del procedimiento</button></main></div>}
{view==='report'&&<ReportWorkspace key={reportModel+'-'+reportHistory} model={reportModel} showHistory={reportHistory} onExit={()=>go('portal')}/>}
{view==='access'&&<main className="access-page"><h1>Modelo {model}. {shortNames[model]}</h1><section className="access-box"><h2>Seleccione el tipo de acceso</h2><button className="certificate-button" onClick={()=>setCertOpen(true)}><KeyRound/><span>Certificado o DNI electrónico</span></button><p>En esta sede se utilizará un certificado de prácticas. No necesita instalar ni aportar un certificado real.</p><button className="back-link" onClick={()=>go('procedure')}>Volver</button></section></main>}
{view==='form'&&<main className={'form-page model-'+d.model}><div className="form-heading"><img src="./aeat.svg" width="170" alt="Agencia Tributaria (simulación)"/><h1>{d.model==='303'?'Modelo 303. Impuesto sobre el Valor Añadido. Autoliquidación.':d.model==='111'?'Impuesto sobre la Renta de las Personas Físicas. Retenciones e ingresos a cuenta sobre el trabajo, actividades económicas, premios y determinadas ganancias patrimoniales e imputaciones de renta. Modelo 111 - Autoliquidación Empresas':'Modelo 115. Retenciones e ingresos a cuenta sobre arrendamientos de inmuebles urbanos. Autoliquidación'}</h1><button onClick={()=>setHelp(true)} aria-label="Ayuda del modelo"><HelpCircle/></button></div><div className="session-bar"><span><ShieldCheck size={16}/>Certificado de prácticas: {certs[certificate].company}</span><button onClick={()=>go('portal')}><LogOut size={15}/>Salir</button></div>
{d.model==='303'?<Tabs value={part} onValueChange={setPart} className="form-tabs"><TabsList><TabsTrigger value="identificacion">Identificación</TabsTrigger><TabsTrigger value="general">Régimen general</TabsTrigger><TabsTrigger value="adicional">Información adicional</TabsTrigger><TabsTrigger value="resultado">Resultado</TabsTrigger></TabsList><TabsContent value="identificacion">{identification}</TabsContent><TabsContent value="general">{vatGeneral}</TabsContent><TabsContent value="adicional"><Section title="Información adicional">{['59','60','120','122','123','124'].map(k=>line(labels[k],k))}</Section></TabsContent><TabsContent value="resultado">{vatResult}</TabsContent></Tabs>:<>{identification}<Section title="Liquidación">{d.model==='115'?<><h3>Retenciones e ingresos a cuenta</h3>{line('Número de perceptores','01',false,true)}{line('Base de las retenciones e ingresos a cuenta','02')}{line('Retenciones e ingresos a cuenta','03')}{line('A deducir (exclusivamente en caso de declaración complementaria): resultado a ingresar de anteriores declaraciones del mismo concepto, ejercicio y periodo','04',!d.complementary)}{line('Resultado a ingresar ([03] − [04])','05',true)}</>:<>{groups111.map(g=><div className="retention-group" key={g.title}><h3>{g.title}</h3>{g.rows.map(r=><fieldset key={r.codes[0]}><legend>{r.label}</legend><div className="triplets">{r.codes.map((k,i)=><div key={k}><span>{retentionColumns(r.codes[0])[i]}</span>{cell(k,false,i===0)}</div>)}</div></fieldset>)}</div>)}<h3>Total liquidación</h3>{line('Suma de retenciones e ingresos a cuenta','28',true)}{line('A deducir: resultado a ingresar de anteriores declaraciones','29',!d.complementary)}{line('Resultado a ingresar ([28] − [29])','30',true)}</>}</Section>{complementary}<TextInput label="Alumno / referencia de la práctica" value={d.alias} onChange={v=>update('alias',v)} maxLength={80} placeholder="Opcional"/></>}
{errors!==null&&<div className={'validation '+(errors.length?'has-errors':'valid')} role="status"><h3>{errors.length?'Errores y avisos':'No existen errores en las comprobaciones del simulador'}</h3>{errors.length?<ul>{errors.map((e,i)=><li key={i}>{e}</li>)}</ul>:<p>Puede continuar con la presentación simulada. Revise que los datos coinciden con su ejercicio.</p>}</div>}
<div className="toolbar"><Button variant="outline" onClick={()=>setClear(true)}><Trash2/>Borrar</Button><Button variant="outline" onClick={save}><Save/>Guardar</Button><Button variant="outline" onClick={loadDraft}><FolderOpen/>Cargar</Button><Button variant="outline" onClick={()=>downloadPDF(d)}><FileText/>Vista previa</Button><Button variant="outline" onClick={check}><CheckCheck/>Validar declaración</Button><Button onClick={formalize}>{d.model==='303'?'Presentar declaración':'Formalizar Ingreso / Devolución'}</Button></div><p className="local-note">Guardar y Cargar utilizan únicamente este navegador. Descargue el PDF antes de cambiar de equipo.</p></main>}
{view==='receipt'&&receipt&&<main className="receipt-page"><div className="success"><CheckCircle2/><h1>Su presentación ha sido realizada con éxito</h1><p>Presentación simulada · Sin validez tributaria</p></div><Section title="Información de la presentación"><dl className="receipt-data"><dt>Modelo</dt><dd>{receipt.declaration.model} · {receipt.declaration.year} · {receipt.declaration.period}</dd><dt>Declarante</dt><dd>{receipt.declaration.company} {receipt.declaration.firstName}</dd><dt>NIF de prácticas</dt><dd>{receipt.declaration.nif}</dd><dt>Fecha de presentación</dt><dd>{new Date(receipt.date).toLocaleString('es-ES',{timeZone:'Europe/Madrid'})}</dd><dt>N.º de registro simulado</dt><dd>{receipt.id}</dd><dt>CSV ficticio</dt><dd>{receipt.csv}</dd><dt>Tipo de declaración</dt><dd>{receipt.declaration.rectifying?'Autoliquidación rectificativa · ':''}{receipt.method}</dd>{receipt.declaration.rectifying&&<><dt>Justificante anterior</dt><dd>{receipt.declaration.previous}</dd></>}{receipt.bank&&<><dt>IBAN de prácticas</dt><dd>{receipt.bank}</dd></>}<dt>Resultado</dt><dd><strong>{money(receipt.result)} €</strong></dd></dl></Section><div className="receipt-actions"><Button onClick={()=>downloadPDF(receipt.declaration,receipt)}>Descargar justificante PDF</Button><Button variant="outline" onClick={()=>go('history')}>Consultar mis presentaciones</Button><Button variant="outline" onClick={()=>go('portal')}>Nueva declaración</Button>{receipt.declaration.model==='303'&&!receipt.declaration.rectifying&&<Button variant="outline" onClick={()=>rectify(receipt)}>Rectificar esta declaración</Button>}</div><p>Descargue y conserve el justificante. Siga las indicaciones de su docente para entregarlo.</p></main>}
{view==='history'&&<main className="history-page"><h1>Área personal</h1><h2>Consulta de declaraciones presentadas</h2><div className="report-actions">{reportModels.map(m=><Button key={m} variant="outline" onClick={()=>openReport(m,true)}>Consultar modelo {m}</Button>)}</div><p>Presentaciones simuladas guardadas en este navegador.</p><div className="report-actions"><DeleteRecord title="Declaraciones tributarias" label="Borrar declaraciones" localDelete={()=>{localStorage.removeItem("aula-presentaciones-v1");setHistory([]);}}/></div>{history.length?<Table><TableHeader><TableRow><TableHead>Modelo</TableHead><TableHead>Declarante</TableHead><TableHead>Ejercicio / periodo</TableHead><TableHead>Resultado</TableHead><TableHead>Justificante</TableHead></TableRow></TableHeader><TableBody>{history.map(r=><TableRow key={r.id}><TableCell>{r.declaration.model}</TableCell><TableCell>{r.declaration.company}</TableCell><TableCell>{r.declaration.year} / {r.declaration.period}</TableCell><TableCell>{money(r.result)} €</TableCell><TableCell><Button variant="link" onClick={()=>{setReceipt(r);setModel(r.declaration.model);go('receipt');}}>Consultar</Button><Button variant="outline" onClick={()=>downloadPDF(r.declaration,r)} aria-label={'Descargar '+r.id}>Descargar</Button><DeleteRecord id={r.id} title={"Modelo "+r.declaration.model+" · "+r.id} localDelete={()=>{const next=history.filter(x=>x.id!==r.id);localStorage.setItem("aula-presentaciones-v1",JSON.stringify(next));setHistory(next);}}/></TableCell></TableRow>)}</TableBody></Table>:<div className="empty-state"><FileText/><p>No constan presentaciones en este navegador.</p><Button onClick={()=>go('portal')}>Presentar una declaración</Button></div>}</main>}
<footer><span>Sede de prácticas · Simulación educativa</span><button onClick={()=>setHelp(true)}>Ayuda y alcance del simulador</button><span>No se realizan pagos ni presentaciones reales.</span></footer>
<Dialog open={presenter111} onOpenChange={setPresenter111}><DialogContent><DialogTitle>Nueva Declaración</DialogTitle><DialogDescription>Seleccione el tipo de presentador:</DialogDescription><label className="check-line"><Switch checked={true} onCheckedChange={()=>{}}/>Presentador Empresa</label><label className="check-line"><Switch checked={false} disabled/>Presentador Administración Pública</label><p className="micro">Esta sede de prácticas está preparada para declaraciones de empresas.</p><div className="modal-actions"><Button variant="outline" onClick={()=>setPresenter111(false)}>Cancelar</Button><Button onClick={()=>{setPresenter111(false);go('form');}}>Aceptar</Button></div></DialogContent></Dialog>
<Dialog open={initial115} onOpenChange={setInitial115}><DialogContent className="initial-115"><DialogTitle>Datos identificativos</DialogTitle><DialogDescription>Modelo 115. Indique los datos para iniciar la declaración.</DialogDescription>{devengo}{identityCore}<div className="modal-actions"><Button variant="outline" onClick={loadDraft}>Cargar</Button><Button onClick={()=>{if(!d.company.trim()||!d.nif.trim()||!/^\d{4}$/.test(d.year)){toast.error('Cumplimente el NIF, la razón social y el ejercicio.');return;}setInitial115(false);go('form');}}>Aceptar</Button></div></DialogContent></Dialog>
<Dialog open={certOpen} onOpenChange={setCertOpen}><DialogContent className="certificate-dialog"><DialogTitle>Seleccionar un certificado</DialogTitle><DialogDescription>Seleccione el certificado ficticio con el que desea identificarse.</DialogDescription><div className="cert-list">{certs.map((c,i)=><button key={c.nif} className={certificate===i?'active':''} onClick={()=>setCertificate(i)}><KeyRound/><span><strong>{c.company}</strong><small>{c.nif} · Emisor: Autoridad de prácticas · SIMULADO</small></span>{certificate===i&&<CheckCircle2 size={18}/>}</button>)}</div><div className="modal-actions"><Button variant="outline" onClick={()=>setCertOpen(false)}>Cancelar</Button><Button onClick={start}>Aceptar</Button></div><p className="micro">Si selecciona otra empresa, podrá editar su razón social y NIF en la declaración.</p></DialogContent></Dialog>
<Dialog open={help} onOpenChange={setHelp}><DialogContent className="help-dialog"><DialogTitle>Ayuda de la sede de prácticas</DialogTitle><DialogDescription>Practique la presentación electrónica de una declaración.</DialogDescription><ol><li>Seleccione el modelo y pulse Presentación.</li><li>Acceda con uno de los certificados ficticios.</li><li>Indique la empresa, el ejercicio y el periodo (mes o trimestre). Cumplimente los datos de su ejercicio.</li><li>Pulse Validar declaración y revise los errores.</li><li>Formalice el ingreso o devolución, pulse Firmar y enviar y marque Conforme.</li><li>Descargue el justificante PDF y entréguelo según las indicaciones de su docente.</li></ol><p><strong>Alcance:</strong> los modelos 111 y 115 incluyen liquidación y complementarias. El 303 trabaja con régimen general, territorio común y periodos mensuales o trimestrales; incluye rectificativas, pero no regímenes especiales. La devolución se ofrece en 4T, diciembre o en periodos mensuales con inscripción en REDEME. Estructura de referencia: 2026.</p><p>Las comprobaciones son didácticas y no equivalen a todas las validaciones oficiales. Los datos se guardan solo en este navegador; no se envían al docente automáticamente.</p><p><strong>Referencia contrastada:</strong> formulario 303 de 2026 y servicios vigentes de presentación del 111 y 115. Revisión: 18/09/2026. El diseño del PDF es una reproducción didáctica; no es un documento emitido por la AEAT.</p><p>Referencias oficiales (abren otra página):</p><div className="reference-links">{models.map(m=><a key={m} href={officialHelp[m]} target="_blank" rel="noreferrer">AEAT · Modelo {m}</a>)}</div></DialogContent></Dialog>
<Dialog open={payment} onOpenChange={setPayment}><DialogContent><DialogTitle>Formalizar Ingreso / Devolución</DialogTitle><DialogDescription>Modelo {d.model} · {d.year} · {d.period}</DialogDescription><div className="payment-total">Resultado de la liquidación <strong>{money(calc.result)} €</strong></div><Choice label="Seleccione el tipo de declaración" value={method} onChange={v=>{setMethod(v);setPayErrors([]);}} options={calc.result>0?[{value:'domiciliacion',label:'Domiciliación del importe a ingresar'},{value:'ingresar',label:'A ingresar (con NRC)'},{value:'deuda',label:'Reconocimiento de deuda'}]:calc.result<0?(allocation.credit>0?[{value:'compensar',label:allocation.correction>0?'A compensar y rectificación':'A compensar'},...(canRefund(d)?[{value:'devolver',label:allocation.correction>0?'Solicitud de devolución y rectificación':'Solicitud de devolución'}]:[])]:[{value:'rectificar',label:'Rectificación de la autoliquidación anterior'}]):[{value:'negativa',label:d.model==='303'?'Resultado cero / sin actividad':'Negativa (resultado cero)'}]}/>{needsBank&&<><TextInput label="Código IBAN de prácticas" value={d.iban||''} onChange={v=>{update('iban',v.toUpperCase());setPayErrors([]);}} maxLength={34} placeholder="ES00 0000 0000 0000 0000 0000"/><p className="micro">Si no dispones de IBAN, usa ES00 0000 0000 0000 0000 0000.</p></>}{method==='ingresar'&&<><TextInput label="NRC de prácticas" value={nrc} onChange={()=>{}} readOnly placeholder="Pendiente de pago simulado"/><Button variant="outline" onClick={()=>{setNrc('SIM'+simulationId().replace(/-/g,'').slice(0,19).toUpperCase());setPayErrors([]);}}>Realizar pago (NRC simulado)</Button></>}{method==='deuda'&&<p className="micro">Se registrará un reconocimiento de deuda ficticio. La tramitación del aplazamiento queda fuera de esta práctica.</p>}{allocation.correction>0&&<p className="micro">Casilla 111 · Importe a regularizar por la rectificación: <strong>{money(allocation.correction)} €</strong>. Según el supuesto del ejercicio, corresponde a devolución de ingresos o modificación de la domiciliación o deuda anterior. El IBAN se utilizará si procede la devolución.</p>}{method==='devolver'&&<p className="micro">Casilla 73 · Solicitud de devolución: <strong>{money(allocation.refund)} €</strong> (incluye las cuotas previas pendientes).</p>}{method==='compensar'&&<p className="micro">Casilla 72 · Importe a compensar: <strong>{money(allocation.compensation)} €</strong>.</p>}{payErrors.length>0&&<p role="alert" className="error-text">{payErrors.join(' ')}</p>}<p className="micro">Los datos de pago son ficticios. No se realizará ningún cargo ni envío a Hacienda.</p><div className="modal-actions"><Button variant="outline" onClick={()=>setPayment(false)}>Cancelar</Button><Button onClick={prepareSign}>Firmar y enviar</Button></div></DialogContent></Dialog>
<Dialog open={sign} onOpenChange={setSign}><DialogContent><DialogTitle>Firma y envío de la declaración</DialogTitle><DialogDescription>Revise la declaración antes de confirmar su presentación simulada.</DialogDescription><div className="signature-summary"><p><strong>Modelo:</strong> {d.model} · {d.year} · {d.period}</p><p><strong>Declarante:</strong> {d.company} {d.firstName}</p><p><strong>NIF:</strong> {d.nif}</p><p><strong>Resultado:</strong> {money(calc.result)} €</p><p><strong>Tipo:</strong> {methodLabel(method)}</p>{needsBank&&<p><strong>IBAN:</strong> {d.iban}</p>}</div><label className="check-line"><Checkbox checked={conform} onCheckedChange={v=>setConform(v===true)}/><strong>Conforme</strong></label><p className="micro">Firma realizada con un certificado ficticio. Presentación sin validez tributaria.</p><div className="modal-actions"><Button variant="outline" onClick={()=>{setSign(false);setPayment(true);}}>Volver</Button><Button disabled={!conform} onClick={send}>Firmar y enviar</Button></div></DialogContent></Dialog>
<AlertDialog open={clear} onOpenChange={setClear}><AlertDialogContent><AlertDialogTitle>¿Borrar la declaración actual?</AlertDialogTitle><AlertDialogDescription>Se vaciarán las casillas del formulario. Las presentaciones anteriores y el borrador guardado se conservarán.</AlertDialogDescription><AlertDialogFooter><AlertDialogCancel>Cancelar</AlertDialogCancel><AlertDialogAction onClick={()=>{setD(blank(d.model,d.company,d.nif));setErrors(null);setPart('identificacion');}}>Borrar declaración</AlertDialogAction></AlertDialogFooter></AlertDialogContent></AlertDialog>
</>;
}
